#+LATEX_CLASS: article

# -*- mode: org; -*-
#+LATEX_CLASS_OPTIONS: [a4paper, 10pt, twocolumn, spanish]
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[margin=.75in]{geometry}
#+LATEX_HEADER: \setlength\parindent{0pt}

#+Title: Apuntes de Teoría del Conocimiento ii
#+SUBTITLE: Sobre Nietzsche y su pensamiento tardío
#+AUTHOR: Jordi Serra

* Introducción
En su última etapa intelectual, que se verá truncada por el colapso
menta que sufre en 1889, Nietzsche hace un ejercicio de autocrítica y
autointerpretación de su trayectoria anterior que culmina con su
última obra /Ecce homo/, una autobiografía intelectual. También
trabajó en la preparación de una gran obra que debería sintentizar
todo su pensamiento y llevaría el título de /la voluntad de poder:/
/ransvaloración de todos los valores/. Este proyecto fue abandonado
quedando sus materiales que no fueron incorporados en las obras en
elaboración forman parte de su importantísimo legado póstumo.\\

En este período reaparecen tamáticas propias de los escritos
anteriores junto con novedades importantísimas. Aparecen los grandes
temas de voluntad de poder, el eterno retorno, el nihilismo, la muerte
de Dios, la transvaloración o el übermensch —el hombre del más
allá. Estos temas se presentan de una poético-alegórico en el /Así/
/habló Zaratustra/ o bien de manera más o menos conceptualmente
argumentadas en el resto de sus obras de éste periodo.\\

/Así habló Zaratustra/ empieza donde concluía el recorrido que habían
llevado a cabo las obras precedentes, cuya aportación fundamental
había sido la comprensión de las estructuras metafísicas y de Dios
como su fundamento como un invención —cómo el mundo verdadero acabó
convirtiéndose en una fábula.\\

Con ello la apariencia fenoménica del mundo quedaba rehabilitada y
liberada de su descrédito y del desprecio que caía sobre ella durante
la vigencia del dualismo metafísico.\\

A la idea del eterno retorno se le atribuye un sentido de un destino
cargado de consecuencia para la historia de Europa. De esta idea parte
prácticamente todo el desarrollo de su último pensamiento, que se
centra en el programa de una transvaloración de todos los
valores. Esto implica todo un nuevo modo de concebir el valor de la
filosofía y la figura y la misión del filósofo, que representa una
transformación sustantiva respecto a lo que ofrecen las obras
crítico-genealógicas anteriores.  La primera gran novedad es la
convicción de que es posible partir de la crítica moderna a la cultura
occidental para provocar una mutación readical de la civilización
occidental.\\
Las obras críticas anteriores ponían de manifiesto que las creencias
metafísicas, religiosas y morales del pasado habían ido perdiendo su
carácter de solución teórica y por tanto su utilidad práctica como
supraestructura de ideas al servicio de la organización de vida.\\

*Dios ha muerto*. Esta liquidación del mundo verdadero suscita una
actitud de *libertad de espíritu* ante los errores sobre los que se
fundamente necesariamente la vida, sobre las invenciones y
*construcciones morales*, religiosas e ideológicas que han sido
necesarias para vivir y organizar la sociedad.\\

Estas obras crítico-genealógicas expresan la actitud de quien se asoma
un momento por encima de todo proceso histórico y contempla como un
espectáculo las equivocaciones que han hecho profundo, rico y matizado
nuestro mundo. Nietzsche atribuye ahora a su pensamiento una
intencionalidad práctica, una pretensión de servir como impulsor de
una transformación de la época moderna en el sentido de una superación
de su nihilismo.\\

Nietzsche piensa ahora en el filósofo como un legislador, un creador
de valores con los que fundar una nueva época y una nueva historia. Es
preciso legislar con vistas a una nueva humanidad. El filósofo se
diferencia pues del trabajador filosófico y de los científicos en que
el filósofo se le exige, le es necesario que cree valores, y no sólo
usar aquellos antiguos patrones de valores fijados y que se usan de
una manera mecánica. El autentico filósofo es el que manda y
legisla. Ellos dicen deciden como deben ser las cosas, determinan el
primero el /hacia donde/ y el /para qué/ del hombre, y para ello
disponen del trabajo previo de todos los trabajadores filosóficos, de
todos los subyugadores del pasado. Su conocer es cread, su creas es
una legislación, su voluntad es *voluntad de poder*.\\

Desde esta perspectiva se entiende su radicalización de su crítica al
cristianismo, tal como la desarrolla en el /Anticristo/. Nietzsche se
confronta con el mundo de ideas e instituciones que más universalmente
ha configurado la historia europea y con la ideología más directamente
responsable del nihilismo.\\

El *nihilismo* lo comprende como nuestra situación contemporánea de
olvido o de pérdida del valor de los antiguos valores supremos que
sostenían la cosmovisión cristiana del mundo. No obstante, el
nihilismo es también un proceso activo, y no sólo pasivo, en virtud
del cual se ha producido la muerte de Dios.\\

Es decir, la *muerte de Dios* no ha consistido en ninguna práctica
voluntarista del ateísmo militante no en el ejercicio destructivo
propiamente dicho del tipo de crítica teórica que el propio N. había
desarrollado hasta ahora. Es el desenlace o el punto final de un
proceso al término del cual ha venido a hacerse luz, o a recordarse
algo que se encontraba ya en germen en el propio planteamiento
original con el que nació.\\
El nihilismo no es otra cosa que ese trabajo mismo de
desenmascaramiento-rememoración de los valores supremos y de Dios como
su fundamento que la historia ha realizado, deslegitimándolos a la
manera de un proceso de autosuperción en el que se reconstruye la
lógica nihilista de los proios conceptos metafísico-morales de verdad
y de bien.\\

En suma, el punto de partida de las obras que inicia /Zaratustra/ es
la comprensión de que ésta es una historia en la que la memoria —hecha
presente en el trabajo hsitórico-genealógico— acaba ganándole la
partida al olvido, pues ha sido la misma exigencia de la búsqueda de
la verdad y de autenticidad que siempre han propugnado la metafísica y
la moral cristianas, la que ha terminado conduciendo finalmente a la
exhumación de sus propios fundamentos nihilistas.\\
La misma exigencia moral de veracidad es la que termina por descubrir
las intenciones ocultas y olvidadas de la práctica de
culturización-domesticación que ha predominado como eje del proceso
civilizatorio en Occidente, sacando a la luz el trasfondo de pura
ideología al servicio de unas determinadas condiciones de existencia y
de una determinada forma de ejercicio del poder.\\

Así, el pensamiento del último Nietzsche tiene la pretensión, no sólo
ya de proponer un sentido a dar a sus principales filosofemas, sino
que es necesario también, mostrar los vínculos que los articulan y que
le dan la consistencia que justifica la importancia de su capacidad
para el desarrollo de nuestro presente y su influencia en la
configuración de muchas de las corrientes de la filosofía posterior.

* El eterno retorno
El pensamiento del eterno retorno —que implica sustancialmente la
reducción del tiempo lineal de la historia al tiempo cíclico de la
naturaleza— no obedece sólo a restaurar la visión griega clásica,
presocrática, del mundo, anterior al dualismo metafísico
platónico-cristiano. Tampoco parece sólo un modo de rechazar la
comprensión judeo-cristiana del tiempo que lo entiende formando
momento sucesivos e irrepetibles, según el modelo de la historia
sagrada —creación, pecado, redención, escatología.\\
Aunque obedece al propósito anticristiano de anudar la época moderna a
la Antigüedad naturalista y pagana, Nietzsche lo plantea como el
pensamiento que lleva a su consumación el nihilismo y como la
condición para su superación.

La idea subyacente es la de que sólo en un mundo en el que no se
pensara ya según la estructura de la temporalidad lineal, sería
posible la felicidad plena.\\
El tiempo lineal supone que cada momento tiene sentido sólo en función
de los otros, precedentes y siguientes, y esto hace imposible la
felicidad, porque ningún momento vivido puede tener él mismo una
plenitud de sentido.\\

La temporalidad lineal implica la diferencia esencial entre el ser que
en cada momento se es, deficitario y siempre imperfecto, y de un
deber-ser como modelo y meta ideal que nunca se alcanza.\\
Establece la diferencia entre mundo verdadero, como mundo de realidad,
y mundo aparente, como ilusión y engaño.\\

La creencia en la temporalidad circular implicaría la supresión de la
ditinción entre mundo verdadero y mundo aparente, así como la
existente entre ser y deber ser.\\

El eterno retorno es un pensamiento selectivo en la medida en que
muestra la mentira de la metafísica y de la moral platónico-cristiana
al destruir las distinciones /mundo verdadero/-/mundo aparente/, ser y
deber ser, y hace imposible así el modo de vivir del hombre nihilista.\\

El eterno retorno es propio sólo del ser humano feliz, que se da
únicamente en una época o cultura radicalmente distinta a la del
nihilismo.\\

En este mundo nuevo, pensar en la posibilidad de que cada instante de
nuestra vida pudiera repetirse eternamente hasta el infinito
significaría un criterio de valoración ética, porque sólo cuando ese
instante es pleno de sentido y de felicidad se puede querer tal
repetición.\\

En la última etapa N. alude a nociones y conceptos que no desarrolla
explícitamente. Se refiere a ellos con ambigüedades de meros símbolos
poéticos y de alegorías. Con el concepto del eterno retorno pasa
esto. Incluso insiste en la necesidad de asumirlo sin que haya sido
expuesto anteriormente.\\

Desde esta perspectiva, se entiende que N. no piensa en la idea del
eterno retorno como una teoría sobre el ser del tiempo, alternativa a
la concepción metafísica vigente. Sino como de una profecía se
tratase, un anuncio o una doctrina. Lo plantea menos como una fórmula
o un enunciado dirigido al entendimiento y a la comprensión que como
la expresión de un reto, un conjuro y de una tarea dirigidos a la
voluntad.\\
EL eterno retorno tendría que ser el objeto de una experiencia, de una
decisión de la voluntad, como una consecuencia o prueba de la
concepción nietzscheana de la realidad, de la transvaloración de todos
los valores y de superación del nihilismo.\\

[Aún así, Nietzsche se preocupa de explicar la posibilidad de entender
el tiempo como eterno retorno. En la síntesis a la que llega muestra
su acuerdo con la afirmación de que la fuerza del universo es fija, ya
que si no fuese así, a lo largo del tiempo hubiera disminuido y
desaparecido. Pero tampoco aumenta indefinidamente, porque se así
fuese habría llegado a ser infinita, y esto es imposible.\\
En virtud de esta limitación total de la fuerza del universo, no es
más que un caos de luchas incesantes entre centros individualizados de
voluntad de poder.\\
Lo que preside el devenir del mundo no es más que el azar, y no hay
leyes naturales ni históricas que se cumplan a través de él.\\
Por otra parte las fuerzas no tienen libertad para decidir si se
ejercen o no, actúan necesariamente. El mundo resulta ser un
movimiento eternoo que nunca se interrumpe por el hecho de alcanzar un
equilibrio último de todas las fuerzas.\\
Esa eternidad e eternidad de un retorno.]\\

Esto es lo que se deduce de la alegoría del pastor y la serpiente en
/Zaratustra/. Liberándose del nihilismo, da paso a un /über/, a un más
allá del hombre como modo nuevo de ser y de existir. La decisión de
liberarse del nihilismo, es la de afirmar, la de decir sí al eterno
retorno de lo mismo con lo que ello implica y significa. Lo decisivo
en él no es su validez teórica, ni su coherencia lógica, ni su verdad
científica, sino su valor como conjuro, como conjuro de la más alta
afirmación de la vida que pueda imaginarse, que debe ser entendida,
irónicamente, como una nueva religión.\\

En este sentido señala cómo muchas representaciones de la religión
cristiana —e.g. el infierno, la condenación eterna, etc.— no tienen
ningún fundamento de verdad racional sin que eso les haya impedido
haber sido efectivamente incorporadas como condición de vida por los
cristianos y haber determinado durante siglos la dirección de su
comportamiento. Ha bastado con la coacción tiránica de un poder
autoritario como el de la Iglesia y mucho tiepo para que calara
profundamente.\\

De modo análogo debería suceder con el eterno retorno. No es preciso
que se demuestre como la verdadera realidad del tiempo Ni si quiera
necesita ser una idea verosímil o probable, sino que lo que tiene que
ser es una idea eficaz como instrumento de transformación y de
educación, una idea asumida porque simplemente se la quiera afirmar
como tal y decirle sí. En este dirigirse a la voluntad y a la decisión
es donde el eterno retorno encuentra su sentido propio y esa eficacia
transformadora o transfiguradora que N. le confiere.\\

El eterno retorno es la más alta afirmación de vida, el instrumento
necesario para discriminar entre hombres nihilistas y el
übermensch. En la concepción lineal del tiempo, puesto que cada
instante presente hace depender su existencia y su significado de su
conexión con el pasado, que ya no existe, u de su anticipación del
futuro, que todavía no existe, ninguno de los momentos del tiempo
lineal en su particularidad de presente, de pasado o futuro logran ser
momentos vivos, depositarios de una plenitud autónoma de significado y
de existencia. De este modo, la vida, su sentido y su valor se
encuentran siempre situados o más acá o más allá de un presente que
nunca realiza su cumplimiento.\\
Esta es la forma más extrema y radical que pueda pensarse de negación
de la vida, porque no implica sólo na desvalorización moral o una
negación general y global de ella, sino que representa su negación
instante por instante, despojarla de realidad y de valor al introducir
la no-existencia, la nada como contenido propio de cada uno de los
instantes que la constituyen.\\

De ahí la convicción del nihilista que vive según esta experiencia de
la temporalidad lineal de que la vida no es, en realidad, un vivir,
sino sólo un ilusorio pasar, una pura apariencia de sueño cuyo
trasfondo de nada la delata como sin sentido, como absurda en sí
misma, siendo necesario proyectar el sentido y el valor en un
trasmundo, un más allá, en una trascendencia.\\
La concepción lineal del tiempo es la manifestación principal del
resentimiento y del espíritu de venganza contra la vida, de modo que
sólo se superaría el nihilismo si se lograr entrar en otro modo de
entender y de vivir la temporalidad que fuese a su vez su redención.\\

El eterno retorno significa como ese otro modo de vivir el tiempo,
ofreciéndose como reto a la voluntad cuya afirmación haría entrar en
otra forma distinta de vivir la temporalidad .\\
El eterno retorno se ofrece como la decisión para un nuevo modo de
aplicar la exigencia ética de articular el tiempo, de modo que de ella
resulta el gozo y la afirmación de la vida en lugar de su extrema
negación.\\


*En qué consiste esta forma de vivir el tiempo, y qué es lo que
implica?*\\
El eterno retorno significa también vivir en el presente. El presente
ya no es este instante vacío, de no-ser, sino que es pleno y vivir en
él. Requiere reunir en el instante presente los recorridos de los
tiempos, del pasado y del futuro. Hay que ser capaz de reordenar la
sucesión vertiginosa de los momentos del tiempo lineal sometiendo su
pluralidad a una unidad para conferirles así un sentido nuevo.\\

El *modo de hacerlo* es imponiendo a esa unidad del instante presente
una forma, una interpretación que reinterprete el pasado que ha
conducido hasta aquí y reoriente el futuro articulando lo que todavía
no es más que un azar. Así, desde esta perspectiva, el pasado no sería
ya lo sucedido en sí, algo que yace detrás del presente de manera
inexorable ejerciendo sobre él una determinación fatal e irreversible,
sino que en cada momento del presente, se interpreta el pasado, se lo
recrea y reconstruye libremente. No es algo que escape a la libertad y
a la voluntad, sino que su sentido depende de lo que se quiera y se
decida en el presente que signifique.\\

Del mismo modo el futuro no es el ámbito de lo totalmente imprevisible
y azaroso, sino el espacio en el que se lanza un proyecto a partir de
una anticipación que se hace en función del conocimiento presente y de
la reinterpretación del pasado.\\
El futuro no está situado al margen de la libertad, de la capacidad de
control de la decisión de la voluntad. Se lo puede anticipar en cierta
medida y construir libremente desde el presente en función del sentido
que se quiera proyectar sobre él.\\

Por eso, sea como hay sido el pasado, es posible amarlo en la medida
en que siempre es posible reinterpretarlo viendo en él las condiciones
que han conducido al presente y a partir de la voluntad con la que se
da un sentido a la vida de cara al futuro. Este querer el pasado no es
ya ni resignación no fatalismo, sino que es quererlo al
reinterpretarlo en íntima conexión con el presente y el futuro.\\

Todo esto es dar una necesidad al tiempo, imponerle una forma
superando la falsa idea de su linealidad inexorable tal como la ha
enseñado la metafísica y la religión cristiana, que separan como
momentos irreconciliables e inconexos pasado, presente y futuro.\\
Y esto es también lo que significa asumir un destino como ley que
reorganiza una y otra vez la existencia, actualizando siempre de nuevo
las metas por las que discurre y haciendo posible así el despliegue
del impulso de autosuperación.

* El eterno retorno u la noción de interpretación
La contradicción entre el eterno retorno e historia se desvanece desde
el momento en que se comprende el eterno retorno como un
acontecimiento histórico, como algo que sucede y acontece dentro de la
historia. En vez de ser una verdad ontológica sobre el ser del sí del
tiempo, no sería más que una interpretación que cuando se adopta,
cuando se afirma, se vive la inanidad, la vacuidad, la futilidad de
todo sentido creído como significado o verdad en sí del mundo y se
descubre la inconsistencia de todos los pretendidos valores absolutos,
llegándose a la consumación del nihilismo. Asumiendo el eterno retorno
como interpretación, el individuo toma conciencia de que la historia
misma no es otra cosa que una confrontación incesante de
interpretaciones y de opciones de valor en la que la consumación final
del nihilismo no sería más que un acontecimiento de este tipo.\\

La aceptación del eterno retorno podría dar lugar a una reorientación
de la historia con valor de novedad sobre la que ya había, y
determinar su curso en la dirección precisamente que no permiten las
concepciones ontológicas: en la dirección de una libre creación del
destino de la humanidad al convencer a ésta de la ausencia de leyes
internas ocultas y de sentidos prestablecidos respecto de los cuales
los individuos sólo son seguidores e instrumentos.\\
Por eso, el eterno retorno puede cumplir una función dismitificadora,
desestabilizadora y corrosiva radical de las comprensiones metafísicas
de la historia, y teniendo un contenido un determinismo total e
incluso un fatalismo, puede, sin embargo, introducir el azar en el
concepto de historia.\\

Si el eterno retorno no es más que una interpretación instrumental, no
una verdad en sí, es compatible con una idea de la historia en la que
ninguna necesidad superior al individuo ordena el devenir al
cumplimiento de fines universales. La única necesidad que actúa en la
historia son los individuos, que se comportan a través de
interpretaciones y posiciones de valor. El devenir está abierto a
posibilidades distintas que sólo dependen de los seres humanos mismos,
de las interpretaciones y valoraciones que dan a su vida y a sus
actos. El eterno retorno no es más que una de estas interpretaciones,
con la que el ser humano podría superar el nihilismo.\\

Por otro lado, otra de las ventajas de este pensamiento del eterno
retorno es que permite entender la historia sin necesidad de pensar en
un final de ella como una ruptura y nuevo comienzo. Como simple
interpretación y como experiencia afirmativa, el eterno retorno puede
cambiar el curso de la historia inaugurando una etapa de mayor
autonomía y emancipación individual. Esto, no quiere decir que el
eterno retorno —la consumación del nihilismo— lleve la historia a su
final y le dé asó un nuevo sentido, aunque negativo, encerrándola en
una totalidad. El nihilismo no designa en N a la historia como tal,
sino sólo a la historia europea y, dentro de ella, a la época
presidida por la fe cristiana y sus consecuencias.\\

La consumación del nihilismo no puede hacer pensar en una teleología
catastrófica determinada por un destino como necesidad superior. No
hay más destino que el que se sigue de una opción histórica que no es
nada predeterminado como ley ontológica, sino un punto de partida
azaroso. El destino que obra en la historia del nihilismo es algo que
determinadas decisiones humanas crearon, no es el Ser el que destina
aquí, sino que son la decisiones humanas.\\

La historia así entendida no tendría ninguna unidad, no sería ninguna
totalidad cerrada entre un principio y un final únicos. Sería sin
principio ni fin. La historia no es más que la sucesión de posiciones
de valor y significados perspectivas en lucha, a través de los cuales
diferentes tipos de individuos tratan de justificarse y predominar
sobre los demás. El cometido a cumplir por la idea del eterno retorno
no es más que el de presentarse como una interpretación instrumental
para modificar la comprensión de la historia, y dejar de verla
justamente como un proceso ontológico.\\

La acción renovadora, autosuperadora que se desea promover, no
significa no representa ningún corte, el final de la historia y el
comienzo de un más allá, sino sólo un cambio que se produce dentro de
la historia, una transformación cuya estructura no es sustancialmente
distinta a la estructura de misma del devenir histórico y del devenir
del mundo en general, un simple cambio de interpretaciones y de
valoraciones, una transvaloración.\\

La transvaloración no es más que una confrontación entre
interpretaciones, un acontecimiento más en la cadena de luchas y
enfrentamientos entre centros desiguales de poder, en torno a los que
gira, como su eje, el conjunto de todo lo que existe. Se trataría sólo
de una acontecimiento determinado por el triunfo de un tipo de
voluntad de poder que implicaría, si se produjera, la reorientación
del curso del curso de la historia en una dirección distinta a la que
le han dado el predominio de otras relaciones de fuerzas. No hay más
que un juego de voluntades de poder que es amoral, que no es tampoco
ontológico, y que no puede dar apoyo a ideologías ni verdaderas ni
falsas, ni buenas ni malas, sino tan solo provechosa o perjudiciales
relativamente, según la óptica de la vida y por referencia a un
individuo o a un grupo de individuos determinado.\\

* La hipótesis de la voluntad de poder
La propuesta nietzscheana de la voluntad de poder tiene el carácter de
una simple hipótesis y no el de una tesis ontológica o incluso
metafísica. Esta hipótesis se formula para explicar y comprender, de
manera particular y concreta , el movimiento, la acción o el acontecer
del mundo, contraponiéndola al modo en que este acontecer había sido
explicado tanto por la metafísica como por la ciencia.\\

La voluntad de poder introduce la novedad de entender el universo como
un relacionarse entre sí de una pluralidad de centros de fuerza que
tienen las mismas características de lo que nosotros conocemos como
voluntad, como querer. No habría más motor que inicie e impulse el
movimiento del mundo que la interacción de estas fuerzas o voluntades
unas con otras.\\
Estas interacciones de voluntades sustituiría a la de la relación
causa-efecto, que era la base tanto de las explicaciones metafísicas
como científicos del acontecer del mundo.\\

La voluntad de poder se caracteriza por el /pathos/ del querer, que es
siempre un mandar. Frente al esquema anterior de causa y efecto,
N. trata de ofrecer un nuevo modelo explicativo que es el de la
relación mandar-obedecer.\\
Critica del modelo causa-efecto el recaer inevitablemente en un
determinismo: de las causas se siguen necesariamente los efectos, y
esto no puede ser más que así, si alteración posible.\\

Para Nietzsche lo que sucede es lo propio de la relación
mandar-obedecer, que hay una fuerza que quiere poder más que las demás
y que manda desde un sentido de superioridad o de mayor fuerza a las
fuerzas que quiere que le obedezcan. Lo que hay son fuerzas mayores o
más poderosas que tratan de dominar a las menos fuertes, las cuales
pueden, o bien ceder y obedecer a ese mandato, o bien resistirse y
negarse a doblegarse.\\

El mandar transmite algo que no es simplemente una orden externa que
se emite en el plano consciente. Por debajo de esta orden externa, lo
que transmite el mandar es un impulso, una fuerza que provoca en la
otra voluntad una modificación y una transformación concomitante. Se
produce en la voluntad a la que va dirigida el mandato desde dentro de
ella misma y de manera autónoma: Ante la presión del mandato ejercido
por la fuerza que se propone como superior, la fuerza destinataria
puede obedecer o bien resistirse al mandato. En los dos casos hay una
modificación que se produce desde dentro y autónomamente. No hay aquí
el determinismo externo de la relación causa-efecto, sin ninguna
posibilidad de que el efecto no se produzca. En cambio, en la relación
mandar-obedecer existe esa transformación desde dentro que se produce,
en las dos fuerzas en lucha, de manera autónoma.\\

Para Nietzsche el planteamiento de la ciencia moderna es ilusorio,
porque consiste en la simulación de estar fuera del mundo y tratar de
ver desde fuera relaciones externas de causa.efecto entre las
cosas. La ciencia moderna lo llama objetividad, porque uno de sus
principios básicos es el que de que el conocimiento científico no
puede tener nada de subjetivo.\\
Para Nietzsche esto es absurdo, porque no es posible salir uno de uno
mismo y del mundo para ver las cosas desde esa exterioridad
objetiva.\\
Propone es reconocer que nuestro acceso al conocimiento del mundo
parte, lo queramos o no, de dentro de nosotros mismos, y sobre todo
parte de la experiencia de nuestro propio cuerpo como lucha de fuerzas
y enfrentamiento de voluntades de poder. Su propuesta metodológica es:
tomar el cuerpo como hilo conductor de toda investigación; suponiendo
que nuestro mundo de apetitos y pasiones sea lo único real que está
dado, que no podamos ascender o descender hacia ninguna otra realidad
que precisamente la realidad de nuestras pulsiones, pues pensar es
solo una interacción de estas pulsiones entre sí. De aquí, es lícito
el planteamiento de si este estar dado no bastaría para comprender
también, partiendo de lo idéntico a sí mismo, el llamado mundo
mecánico, material, el mundo visto desde dentro, el mundo definido y
caracterizado de acuerdo con su carácter inteligible, sería justamente
voluntad de poder y nada más.\\

Nietzsche piensa que la energía constante total del mundo, movida por
la aspiración de las voluntades de poder que la integran hacia el
logro de un máximum de poder, alcanzaría un determinado novel cenital
de organización como suma de fuerzas en juego, como un vértice, en la
jerarquización interna del mundo. Una vez alcanzado, se hundiría
disgregándose de nuevo en una multiplicidad anárquica. Esto sería un
círculo eterno. El sentido de Dios sería Dios como estado máximo, como
un época, un punto en el desarrollo de la voluntad de poder desde el
cual se explicaría tanto el desarrollo ulterior como lo previo, la
hasta-él.\\
Dionisio es ese dios que muere despedazado y vuelve a renacer de sí
mismo como consecuencias de lo que la naturaleza es en cuanto
pluralidad de voluntades de poder. El caos del mundo no contradice el
orden de un retorno cíclico y regular. Ambas cosas proceden de lo que
la voluntad es. El devenir, el ciclo, se origina así en la lucha
incesante de las voluntades de poder.\\

Otro punto esencial de esto es el modo en que tiene lugar el combate
entre las fuerzas por lograr el máximo poder. Esto es justamente el
ejercicio de la evaluación y de a interpretación, la imposición por
parte de una fuerza dominante de un sentido o de un valor a las otra
fuerzas en función del juego de dominación propio de los afectos en
lucha.\\
Interpretar una cosa, evaluarla, es imponerle un significado o
conferirle un valor. Y ese es el medio más originario de intentar
dominarla.\\
Esta actividad de interpretación y de evaluación de la voluntad como
un proceso de digestión de la realidad por el que una fuerza crece
alimentándose de otras fuerzas. Esta asimilación es siempre selectiva,
empieza con un acto de discriminación de las fuerzas para asimilar
aquellas que se estiman como susceptibles de ser eficazmente
incorporadas, por su capacidad para autofortalecer y aumentar el nivel
propio de poder, mientras que todo lo que no se estima útil para este
fin es desestimado y desechado.\\

Con todo, Nietzsche está ensayando un manera alternativa de explicar
el acontecer en la naturaleza tal como la que había propuesto el
darwinismo, que entendía este acontecer como una evolución cuyo motor
es la lucha externa regida por la necesidad de adaptación al medio y
por el principio de la selección natural.\\
Nietzsche acepta las tesis de lucha del darwinismo pero añade que en
esa lucha entre las fuerzas que se confrontan no se produce según el
esquema causa-efecto, de la determinación del medio como causa.\\
Para Darwin, el ambiente externo y sus condiciones son los estímulos
que producen como efectos determinísticamente las respuestas de
adaptación de los seres vivos.\\
Nietzsche en cambio, el movimiento no parte del medio externo, sino
que parte de dentro de los seres vivos, que tienen constitutivamente
un poder interior de creación de formas, de órganos, de
funciones. Defiende un principio de autorregulación interior como
poder propio de los seres vivos, frente al mero adaptacionismo de los
darwinistas.\\

En esta perspectiva de la voluntad de poder y a su afecto de mandar le
es concomitante un sentimiento de placer o de displacer. El placer
sobreviene cuando se alcanza aquello a lo que la voluntad de poder
realmente tiende, o sea, el poder. Y que el dolor sobreviene cuando el
poder no se consigue o se pierde.\\
Así, este placer no es el placer provocado por el poder no por la
posesión del poder, sino el placer que sobreviene como consecuencia de
la percepción del aumento de poder y de la diferencia que eso marca
frente a las otras fuerzas —el placer es un síntoma del sentimiento
del poder alcanzado, un llegar a una consciencia de la diferencia; el
viviente no aspira al placer, sino que el placer aparece cuando el
viviente alcanza aquello a lo que aspira.\\
El placer en la voluntad de poder como lucha de fuerzas es el de la
victoria sobre otras fuerzas, victoria que hacer aumentar su propio
poder, mientas que el dolor es el dolor de la derrota y la percepción
de una disminución de la cantidad de poder.\\
Pero la principal dificultad de esta caracterización radica en tener
que admitir una explicación para las ciencias —física, química etc.—
donde no hay manera de considerar una voluntad de poder con
sensaciones de placer o de dolor, no con otros sentimientos
concomitantes al aumento o a la disminución de la fuerza. La respuesta
de N. consiste en proponer su hipótesis como un giro hacia una
interpretación del mundo de los fenómenos desde dentro de los sujetos
de conocimiento, en lugar de desde fuera como hace le mecanicismo, que
serviría para hacer avanzar el saber en una dirección a la que la
ciencia moderna se ha cerrado.\\

** La nueva concepción de ciencia
El conjunto de observaciones críticas con las que N. cuestiona la
ciencia moderna está en su nueva concepción de lo que es ciencia y de
lo que es un hombre de ciencia.\\
El *hombre de ciencia* no es sino un intérprete, un filósofo cuya
tarea principal consiste en descifrar los fenómenos naturales,
históricos o culturales con las claves que proporciona el texto del
cuerpo. Y esto según dos condiciones: puesto que el cuerpo interpreta,
la salud y la enfermedad deben ser consideradas como los determinantes
de la calidad y del valor de toda interpretación. La segunda condición
es que en el ejercicio de la práctica interpretativa es preciso
explicar cómo funciona y se aplica el criterio para diferenciar una
buena de una mala interpretación. Si en lugar de la verdad-falsedad
son la salud-enfermedad los nuevos determinantes del valor de toda
interpretación, es obvio que será distinta la actividad interpretativa
que brota de una voluntad de poder sana, activa. Por el contrario, la
que es producto de la mera negación, reactiva, en la medida en que la
conciencia no es mas que una instancia subordinada que ejecuta las
órdenes emitidas por los impulsos y que toda nuestra actividad
espiritual o culturas está determinada y dirigida por el dinamismo
propio de nuestras configuraciones instintuales.\\

Así pues, no hay conocimiento objetivo y desinteresado de leyes en sí
del mundo, o de esencias existentes en un mundo inteligible. Ni
tampoco valores en sí, sino juicios concretos de valor interiorizados
en virtud de ese proceso de incorporación en la que consiste la
socialización.\\
Si las teorías científicas, los valores morales de una sociedad o de
un individuo, no son otra cosa que la traducción de las necesidades
propias de un organismo como cuerpo que interpreta, esto determinará
una diferencia entre la expresión del tipo de exigencias fisiológicas
que brotan de un cuerpo como voluntad de poder, está exigiendo una
fisiología que no es ya la de la ciencia newtoniana. Conocer y juzgar
de forma genealógica es ahora considerar que el suelo de la vida
fundamenta y constituye el sentido y el valor de las opciones teóricas
espirituales o culturales.\\
La vida es susceptible de vivirse básicamente como salud o plenitud de
fuerzas y como decadencia, declive o debilitamiento de las fuerzas.\\
Por otra parte la segunda condición del arte de leer bien el cuerpo es
lo que N. llama la *honestidad filológica*, que implica una
transformación radical en la concepción de la verdad.\\
Verdad ya no se entiende como la explicación correcta y adecuada de un
texto en sí, sino como aquella clase de interpretación que cumple
determinados requisitos de honestidad.\\
Muchas de sus críticas a la ciencia y a la filosofía de la moral, son
debidas a malas lecturas o incluso denuncias por la tradición entera
de la cultura occidental.

* Voluntad de poder activa y decadencia
En la voluntad de poder, la noción de vida sana, no decadente no
enfermedad, es voluntad de poder activa que aspira a confrontarse con
dificultades y a superarlas. No rehuye las dificultades ni el dolor,
sino que los afronta y los quiere como el mejor medio de crecer de
fortalecerse y de convertirse en algo más.\\

El sentimiento de bienestar y de placer como ausencia de dolor y de
conflictos el que subyace a la concepción nietzschana de la salud,
sino la autoafirmación como predomino de las fuerzas activas sobre las
reactivas y como ejercicio de una voluntad de poder que aumenta
venciendo sufrimientos y resistencias.\\
Se deducen dos condiciones distintivas de la salud: (/i/) el poder de
afirmar la vida en su fluir caótico, imprevisible e incontrolable sin
temor a los aspectos dolorosos que pueda producirse y (/ii/) el poder
de armonizar las fuerzas más opuestas sometiendo su diversidad
conflictiva a una ley, a una unidad simple, lógica, categórica, a la
clásica del gran estilo.\\

Salud es ser lo bastante fuerte como para no retroceder ante el dolor
de la vida, sino aprovecharlo para llegar a hacerse aún más
fuerte. Salud es no dejarse descomponer por el caos pulsional de los
propios instintos, sino hacerse dueño del propio caos que se es y
construir, a partir de él, la armonía de un proyecto vital.\\
Para N. los griegos consiguieron ambas cosas, y de ahí el valor
modélico clásico de su cultura. Con su arte y su religión proyectaron
sobre el fondo cruel y terrible de la vida la apariencia multicolor de
sus dioses olímpicos apolíneos, y practicaron el orgiasmo musical
dionisíaco. La voluntad de lo trágico es la fuerza básica de la
autoafirmación como impulso de vida ascendente y como fuerza para la
que el dolor actúa como un estimulante. El arte clásico, arte de la
salud en el que lo pulsional, fuente de toda creación, es dominado por
una ley y sometido a una forma.\\

Frente a la imagen de salud, lo propio de la decadencia, como voluntad
de poder, es una disminución de la fuerza y, por tanto, el predominio
de un miedo al dolor en el que no se percibe ya su conexión con el
placer. La fuerza para acrecentarse y para producir el sentimiento de
un placer superior, tiene que esforzarse, tiene que sufrir venciendo
resistencias y obstáculos sin los cuales no se ejercita no puede
aumentar. Lo característico del decadente es no aceptar el dolor,
excluir el dolor del estado creador original. La disminución de la
fuerza, propio de la decadencia, tiene como consecuencia la
desaparición de las condiciones de la salud.\\
Por un lado da lugar a la negación de los aspectos terribles y
trágicos de la vida. Por otro se mueve en medio de un cierto caos
pulsional que no es autónomamente controlado ni sometido a ley.\\

En la /genealogía de la moral/ describe los rasgos de la decadencia en
tres ámbitos: la filosofía, la religión y la moral. Todos tres
presididos por los ideales ascéticos inspirados en el resentimiento y
la mala consciencia.\\
Las objeciones de N. a la cultura dominada por estos ideales pueden
resumirse diciendo que se ha complacido en la decadencia y se ha
identificado con ella.\\

El cristianismo, como columna vertebral de la cultura europea a lo
largo de los siglos, es para N. el paradigma genealógico-hermenéutico
opuesto al que ofrece la cultura griega. Ejemplificarían los dos polos
enfrentados que marcan esa diferencia interna a la voluntad de poder
que es el de la enfermedad y la salud.\\

El cristianismo y su moral son degeneración psico-fisiológica,
voluntad de poder reactiva, enfermedad y neurosis.\\
Si la salud —cuyo paradigma es la cultura griega— es capacidad de
someter a control el caos pulsional de los propios instintos, lo
propio de la decadencia es buscar en la cultura remedio a su
agotamiento, estimulantes o tranquilizantes.\\

Nietzsche ve en la moral cristiana toda una retórica teatral, un
constante exageración histérica animada por na intención de tiranizar
oculta.\\
En esto es lo que encuentra una similitud entre e cristianismo y las
ópera de Wagner. Los dos modelos ejemplares de lo que entiende por
decadencia.\\
La decadencia que equivale a descontrol de los instintos, da origen a
una sensación de miedo y de inseguridad por la incapacidad para
controlarlos. Entonces se impone la necesidad de tiranizar, que sería
la que habría presidido y determinado todo el proceso de culturización
occidental que no habría consistido esencialmente en otra cosa que en
un proceso de domesticación y desnaturalización del hombre.\\

Lo criticable de la decadencia como subsuelo de la cultura occidental
no sería la decadencia en sí, ni la enfermedad de la voluntad, que son
una faceta de la /physis/ y del cuerpo, lo mismo que la salud. Lo
criticable es que se la haya querido, el haberse complacido en ella y
haberla utilizado como resorte de una tiranía que ha convertido en
equivalentes culturización y desnaturalización.\\

Para que el hombre nihilista y enfermo recupere la salud, ha de llevar
a cabo una determinada recuperación de su mundo institucional y
pulsional. Pero este trasfondo no es el fundamento natural del hombre,
como su verdadera y originaria naturaleza.\\
Los instintos o son ningún principio originario, no son la cosa-en-sí
como fundamento de lo que el ser humano auténticamente es, de manera
que podamos hablar de una instintividad humana que debe ser liberada
como su verdadera naturaleza. Los instintos son la fuerza que se va
configurando y moldeando en función de la orientación que les imprime
la cultura, y en especial la moral.\\
Es aqeullo más importante del comportamiento, no porque sean innatos,
sino porque so lo que cubre el vacío de automatismo genético que
tienen los animales.\\
Los instintos, una vez configurados y consolidados, se convierten en
una segunda naturaleza, dirigen el comportamiento de una manera
espontánea anticipándose a cualquier intervención de la reflexión y de
la consciencia. Por eso es importante se moldeado o configuración, su
educación.\\

Si esto fuese así, se podría intentar un giro e iniciar un proceso de
reconfiguración de so instintos para que su energía resulta creativa y
produzca en los individuos la salud en vez de la enfermedad.


* El proceso civilizatorio europeo
En las obras del último Nietzsche /más allá del bien y del mal/, /la
genealogía de la moral/ y el /crepúsculo de los ídolos/, desatacan dos
temáticas relevantes. Por un lado, el relato de la historia de la
domesticación del hombre europeo en a que reconstruye los
procedimientos básicamente mnemotécnicos por los que un animal humano
se acaba convirtiendo en una persona socializada y civilizada a la
europea, crear un animal al que le sea lícito hacer promesas.\\
Por otro lado, la genealogía, el origen, la fuente de la
culpabilización y de la moral del resentimiento y de la
represión-olvido a la que esa metodología educadora da lugar.\\

Nitezsche expone como la culpa se gesta para conformar a un ser humano
capaz de responder de sí, de prometer, de recordar lo prometido y de
comprometerse con lo prometido. Para hacer de él un ser social
civilizado, consciente, responsable , que recuerda las leyes y las
cumple, en todo lo cual la memoria juega un importante papel.\\
La culpa es entendida como obligación personal de un deudor de modo
que la causa del dolor sea la responsabilidad.\\

El problema no es tanto el de la culpa misma y la responsabilidad como
origen de nuestra sociedad, cuanto el del origen de la culpa y la
inversión de los valores a los que la culpabilización conduce. Ese
origen, aquello que la genealogía busca y descubre, es el rechazo y el
olvido de determinadas posibilidades y exigencias dela vida, estimada
e impuestas por los promotores de esa metodología de la
culpabilización como impresentables.\\
El problema no es tanto como la culpa y la responsabilidad dan lugar a
un cierto tipo de orden legal y moral, sino cómo y por qué un tipo
específico de individuos crean una moral y una sociedad que se termina
generalizando e imponiendo sobre la base de un determinado
funcionamiento de la represión y el olvido, y que promueve el miedo y
el rechazo a las fuerzas de la vitalidad natural y de los impulsos del
cuerpo. El rechazo y el olvido reprimido de los estado corporales en
los que la vitalidad sobreabundante de una fuerza acrecentada y
sobrepotenciada se descarga dejando que se desborde su sobreabundancia
de poder. El miedo a estos estado es lo que lleva a los moralizadores
de la culpa y del resentimiento, al cristianismo, a revalorizar, a
ensalzar y a obligar a que se recuerden constantemente como moralmente
deseables y buenos loes estado opuestos, el debilitamiento, la
culpabilización, el desprecio y la negación de uno mismo, la
humanidad, etc.\\

En primer lugar se considera que sin la utilización del miedo, de la
intimidación y de la crueldad, del sufrimiento en vistas a imponer una
estandarización entre los individuos y una regularidad a sus acciones,
no se grabarían en lo más profundo de ellos las normas y los valores
de la civilización.\\
Sin el sufrimiento permanente no se fijan para toda la vida esos
valores, la distinción entre lo promedio y lo prohibido por la
sociedad, entre el bien y el mal.\\

Ser educado, civilizarse, hacerse humano y moral en la cultura
occidental ha sido el resultado de un ejercicio sobre los individuos
de la crueldad en virtud del cual han incorporado las reacciones
instintivas de inclinación hacia lo bueno, lo debido, y de rechazo
hacia lo malo, lo prohibido. Reacciones instintivas que se ponen en
funcionamiento al margen de la voluntad y del conocimiento
consciente. Se las ha creado así un estatuto moral que les hace
responsables, obligados a responder de sus comportamientos.\\
El castigo, el sufrimiento que se inflige al autor de una falta es el
modeo concreto de obligarle a que recupere la memoria de lo que se
debí y no se debía hacer.\\

El afecto de la crueldad caracteriza: (/i/) al proceso de aprendizaje
de la obediencia a la moral, (/ii/) al proceso de su transmisión y al
mantenimiento de su vigencia, (/iii/) al comportamiento moral mismo de
los individuos así moralizados.\\

En conclusión, el *europeo actual* es el resultado de una larga
evolución impulsada y dirigida por un entrenamiento civilizado
determinado, y de manera más específica moralizador, que la sociedad
ha impuesto a os individuos.\\
En todas las sociedades, el acceso a la cultura y la superación de la
animalidad consiste en dar forma al caos de los impulsos vitales del
individuo. Ninguna civilización humana es una pura continuidad con la
naturaleza.\\
La cultura, i.e. la reordenación de los dispositivos pulsionales de
los individuos y de sus instintos en función de una voluntad
coercitiva externa, es consustancial al individuo humano que vive en
sociedad.\\
Sin embargo hay distintas formas de hacer esto. Nietzsche acusa a la
moral europea de haber identificado la moralización con una mala
desnaturalización, en cuyo núcleo está la mala consciencia.\\
Los instintos que se descargaban hacia fuera se vuelven ahora hacia
dentro. El ser humano se sumerge en un proceso de interiorización en
el que empieza a sufrir de sí mismo.

Que la cultura y naturaleza sean cosas ditintas no quiere decir que
sean inconciliables. La moral occidental las ha contrapuesto
drásticamente con su prejuicio dualista metafísico, que separa de modo
radical naturaleza y espíritu, cuerpo y alma. Así ha concebido al ser
humano como sólo espíritu, alma y razón, y en modo alguno como un ser
natural. Al haberse obligado a desnaturalizarse, se ha hecho de los
individuos seres sin arraigo, sin la regulación espontánea y natural
de instintos sanos y, en consecuencia, seres desorientados,
angustiados y dominados por el deseo de dejar de ser para fundirse y
desaparecer en el rebaño.\\

Por otro lado, los fenómenos morales son remitidos a su origen en los
sentimientos morales. Estos a su vez, son entendidos como la expresión
dela actividad valorativa y axiológica (:teoría de valores) básica de
la voluntad de poder.\\
El bien de una moral determinada expresaría aquellas condiciones de
vida que los hombres que profesan esa moral estiman adecuadas y
necesarias para su supervivencia y crecimiento, mientras que el mal
designaría aquello que debe ser evitado y excluido. Por tanto, sería
la expresión de un sentimiento de impotencia.\\

El ser humano es esencialmente un animal que evalúa, que percibe y
valora, en el nivel básico y elemental de su actividad
fisiopsicológica, qué es lo que puede asimilar y dominar para
sobrevivir y crecer, que qué es lo que puede ser para él una amenaza,
un daño y un peligro.\\

El sentimiento del miedo, pues, no es un instinto en sí, sipo que es
fruto de la percepción o evaluación de un peligro, de un posible daño
para la supervivencia, para el crecimiento y la expansión del propio
ser. A esta actividad básica de evaluación fisiopsicológica la llama
voluntad de poder, i.e., voluntad de sobrevivir y de aumentar la
propia potencia y fuerza de ser.\\
Así, en la lucha de esta voluntad de poder por acrecentar su potencia
de ser, el miedo es el sentimiento que procede de la percepción de una
fuerza evaluada como superior a la propia y, por tanto, como una
amenaza potencial susceptible de vencer y frustrar el impuslo de vida
y de poder.\\

La moral es una interpretación de la realidad engendrada por un ser
viviente, por una cierta configuración de impulsos que, poniendo
valores, expresa sus condiciones de vida que permiten asegurar el
acrecentamiento de su poder.\\
Para determinar la relación entre impulsos y valores hay que fijarse
en esa condición de los impulsos o instintos de ser productores,
creadores de valoraciones e interpretaciones. Es de aquí de donde
N. deriva la crítica a la moral y sus posiciones alternativas: Cuando
hablamos de valores lo hacemos bajo la inspiración, bajo la óptica de
la vida misma. La vida misma nos obliga a poner valores, valora a
través de nosotros cuando ponemos valores. Así, aquella
contranaturaleza en cuanto moral que entiende a Dios como
contraconcepto y como condena de la vida, no es más que un juicio de
valor de la vida. De una vida descendente, debilitada, cansada,
condenada.\\

Los valores no son esencias inmutables y suprasensibles, no hay una
objetividad inteligible de los valores en sí, como existentes en un
mundo metafísico.\\
Lo que hay son valoraciones /in situ/, estimaciones de valor en cuanto
producción de estas valoraciones, procesualidad continua de esta
actividad. La única realidad de los valores es el ejercicio mismo de
la valoración, el proceso de apreciación interpretativa propia de un
ser vivo en su actividad constante de dar forma a su universo a partir
de preferencias que brotan de su sistema pulsional.

En suma, lo pulsional es genealógicamente originaria porque es
evaluante. Es actividad, no pasividad entendida como simple reacción
al medio (Darwin). La pulsionalidad es espontaneidad que juzga,
aprecia, estima prefiere y distingue, y no simplemente
reacciona. Estas preferencias y rechazos pulsionales son mucho más
profundos y determinantes que los juicios morales conscientes y
reflexivos.

* Moral de los señores y moral de los esclavos
En /la geneología de la moral/ esboza la historia de la moral europea
como genealogía que sa han constituido los dispositivos pulsionales
que rigen los sentimientos morales. En esta historia ve dos procesos
de fijación de valores distintos y en lucha continua, que dan lugar a
dos tipos diferentes de moral.\\
Uno de estos procesos se establece como valor prioritario el valor
/bueno/, mientras que el valor /malo/ queda como secundario o
accesorio. En el otro proceso, la prioridad la tiene el valor /malo/.\\

La primera de esta morales la llama *moral de los señores*, propia de
las antiguas aristocracias y de la nobleza como clase social. El valor
bueno tiene un sentido de apto, de bien dotado naturalmente, de
fuerte. Es decir, /bueno/ no tiene en esta valoración un significado
ni moral ni moralizante propiamente.\\
El valor /malo/ designa al hombre no apto, no capacitado, ordinario y
común, hombre vulgar, que no es fuerte, ni excelente, que no ha
desarrollado una inteligencia i una sensibilidad no una excelencia
destacadas. Tiene connotaciones que lo vuelven objeto de cierto
desprecio por parte de los nobles que, por su disciplina de vida,
están por encima, y por eso son nobles y ricos.\\

La característica básica del individuo aristocrático es el pathos de
la distancia respecto de la masa de los individuos vulgares. No hay un
sentimiento de hostilidad sino sólo de diferencia.\\
Este pathos de la distancia es la expresión de una apreciación básica
de la voluntad de poder es el que establece espontáneamente la
jerarquía en cuanto diferencia fundamental entre buenos y malos. El
valor bueno surge en esta moral a partir de esta espontaneidad de la
voluntad de poder ascendente y activa.\\

La *moral de los esclavos* tiene otra historia y su tabla de valores
no se establece espontáneamente. Se construye progresivamente a partir
de la confrontación entre una nobleza en guerra activa y los grupos a
los que se opone imponiéndoles su denominación.\\
Por ejemplo, los grupos religiosos cristianos formados por esclavos ,
en los que la impotencia generó el odio y el deseo de venganza.\\
La interiorización de éste odio y de esta impotencia se habría
cristalizado como resentimiento de l que habría nacido la moral
ascética, con la que se ha llevado a cabo durante siglos una auténtica
guerra de aniquilación contra la moral de los señores.\\
La debilidad de los resentidos se convirtió en astucia, encontrando el
modo de vencer a los señores mediante la inversión de valores
aristocráticos.\\
Según N. el cristianismo se limitó a implementar, generalizándola, la
formula crada por los judíos durante su cautividad en Babilonia y
Egipto.\\

Así, lo que diferencia a estos dos tipos de moral es su origen o
precedencia a partir de configuraciones pulsionales distintas que a lo
largo de la historia y en condiciones de civilización y de sociedad
diferentes, han dado lugar a cristalizaciones de valores y de
sentimientos morales contrapuestos.\\
No es su verdad o falsedad, ni su bondad o maldad lo que
originariamente las distingue. No es que la moral de los señores sea
la buena y la veradera, y la moral de los esclavos la mala y la falsa,
sino que lo las separa es un criterio distinto: el de la salud y la
enfermedad y el de su capacidad de promover el crecimiento y
potenciación de la vida del individuo, o por el contrario, su
disminución y debilitamiento.\\

Para N. el conflicto pulsional básico, propio de la vida humana, es el
de la lucha entre un impulso a elevarse, diferenciarse, a adquirir una
forma y una individualidad —lo apolíneo—, frente al impulso que empuja
la fusión con los otros, a la disolución de uno mismo en el todo
identificándose con la totalidad indiferenciada y quedando absorbida
por ella —lo dionisíaco.\\
De la diferencia de estos dos impulsos se deriva que es la vida misma
la que hace que el individuo tienda a la autoafirmación, a la
autonomía, y que incorpore de este modo la elección, el límite, la
renuncia, la prohibición y la responsabilidad emergiendo de su
indiferenciación, de su ignorancia y de su minorías de edad.\\

Sería pues, la vida misma la que tiene ya de manera connatural, en su
dinamismo, un amoral de la autosuperación que es sustancialmente una
moral del equilibrio, de la autolimitación, de la autodisciplina y el
autocontrol.\\


Se podría pensar que lo lógico habría sido que el hombre europeo
hubiera desarrollado esta moral que brota de la vida y que funciona en
armonía con ella.\\
Lo que parece haber sucedido es que la moral europea se ha erigido y
ha funcionado como instancia directamente opuesta de la vida. De ahí
la duaidad de morales: Por un lado, una moral que es propia de la
vida, que la realiza y la potencia —de los señores—, y otra que va
contra la vida, que la niega y la intenta suplantar —la de los
esclavos.\\

El contraste y la lucha entre ellas sería irreductible y sin
solución. Dos morales, una conforme a la vida porque brota de ella y
otra opuesta y contraria a la vida porque no la acepta, la considera
inmoral, se esfuerza en una lucha para que la vida se adapte y se
ajuste a un ideal abstracto y metafísico que la corrija de su
injusticia y su inmoralidad.\\

El objeto principal de esta moral europea y occidental habría sido el
de limitar a los individuos en sus acciones prohibiéndoles una serie
de cosas y haciendo prevalecer reglas uniformadoras según un código de
conducta universal qeu trata de determinar, no sólo las acciones
concretas en su dimensión externa, sino inclusa también las
intenciones íntimas y los motivos psicológicos de la acción. El
*hombre moral* sería el que obedece escrupulosamente esas reglas
absolutas.\\
Se ha ignorado que todos los /tu debes/ son obra de hombres
individuales. Se ha querido tener un Dios moral para sustraerse a la
tarea que exige del hombre el creas. Detrás de la pensar
cristiano-católico se esconden la debilidad o la pereza.\\

Por el contrario, la actitud del *hombre libre* sería la de construir
sus propios valores porque él no acepta ser exonerado de esta
responsabilidad.\\
Un ser humano fuerte, de elevada formación, que se contiene a sí
mismo, que es bastante fuerte para esta libertad. El ser humano de la
tolerancia, no por debilidad sino por fuerza, porque aquello en que
perecería una naturaleza mediana, él sabe utilizarlo incluso para su
provecho. El ser humano para el que no hay nada prohibido excepto la
debilidad.\\

La *dualidad de morales* mantendría la confrontación entre una moral
dogmática —que busca y genera la gregarización como la mejor manera de
gobernar al rebaño—, frente la hipótesis de una ética de la
singularidad —dispuesta a aceptar el riesgo que se seguiría de admitir
capacidadees de acción nuevas e innovadoras que hacen crecer y
fortalecer a los individuos en lugar de disminuirlos.\\

En esta *nueva moral*, la *virtud* sería a a fuerza como invención de
uno mismo, en contraposición a la no-voluntad de los esclavos que
obedecen al orden establecido en actitud propia de un rebaño.\\
Esculpirse a sí mismo con un juicio de gusto sobre el estilo a dar al
propio carácter. Ésta sería la ética que se funda en la experiencia de
un autodomino por oposición a una moral de lo universal qeu atribuye a
cada uno la capacidad de actual moralmente en función de una ley
determinada.\\

En suma, la moral occidental sería el resultado de la confrontación a
lo largo de los siglos de estos dos tipos de moral, que expresan modos
de evaluación opuestos. De la evolución en cada uno de ellos y su
relación de constante lucha nace la forma relativamente estable de la
actual *moral europea y occidental*. Habría en el trasfondo de esta
moral una diferencia afectiva irreconciliable que está en la fuente de
las respectivas tablas de valores de las dos morales de las que ha
nacido esa diferencia reconducible a los dos modos de evaluación vital
básicos de la voluntad de poder, como de poder activa y como voluntad
de poder reactiva.

* El Wagner imposible de nietzsche

** La estética como política
Nietzsche ve en las obras de Wagner plasmar la moral shopenhaueriana
de la compasión y de la negación del querer vivir. Según N. esta
dependencia de la filosofía pesimista de Schopenhauer fue la que
condujo a W. al cristianismo.\\

Pero también se detecta un resentimiento personal de N. hacia W.,
probablemente relacionado con algún episodio personal.\\

Nietzsche describe a W. como el /advenimiento del comediante en la/
/música/. Esto representa el motivo esencial de una gran decepción
respecto a las expectativas que la propuesto estético-cultural de
W. había despertado en N. durante su juventud.\\

Uno de los motivos de la relación de tensión entre ambos, fue la idea
que heredó N. del romanticismo de que el arte, o ciertas formas de
arte, podrían volver a cumplir en la época contemporánea la función
educadora que consiguieron cumplir en la Grecia antigua.\\

Wagner presentaba su música como materialización de esta pretensión
del romanticismo: Quería hacer de su música el nuevo gran arte
romántico como nueva religión estética para los tiempos modernos.\\
Nietzsche creyó primero que el drama musical de W. podría cumplir este
objetivo, pero pronto se dio cuenta que lo que la música de
W. representaba era una desfiguración y una falsificación de ese
hermoso ideal romántico de reactiva en nuestra época la fuerza
ennoblecedora del arte griego.\\

El proyecto wagneriano era convertir la ópera en un arte de masas
mediante la técnica orquestral y teatral. Esto no era ajeno a una
intención estético-política, como la que tuvo en la Antigüedad la
tragedia griega.\\

Se debía empezar para transformar el concepto mismo de ópera moderna,
rompiendo con la visión de subordinación de la música a la poesía en
la misma ópera. Wagner redefinió su ópera como la representación
sensible de un contenido espiritual, en lugar de una dramatización de
las pasiones. La poesía se resuelve en el mito, destinado a fundirse
con la música en el drama musical.\\

Wagner aceptaba la comprensión que los griega tenían del mito como
materia ideal del poeta. Pero le dio su propio sesgo, afirmando que el
mito es siempre el poema primitivo y anónimo de un pueblo, retomado
por todas las épocas y poetas posteriores, al mostrar lo que la vida
tiene de verdaderamente humano, de eternamente comprensible, y lo que
muestra bajo esta forma concreta. Es decir, la mitología de las sagas
germánicas era el poema anónimo de un pueblo concreto, el germánico,
que podía presentarse como expresión de lo humano extensible y
generalizable al resto de los demás pueblos.\\
En este sentido, la poesía del futuro habría que ser el mito en cuanto
creador de identidad colectiva y de comunidad. Y este mito es lo que
había que transmitir en la música.\\

Wagner decía que lo que aseguraba su drama musical el poder político
de cohesionar la sociedad y superar la fragmentación y el aislamiento
de los individuos —como la gran enfermedad de la época moderna— era su
virtud figurativa, el poder de representar figuras de tal manera que
produjeran un determinado tipo de efecto en los participantes.\\
Pretendía representar en su óperas eran las grandes figuras míticas
con las que el pueblo alemán reunido podría identificarse.\\
Así pues son necesarias figuras míticas, extraídas del patrimonio
mitológico de la tradición, para la organización de una
comunidad. Pero la religión cristiana ya no crea la solidaridad de la
comunidad, le correspondía al arte reencontrar su antiguo destino y
erigir las figuras míticas en las que la humanidad pudiera reconocerse
en su esencia constitutiva.\\


Nietzsche le replica a Wagner de degradar y desfigurar el original
proyecto romántico de una rehabilitación en el presente de la tragedia
griega. La ópera de W. no podía ser el momento de una conexión
artística dionisíaca construido sobre las leyendas y mitos germánicos,
i.e. nacionalista. Con esto, Wagner contradecía el propósito del
primer romanticismo, que proclamaba la idea de un arte conciliador
para hacer posible acceder a un nivel de comunidad en la que se
desvanecieran las divisiones entre los pueblos.\\
A esto es a lo que se había adherido N. en su juventud.\\
Pero Wagner perseguía el sueño de un gran arte alemán capaz de definir
el ser alemán, y distinguirlo bien frente a lo extraño y espurio,
representado por todo lo procedente del ámbito semita y latino.\\
Wagner aprovechaba la unificación alemana llevado a cabo por Bismark
para construir la nueva identidad alemana sobre un pueblo-sujeto.\\

Nietzsche, con una comprensión cada vez más madura y original de la
cultura griega se contrastaba cada vez más con las tesis del
wagnerianismo. Lo propio de la cultura griega fue, para N., subrayar,
en el fenómeno dionisíaco, no el movimiento de la disolución de lo
apolíneo en lo dionisíaco, sino, de forma más positiva y afirmativa,
el otro movimiento el que va de lo dionisíaco a lo apolíneo, el
movimiento de la creatividad y de la formación de cultura a partir del
caos de los impulsos informes y desmesurados.\\
La superioridad de los griegos es esa actitud afirmativa de la visa
que les llevó a dominar el pesimismo regresivo de la disolución
dionisíaca del mundo mediante la creación de formas y leyes con las
que poner en orden en el caos y hacer posible y deseable vivir.\\
Desde esta perspectiva, el romanticismo de Wagner no podía aparecer
como otra cosa que como una desvalorización nihilista de la cultura y
de sus creaciones, una ansia enfermiza por disolverse en lo dionisíaco
sentida esta disolución como liberación, pero que, desde la
perspectiva de la cultura griega apolínea, no es más que la desmesura
bárbara, pre- o anti-griega.\\

Lo substancial de la decepción que N. sufrió respecto del proyecto
estético de W. tenía qeu ver directamente con la dirección más propia
de su pensamiento: la liberación que debe ser buscada a través del
arte no es la experiencia dionisíaca del anonadamiento de la
individualidad como regreso de nuestro yo al todo cósmico o
social. Esto no es más que la huda del mundo, nihilismo, desprecio y
negación de la vida. Lo tiene que hacer el hombre que ama y afirma la
vida es conquistarse a cada instante dominando su caos, dando un
sentido a su vida e imponiendo una ley, un orden, un ritmo a su
temporalidad unificándola en una estructura articulada. Si no hace
esto se verá aplastado por el caos de las impresiones y de las
determinaciones cambiantes e imprevisibles que se mueven en todas las
direcciones. Crear es ordenar el caos constitutivo de la existencia,
darle una ley, un orden que va más allá del momento presente y
organiza el futuro alrededor de una meta, dando sentido a nuestro
futuro y pasado.\\
La música afirmativa, la que favorece la vida ascendente y nos ayuda a
superar el nihilismo no puede ser la que nos sumerge y diluye en lo
dionisíaco aniquilador, que es lo que pretende la música de W., sino
la que nos enseña el modo de escapar de él.\\

** Drama muscial y metafísica idealista
Para W. su objeto no era propiamente ala música, sino el drama,
respecto del cual la música es sólo un medio, el medio para expresar y
hacer sentir el mundo de la representación dramática.\\

El sentido del drama es el de definir el proceso finito, temporalmente
definible, a través del cual se produce efectivamente la posible
síntesis entre música y sentimiento, entre lenguaje y mundo, entre
lenguaje y realidad.\\

Esto se basa en una mala interpretación de W. del pensamiento de
Schopenhauer, quien este último decía que la música era la más elevada
forma artística porque revela la esencia del mundo de manera
inmediata. Wagner lo interpretó como posibilidad de una síntesis
perfecta entre sentimiento y el sonido, entre el lenguaje y
realidad. Pero para Schopenhauer, la voluntad del mundo es
incognoscible como cosa en sí, lo que implica que las representaciones
se comprendan como anonadantes, como aniquilantes.\\

Así, el problema de W. no es el del reconocimiento de la
insustancialidad y del vacío de toda apariencia, sino que al
contrario, su problema es el de la creación del drama, para él la
música tiene el valor de una forma representativo-expresiva capaz de
realizarse en perfecta coherencia con un significado.\\
Es decir, necesariamente W. tiene que dar por supuesto en la búsqueda
de la síntesis que el significado se convierte en Idea, y que la
representación de esa Idea reviste el carácter de un deber-ser. El
valor del drama es el de la representación, y su lenguaje es un
lenguaje que vale para describir el espíritu.\\


Para Schopenhauer, aquello distinto en la música frente a las demás
artes radica precisamente en su alejamiento de esta función de
representar ideas. Esta liberación de la música de la obligación de
representar fenómenos o ideas es la que le hace inservible desde el
punto de vista utilitario. La música no sirve para comunicar ideas, no
tiene valor para la vida práctica. No contribuye a alimentar el
querer vivir de la voluntad del mundo. Más bien lo niega.\\

Para resumir, en Schopenhauer, la música es negación del mundo como
voluntad de vivir, simple forma artística que no aporta, que no
capitaliza ningún significado.\\
Wagner en cambio, lo que pretende es hacer del drama musical el
lenguaje que vale para describir la realidad.\\
Por esto, para Nietzsche, el proyecto de Wagner es un fracaso
absoluto.\\

En los tiempos en N. rompió con W. había logrado alcanzar sus dos
posiciones filosóficas que iban a determinar su pensamiento de
madurez. Por un lado, la comprensión de la cultura griega que había
logrado desprenderse del romanticismo presente en las obras de su
juventud. En contraste con e romanticismo y su impulso regresivo, la
cultura griega se le aparecía como la búsqueda de la mesura y el
triunfo afirmativo del dominio de la voluntad sobre el caos del
mundo.\\
Desde esta perspectiva, el romanticismo de W. no podría aparacérsele
como otra cosa que como una lucha abierta contra la cultura sin más y
contra sus creaciones.\\

El segundo logro precipitó su conflicto con W., fue que empezaba a
convencerse del carácter puramente convencional y retórico de todo
lenguaje. Esto le movió a una crítica antimetafísica contra todas las
tesis que defendían la necesidad del vínculo semántico entre lenguaje
y ser, y plantear el valor del lenguaje únicamente en función de su
eficacia para la vida.\\

Por todo esto, la dialéctica wagneriana entre lenguaje musical y
esencia del mundo chocaba fuertemente con sus proyectos e ideas. Si
nada garantiza la identidad de música y mundo, la música de W., que
pretende ser presentarse como símbolo metafísico de la esencia del
ser, no es más que la falsedad e impostura. La música de W. no es más
que búsqueda de consuelo, síntoma de debilidad, puro efectismo teatral
e histérico, nihilismo, decadencia y negación de la vida.\\
Si lo que hace posible la vida del hombre y la desarrolla es
introducir la regularidad y la unidad en el caos, entonces lo que
expresa la música de W. es la tendencia opuesta. Al querer reflejar
musicalmente el fondo dionisíaco del mundo, esta música tiene una
estructura análoga al estado originario de indeterminación previo al
esfuerzo del hombre por identificar y determinar perceptivamente los
objetos.\\

NIetzsche modifica en su madurez el juicio de valor que sobre la
música de W. tenía en su juventud. Lo que se muestra tras el fracaso
de W. es que no existe ninguna esencia oculta en el significar de la
música, ni la relación originaria entre signo y significado, ni
lenguaje como representación metafísica de un sentimiento o de un
mundo.\\
Todo indicio de expresar más que sí misma, toda posible connotación
metalingüística, todo afán de querer decir sus propios fundamentos
metafísicos, subjetivos o utópicos, tiene que ser rechazado.\\
Esta es la gran miseria y grandeza trágicas de la música absoluta. Que
su escritura ya no es escritura de ninguna nueva síntesis, sino
aceptación de una separación, de una desvinculación completa respecto
de cualquier originario, como cualquier otra forma o fenómeno del
mundo, pura apariencia.


* El hombre nuevo
** La imagen de la gran salud
La idea del Übermensch aparece en los escritos de 1882, poco antes de
la composición del /Así habló Zaratustra/, en la que se convierte en
un tema central.\\
Para Nietzsche el Übermensch es una evolución del último hombre, pero
no en sentido darwinista, sino desde una perspectiva de la vida como
creatividad. La vida es voluntad de poder activa en cada centro de
fuerza, de modo que el verdadero progreso en el sentido de la
autosuperación sólo se cumple individualmente.\\

De ahí que esté presente a lo largo de su obra la noción de la
formación de fuertes personalidades individuales. Sostiene que las
virtudes de los individuos sea aquello característico de él y no algo
extraño, una piel, un manto, ya que es la verdad de fondo del alma.\\

Primero genio, luego espíritu libre y, ahora, Übermensch, en el que se
proyecta el valor de grandeza y el /pathos/ de la distancia que hace
nacer, en el interior del alma una distancia aún mayor que la
puramente social.\\
El Übermensch es una figura hipotética, un modo alternativo de
existencia más-allá o después del nihilismo.\\
El anuncio del übermensch va unido a la predicación del eterno retorno
porque, para aceptar la inmanencia total del mundo tras la muerte de
Dios, el hombre necesita elevarse por encima de sí, tiene que
desaparecer a din de que nazca el Übermensch. Sólo un ser más allá del
hombre será capaz de afirmar la vida que retorna eternamente.\\

Lo que distingue, en último término, al moderno europeo nihilista
—como individuo enfermo y decadente— del Übermensch —como hipótesis de
una existencia que ha superado ya esa enfermedad—, es que el
übermensch es exponente del la *gran salud* del cuerpo. Es el hombre
redento, el espíritu creador, de gran amor que su fuerza impulsiva
mantiene alejado de cualquier más allá o más acá, cuya soledad el
pueblo interpreta como si fuera una huida de la realidad, cundo no es
sino un sumergirse, un engolfarse , un ahondar en la realidad, para
traer la redención de dicha realidad, su redención respecto de la
maldición que el ideal habido hasta ahora ha echado sobre ella.\\


Nietzsche, también identifica la *gran salud* con las grandes obras
del arte clásico. La mesura de las formas apolíneas propias del gran
estilo no es jamás la negación de la sensibilidad, sino la victoria de
un poder que conserva la vitalidad de los sentidos y sabe producir con
ella bellas armonías, formas, ritmos, etc. Este modo de crear es el
contrapunto crítico del ascetismo platónico-cristiano-schopenhaueriano
del hombre decadente y, por ello, adopta la imagen de un modo de ser
en la que la voluptuosidad y la sensualidad no se reprimen, sino que
se dominan y se presentan de una forma sublimada, exaltada.\\

Lo que diferencia el Übermensch del individuo decadente y nihilista es
que, en ves de eliminar los sensible, las pasiones, lo instintivo,
etc., apuesta por un reforzamiento y mutuo potenciamiento de la unidad
indisoluble en él de lo sensible y lo inteligible, de lo natural y lo
cultural. Ese es el Übermensh como hombre renaturalizado, que ha
vuelto a encarnar en sí mismo ese texto primordial del *homonatura*.\\

Sostiene N. que pensar el ser humano fuera ya de las ideas metafísicas
significa pensarlo como una unidad natural en vez de como una dualidad
cuerpo-alma, materia-espíritu o razón-sensibilidad. El espíritu, el
alma, la razón, el yo, la conciencia, no son cosas separadas del
cuerpo, sino aspectos del ser humano concebido como un todo organizado
de la misma naturaleza de la que está constituido del universo.\\
Esta idea reformula y transforma en un sentido original, el
pensamiento de Schopenhauer de que la vida, en cuanto voluntad
inconsciente y sin finalidad, tiene en la conciencia y en el mundo de
la repreentación su expresión más superficial.  De modo que la
conciencia o el espíritu, no sólo no están separados del cuerpo y de
los impulsos inconscientes como si formasen dos mundos distintos, como
ha sostenido el dualismo metafísico, sino que son la manifestación de
fuerzas cuya lógica y cuyo funcionamiento pertenecen a una especie de
razón-superior que es la que gobierna al cuerpo, a la que N. llama,
para distinguirlo del yo-consciente, el-sí-mismo.\\

Los impulsos o instintos son condiciones básicas de la dinámica de los
seres vivo orgánicos, respecto de los cuales la consciencia no es más
que una estructura secundaria, un subproducto que no deja de depender
nunca de esas otras fuerzas instintivas qeu son las qeu realmente
deciden.\\

A partir de estas premisas, N. extrae una importante conclusión. Lo
que ha caracterizado a la cultura europea y occidental, y en concreto
a su moral, es que se ha interferido entre la vida y el instinto
interponiendo entre ellos unos ideales que niegan la vida. Por eso
propone una transvaloración o inversión moral —propio del übermensch—,
como hipótesis de una situación, no de la negación y el desprecio de
la vida, sino de su afirmación, de su aceptación u de su aprobación.\\

Afirmar la vida es mandarse a sí mismo, encontrar en uno su propia ley
y no tener más ley que la necesidad de autosuperación interna a la
propia voluntad de poder. \\
Lo que significaría la muerte de Dios y el advenimiento del nihilismo
es que no hay ya ningún valor absoluto que pueda seguir imponiéndose a
la voluntad individual, ni apelando a lo trascendente ni tampoco a lo
trascendental (Kant). La libertad que simboliza el Übermensch no es
autonomía de la moral trascendental en una sociedad normativizada de
individuos libres, sino el ejercicio de la voluntad fuerte y
afirmativa que encuentro sólo en sí misma su motivación y su ley.\\

Nietzsche opone pues, a la cristiana y kantiana moral como
contranaturaleza la idea de una *ética de la singularidad* que gira en
trono al concepto de *construcción de sí mismo* y de gusto por la
escelencia y la distinción.\\
Las virtudes de esta ética están hechas para soportar la afirmación
dichosa del carácter cambiante y perspectivista de la vida. No son
virtudes en razón de su mayor universalidad o verdad, sino porque
valen para preservar al individuo en sus máximas del amor inteligente
a uno mismo y a los demás por sobreabundancia y riqueza internas.\\

Esta ética de la singularidad parte de una apuesta por el carácter
estética de los valores morales y por la naturaleza artística de la
acción moral. Reducción moral a la estética.\\

El valor no remita a la representación de juicios estables sobre lo
bueno y lo malo, sino a creencias que hemos incorporado
individualmente en el curso de una práctica de aprendizaje y de
socialización.\\

Los valores no son bienes ideales absolutos suprasensibles que la
razón capta e impone frente a los instintos. Son las pulsiones
actuando valorativa y procesualmente. En este proceso, juegan un papel
importante los afectos o sentimientos. Las valoraciones tiene su
fuente inmediata en los afectos o sentimientos, y éstos, a su vez,
brotan de los impulsos infraconscientes que constituyen el sistema
pulsionas de cada individuo.\\
Los sentimientos tienen un importante papel mediador, la pulsión o el
instinto se insinúa siempre como el sentimiento de algo bueno o de
algo malo. Todo instinto, pues, es la traducción de preferencias al
nivel más elemental entre lo beneficioso y lo perjudicial, entre lo
agradable y lo desagradable. La relación entre la pulsión y los
valores empueza con un sentimiento de esto-me-gusta o
esto-no-me-gusta, prefiero-esto o me-repugna-aquello, de modo que el
ejercicio de la valoración va siempre acompañado de sentimientos que
son su inmediata dimensión motriz.
