#+LATEX_CLASS: article

# -*- mode: org; -*-
#+LATEX_CLASS_OPTIONS: [a4paper, 10pt, twocolumn, spanish]
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[margin=.75in]{geometry}
#+LATEX_HEADER: \setlength\parindent{0pt}

#+Title: Apuntes de Teoría del Conocimiento ii
#+SUBTITLE: Sobre Nietzsche y su pensamiento tardío
#+AUTHOR: Jordi Serra

* Introducción
En su última etapa intelectual, que se verá truncada por el colapso
menta que sufre en 1889, Nietzsche hace un ejercicio de autocrítica y
autointerpretación de su trayectoria anterior que culmina con su
última obra /Ecce homo/, una autobiografía intelectual. También
trabajó en la preparación de una gran obra que debería sintentizar
todo su pensamiento y llevaría el título de /la voluntad de poder:/
/ransvaloración de todos los valores/. Este proyecto fue abandonado
quedando sus materiales que no fueron incorporados en las obras en
elaboración forman parte de su importantísimo legado póstumo.\\

En este período reaparecen tamáticas propias de los escritos
anteriores junto con novedades importantísimas. Aparecen los grandes
temas de voluntad de poder, el eterno retorno, el nihilismo, la muerte
de Dios, la transvaloración o el übermensch —el hombre del más
allá. Estos temas se presentan de una poético-alegórico en el /Así/
/habló Zaratustra/ o bien de manera más o menos conceptualmente
argumentadas en el resto de sus obras de éste periodo.\\

/Así habló Zaratustra/ empieza donde concluía el recorrido que habían
llevado a cabo las obras precedentes, cuya aportación fundamental
había sido la comprensión de las estructuras metafísicas y de Dios
como su fundamento como un invención —cómo el mundo verdadero acabó
convirtiéndose en una fábula.\\

Con ello la apariencia fenoménica del mundo quedaba rehabilitada y
liberada de su descrédito y del desprecio que caía sobre ella durante
la vigencia del dualismo metafísico.\\

A la idea del eterno retorno se le atribuye un sentido de un destino
cargado de consecuencia para la historia de Europa. De esta idea parte
prácticamente todo el desarrollo de su último pensamiento, que se
centra en el programa de una transvaloración de todos los
valores. Esto implica todo un nuevo modo de concebir el valor de la
filosofía y la figura y la misión del filósofo, que representa una
transformación sustantiva respecto a lo que ofrecen las obras
crítico-genealógicas anteriores.  La primera gran novedad es la
convicción de que es posible partir de la crítica moderna a la cultura
occidental para provocar una mutación readical de la civilización
occidental.\\
Las obras críticas anteriores ponían de manifiesto que las creencias
metafísicas, religiosas y morales del pasado habían ido perdiendo su
carácter de solución teórica y por tanto su utilidad práctica como
supraestructura de ideas al servicio de la organización de vida.\\

*Dios ha muerto*. Esta liquidación del mundo verdadero suscita una
actitud de *libertad de espíritu* ante los errores sobre los que se
fundamente necesariamente la vida, sobre las invenciones y
*construcciones morales*, religiosas e ideológicas que han sido
necesarias para vivir y organizar la sociedad.\\

Estas obras crítico-genealógicas expresan la actitud de quien se asoma
un momento por encima de todo proceso histórico y contempla como un
espectáculo las equivocaciones que han hecho profundo, rico y matizado
nuestro mundo. Nietzsche atribuye ahora a su pensamiento una
intencionalidad práctica, una pretensión de servir como impulsor de
una transformación de la época moderna en el sentido de una superación
de su nihilismo.\\

Nietzsche piensa ahora en el filósofo como un legislador, un creador
de valores con los que fundar una nueva época y una nueva historia. Es
preciso legislar con vistas a una nueva humanidad. El filósofo se
diferencia pues del trabajador filosófico y de los científicos en que
el filósofo se le exige, le es necesario que cree valores, y no sólo
usar aquellos antiguos patrones de valores fijados y que se usan de
una manera mecánica. El autentico filósofo es el que manda y
legisla. Ellos dicen deciden como deben ser las cosas, determinan el
primero el /hacia donde/ y el /para qué/ del hombre, y para ello
disponen del trabajo previo de todos los trabajadores filosóficos, de
todos los subyugadores del pasado. Su conocer es cread, su creas es
una legislación, su voluntad es *voluntad de poder*.\\

Desde esta perspectiva se entiende su radicalización de su crítica al
cristianismo, tal como la desarrolla en el /Anticristo/. Nietzsche se
confronta con el mundo de ideas e instituciones que más universalmente
ha configurado la historia europea y con la ideología más directamente
responsable del nihilismo.\\

El *nihilismo* lo comprende como nuestra situación contemporánea de
olvido o de pérdida del valor de los antiguos valores supremos que
sostenían la cosmovisión cristiana del mundo. No obstante, el
nihilismo es también un proceso activo, y no sólo pasivo, en virtud
del cual se ha producido la muerte de Dios.\\

Es decir, la *muerte de Dios* no ha consistido en ninguna práctica
voluntarista del ateísmo militante no en el ejercicio destructivo
propiamente dicho del tipo de crítica teórica que el propio N. había
desarrollado hasta ahora. Es el desenlace o el punto final de un
proceso al término del cual ha venido a hacerse luz, o a recordarse
algo que se encontraba ya en germen en el propio planteamiento
original con el que nació.\\
El nihilismo no es otra cosa que ese trabajo mismo de
desenmascaramiento-rememoración de los valores supremos y de Dios como
su fundamento que la historia ha realizado, deslegitimándolos a la
manera de un proceso de autosuperción en el que se reconstruye la
lógica nihilista de los proios conceptos metafísico-morales de verdad
y de bien.\\

En suma, el punto de partida de las obras que inicia /Zaratustra/ es
la comprensión de que ésta es una historia en la que la memoria —hecha
presente en el trabajo hsitórico-genealógico— acaba ganándole la
partida al olvido, pues ha sido la misma exigencia de la búsqueda de
la verdad y de autenticidad que siempre han propugnado la metafísica y
la moral cristianas, la que ha terminado conduciendo finalmente a la
exhumación de sus propios fundamentos nihilistas.\\
La misma exigencia moral de veracidad es la que termina por descubrir
las intenciones ocultas y olvidadas de la práctica de
culturización-domesticación que ha predominado como eje del proceso
civilizatorio en Occidente, sacando a la luz el trasfondo de pura
ideología al servicio de unas determinadas condiciones de existencia y
de una determinada forma de ejercicio del poder.\\

Así, el pensamiento del último Nietzsche tiene la pretensión, no sólo
ya de proponer un sentido a dar a sus principales filosofemas, sino
que es necesario también, mostrar los vínculos que los articulan y que
le dan la consistencia que justifica la importancia de su capacidad
para el desarrollo de nuestro presente y su influencia en la
configuración de muchas de las corrientes de la filosofía posterior.

* El eterno retorno
El pensamiento del eterno retorno —que implica sustancialmente la
reducción del tiempo lineal de la historia al tiempo cíclico de la
naturaleza— no obedece sólo a restaurar la visión griega clásica,
presocrática, del mundo, anterior al dualismo metafísico
platónico-cristiano. Tampoco parece sólo un modo de rechazar la
comprensión judeo-cristiana del tiempo que lo entiende formando
momento sucesivos e irrepetibles, según el modelo de la historia
sagrada —creación, pecado, redención, escatología.\\
Aunque obedece al propósito anticristiano de anudar la época moderna a
la Antigüedad naturalista y pagana, Nietzsche lo plantea como el
pensamiento que lleva a su consumación el nihilismo y como la
condición para su superación.

La idea subyacente es la de que sólo en un mundo en el que no se
pensara ya según la estructura de la temporalidad lineal, sería
posible la felicidad plena.\\
El tiempo lineal supone que cada momento tiene sentido sólo en función
de los otros, precedentes y siguientes, y esto hace imposible la
felicidad, porque ningún momento vivido puede tener él mismo una
plenitud de sentido.\\

La temporalidad lineal implica la diferencia esencial entre el ser que
en cada momento se es, deficitario y siempre imperfecto, y de un
deber-ser como modelo y meta ideal que nunca se alcanza.\\
Establece la diferencia entre mundo verdadero, como mundo de realidad,
y mundo aparente, como ilusión y engaño.\\

La creencia en la temporalidad circular implicaría la supresión de la
ditinción entre mundo verdadero y mundo aparente, así como la
existente entre ser y deber ser.\\

El eterno retorno es un pensamiento selectivo en la medida en que
muestra la mentira de la metafísica y de la moral platónico-cristiana
al destruir las distinciones /mundo verdadero/-/mundo aparente/, ser y
deber ser, y hace imposible así el modo de vivir del hombre nihilista.\\

El eterno retorno es propio sólo del ser humano feliz, que se da
únicamente en una época o cultura radicalmente distinta a la del
nihilismo.\\

En este mundo nuevo, pensar en la posibilidad de que cada instante de
nuestra vida pudiera repetirse eternamente hasta el infinito
significaría un criterio de valoración ética, porque sólo cuando ese
instante es pleno de sentido y de felicidad se puede querer tal
repetición.\\

En la última etapa N. alude a nociones y conceptos que no desarrolla
explícitamente. Se refiere a ellos con ambigüedades de meros símbolos
poéticos y de alegorías. Con el concepto del eterno retorno pasa
esto. Incluso insiste en la necesidad de asumirlo sin que haya sido
expuesto anteriormente.\\

Desde esta perspectiva, se entiende que N. no piensa en la idea del
eterno retorno como una teoría sobre el ser del tiempo, alternativa a
la concepción metafísica vigente. Sino como de una profecía se
tratase, un anuncio o una doctrina. Lo plantea menos como una fórmula
o un enunciado dirigido al entendimiento y a la comprensión que como
la expresión de un reto, un conjuro y de una tarea dirigidos a la
voluntad.\\
EL eterno retorno tendría que ser el objeto de una experiencia, de una
decisión de la voluntad, como una consecuencia o prueba de la
concepción nietzscheana de la realidad, de la transvaloración de todos
los valores y de superación del nihilismo.\\

[Aún así, Nietzsche se preocupa de explicar la posibilidad de entender
el tiempo como eterno retorno. En la síntesis a la que llega muestra
su acuerdo con la afirmación de que la fuerza del universo es fija, ya
que si no fuese así, a lo largo del tiempo hubiera disminuido y
desaparecido. Pero tampoco aumenta indefinidamente, porque se así
fuese habría llegado a ser infinita, y esto es imposible.\\
En virtud de esta limitación total de la fuerza del universo, no es
más que un caos de luchas incesantes entre centros individualizados de
voluntad de poder.\\
Lo que preside el devenir del mundo no es más que el azar, y no hay
leyes naturales ni históricas que se cumplan a través de él.\\
Por otra parte las fuerzas no tienen libertad para decidir si se
ejercen o no, actúan necesariamente. El mundo resulta ser un
movimiento eternoo que nunca se interrumpe por el hecho de alcanzar un
equilibrio último de todas las fuerzas.\\
Esa eternidad e eternidad de un retorno.]\\

Esto es lo que se deduce de la alegoría del pastor y la serpiente en
/Zaratustra/. Liberándose del nihilismo, da paso a un /über/, a un más
allá del hombre como modo nuevo de ser y de existir. La decisión de
liberarse del nihilismo, es la de afirmar, la de decir sí al eterno
retorno de lo mismo con lo que ello implica y significa. Lo decisivo
en él no es su validez teórica, ni su coherencia lógica, ni su verdad
científica, sino su valor como conjuro, como conjuro de la más alta
afirmación de la vida que pueda imaginarse, que debe ser entendida,
irónicamente, como una nueva religión.\\

En este sentido señala cómo muchas representaciones de la religión
cristiana —e.g. el infierno, la condenación eterna, etc.— no tienen
ningún fundamento de verdad racional sin que eso les haya impedido
haber sido efectivamente incorporadas como condición de vida por los
cristianos y haber determinado durante siglos la dirección de su
comportamiento. Ha bastado con la coacción tiránica de un poder
autoritario como el de la Iglesia y mucho tiepo para que calara
profundamente.\\

De modo análogo debería suceder con el eterno retorno. No es preciso
que se demuestre como la verdadera realidad del tiempo Ni si quiera
necesita ser una idea verosímil o probable, sino que lo que tiene que
ser es una idea eficaz como instrumento de transformación y de
educación, una idea asumida porque simplemente se la quiera afirmar
como tal y decirle sí. En este dirigirse a la voluntad y a la decisión
es donde el eterno retorno encuentra su sentido propio y esa eficacia
transformadora o transfiguradora que N. le confiere.\\

El eterno retorno es la más alta afirmación de vida, el instrumento
necesario para discriminar entre hombres nihilistas y el
übermensch. En la concepción lineal del tiempo, puesto que cada
instante presente hace depender su existencia y su significado de su
conexión con el pasado, que ya no existe, u de su anticipación del
futuro, que todavía no existe, ninguno de los momentos del tiempo
lineal en su particularidad de presente, de pasado o futuro logran ser
momentos vivos, depositarios de una plenitud autónoma de significado y
de existencia. De este modo, la vida, su sentido y su valor se
encuentran siempre situados o más acá o más allá de un presente que
nunca realiza su cumplimiento.\\
Esta es la forma más extrema y radical que pueda pensarse de negación
de la vida, porque no implica sólo na desvalorización moral o una
negación general y global de ella, sino que representa su negación
instante por instante, despojarla de realidad y de valor al introducir
la no-existencia, la nada como contenido propio de cada uno de los
instantes que la constituyen.\\

De ahí la convicción del nihilista que vive según esta experiencia de
la temporalidad lineal de que la vida no es, en realidad, un vivir,
sino sólo un ilusorio pasar, una pura apariencia de sueño cuyo
trasfondo de nada la delata como sin sentido, como absurda en sí
misma, siendo necesario proyectar el sentido y el valor en un
trasmundo, un más allá, en una trascendencia.\\
La concepción lineal del tiempo es la manifestación principal del
resentimiento y del espíritu de venganza contra la vida, de modo que
sólo se superaría el nihilismo si se lograr entrar en otro modo de
entender y de vivir la temporalidad que fuese a su vez su redención.\\

El eterno retorno significa como ese otro modo de vivir el tiempo,
ofreciéndose como reto a la voluntad cuya afirmación haría entrar en
otra forma distinta de vivir la temporalidad .\\
El eterno retorno se ofrece como la decisión para un nuevo modo de
aplicar la exigencia ética de articular el tiempo, de modo que de ella
resulta el gozo y la afirmación de la vida en lugar de su extrema
negación.\\


*En qué consiste esta forma de vivir el tiempo, y qué es lo que
implica?*\\
El eterno retorno significa también vivir en el presente. El presente
ya no es este instante vacío, de no-ser, sino que es pleno y vivir en
él. Requiere reunir en el instante presente los recorridos de los
tiempos, del pasado y del futuro. Hay que ser capaz de reordenar la
sucesión vertiginosa de los momentos del tiempo lineal sometiendo su
pluralidad a una unidad para conferirles así un sentido nuevo.\\

El *modo de hacerlo* es imponiendo a esa unidad del instante presente
una forma, una interpretación que reinterprete el pasado que ha
conducido hasta aquí y reoriente el futuro articulando lo que todavía
no es más que un azar. Así, desde esta perspectiva, el pasado no sería
ya lo sucedido en sí, algo que yace detrás del presente de manera
inexorable ejerciendo sobre él una determinación fatal e irreversible,
sino que en cada momento del presente, se interpreta el pasado, se lo
recrea y reconstruye libremente. No es algo que escape a la libertad y
a la voluntad, sino que su sentido depende de lo que se quiera y se
decida en el presente que signifique.\\

Del mismo modo el futuro no es el ámbito de lo totalmente imprevisible
y azaroso, sino el espacio en el que se lanza un proyecto a partir de
una anticipación que se hace en función del conocimiento presente y de
la reinterpretación del pasado.\\
El futuro no está situado al margen de la libertad, de la capacidad de
control de la decisión de la voluntad. Se lo puede anticipar en cierta
medida y construir libremente desde el presente en función del sentido
que se quiera proyectar sobre él.\\

Por eso, sea como hay sido el pasado, es posible amarlo en la medida
en que siempre es posible reinterpretarlo viendo en él las condiciones
que han conducido al presente y a partir de la voluntad con la que se
da un sentido a la vida de cara al futuro. Este querer el pasado no es
ya ni resignación no fatalismo, sino que es quererlo al
reinterpretarlo en íntima conexión con el presente y el futuro.\\

Todo esto es dar una necesidad al tiempo, imponerle una forma
superando la falsa idea de su linealidad inexorable tal como la ha
enseñado la metafísica y la religión cristiana, que separan como
momentos irreconciliables e inconexos pasado, presente y futuro.\\
Y esto es también lo que significa asumir un destino como ley que
reorganiza una y otra vez la existencia, actualizando siempre de nuevo
las metas por las que discurre y haciendo posible así el despliegue
del impulso de autosuperación.

* El eterno retorno u la noción de interpretación
La contradicción entre el eterno retorno e historia se desvanece desde
el momento en que se comprende el eterno retorno como un
acontecimiento histórico, como algo que sucede y acontece dentro de la
historia. En vez de ser una verdad ontológica sobre el ser del sí del
tiempo, no sería más que una interpretación que cuando se adopta,
cuando se afirma, se vive la inanidad, la vacuidad, la futilidad de
todo sentido creído como significado o verdad en sí del mundo y se
descubre la inconsistencia de todos los pretendidos valores absolutos,
llegándose a la consumación del nihilismo. Asumiendo el eterno retorno
como interpretación, el individuo toma conciencia de que la historia
misma no es otra cosa que una confrontación incesante de
interpretaciones y de opciones de valor en la que la consumación final
del nihilismo no sería más que un acontecimiento de este tipo.\\

La aceptación del eterno retorno podría dar lugar a una reorientación
de la historia con valor de novedad sobre la que ya había, y
determinar su curso en la dirección precisamente que no permiten las
concepciones ontológicas: en la dirección de una libre creación del
destino de la humanidad al convencer a ésta de la ausencia de leyes
internas ocultas y de sentidos prestablecidos respecto de los cuales
los individuos sólo son seguidores e instrumentos.\\
Por eso, el eterno retorno puede cumplir una función dismitificadora,
desestabilizadora y corrosiva radical de las comprensiones metafísicas
de la historia, y teniendo un contenido un determinismo total e
incluso un fatalismo, puede, sin embargo, introducir el azar en el
concepto de historia.\\

Si el eterno retorno no es más que una interpretación instrumental, no
una verdad en sí, es compatible con una idea de la historia en la que
ninguna necesidad superior al individuo ordena el devenir al
cumplimiento de fines universales. La única necesidad que actúa en la
historia son los individuos, que se comportan a través de
interpretaciones y posiciones de valor. El devenir está abierto a
posibilidades distintas que sólo dependen de los seres humanos mismos,
de las interpretaciones y valoraciones que dan a su vida y a sus
actos. El eterno retorno no es más que una de estas interpretaciones,
con la que el ser humano podría superar el nihilismo.\\

Por otro lado, otra de las ventajas de este pensamiento del eterno
retorno es que permite entender la historia sin necesidad de pensar en
un final de ella como una ruptura y nuevo comienzo. Como simple
interpretación y como experiencia afirmativa, el eterno retorno puede
cambiar el curso de la historia inaugurando una etapa de mayor
autonomía y emancipación individual. Esto, no quiere decir que el
eterno retorno —la consumación del nihilismo— lleve la historia a su
final y le dé asó un nuevo sentido, aunque negativo, encerrándola en
una totalidad. El nihilismo no designa en N a la historia como tal,
sino sólo a la historia europea y, dentro de ella, a la época
presidida por la fe cristiana y sus consecuencias.\\

La consumación del nihilismo no puede hacer pensar en una teleología
catastrófica determinada por un destino como necesidad superior. No
hay más destino que el que se sigue de una opción histórica que no es
nada predeterminado como ley ontológica, sino un punto de partida
azaroso. El destino que obra en la historia del nihilismo es algo que
determinadas decisiones humanas crearon, no es el Ser el que destina
aquí, sino que son la decisiones humanas.\\

La historia así entendida no tendría ninguna unidad, no sería ninguna
totalidad cerrada entre un principio y un final únicos. Sería sin
principio ni fin. La historia no es más que la sucesión de posiciones
de valor y significados perspectivas en lucha, a través de los cuales
diferentes tipos de individuos tratan de justificarse y predominar
sobre los demás. El cometido a cumplir por la idea del eterno retorno
no es más que el de presentarse como una interpretación instrumental
para modificar la comprensión de la historia, y dejar de verla
justamente como un proceso ontológico.\\

La acción renovadora, autosuperadora que se desea promover, no
significa no representa ningún corte, el final de la historia y el
comienzo de un más allá, sino sólo un cambio que se produce dentro de
la historia, una transformación cuya estructura no es sustancialmente
distinta a la estructura de misma del devenir histórico y del devenir
del mundo en general, un simple cambio de interpretaciones y de
valoraciones, una transvaloración.\\

La transvaloración no es más que una confrontación entre
interpretaciones, un acontecimiento más en la cadena de luchas y
enfrentamientos entre centros desiguales de poder, en torno a los que
gira, como su eje, el conjunto de todo lo que existe. Se trataría sólo
de una acontecimiento determinado por el triunfo de un tipo de
voluntad de poder que implicaría, si se produjera, la reorientación
del curso del curso de la historia en una dirección distinta a la que
le han dado el predominio de otras relaciones de fuerzas. No hay más
que un juego de voluntades de poder que es amoral, que no es tampoco
ontológico, y que no puede dar apoyo a ideologías ni verdaderas ni
falsas, ni buenas ni malas, sino tan solo provechosa o perjudiciales
relativamente, según la óptica de la vida y por referencia a un
individuo o a un grupo de individuos determinado.\\

* La hipótesis de la voluntad de poder
La propuesta nietzscheana de la voluntad de poder tiene el carácter de
una simple hipótesis y no el de una tesis ontológica o incluso
metafísica. Esta hipótesis se formula para explicar y comprender, de
manera particular y concreta , el movimiento, la acción o el acontecer
del mundo, contraponiéndola al modo en que este acontecer había sido
explicado tanto por la metafísica como por la ciencia.\\

La voluntad de poder introduce la novedad de entender el universo como
un relacionarse entre sí de una pluralidad de centros de fuerza que
tienen las mismas características de lo que nosotros conocemos como
voluntad, como querer. No habría más motor que inicie e impulse el
movimiento del mundo que la interacción de estas fuerzas o voluntades
unas con otras.\\
Estas interacciones de voluntades sustituiría a la de la relación
causa-efecto, que era la base tanto de las explicaciones metafísicas
como científicos del acontecer del mundo.\\

La voluntad de poder se caracteriza por el /pathos/ del querer, que es
siempre un mandar. Frente al esquema anterior de causa y efecto,
N. trata de ofrecer un nuevo modelo explicativo que es el de la
relación mandar-obedecer.\\
Critica del modelo causa-efecto el recaer inevitablemente en un
determinismo: de las causas se siguen necesariamente los efectos, y
esto no puede ser más que así, si alteración posible.\\

Para Nietzsche lo que sucede es lo propio de la relación
mandar-obedecer, que hay una fuerza que quiere poder más que las demás
y que manda desde un sentido de superioridad o de mayor fuerza a las
fuerzas que quiere que le obedezcan. Lo que hay son fuerzas mayores o
más poderosas que tratan de dominar a las menos fuertes, las cuales
pueden, o bien ceder y obedecer a ese mandato, o bien resistirse y
negarse a doblegarse.\\

El mandar transmite algo que no es simplemente una orden externa que
se emite en el plano consciente. Por debajo de esta orden externa, lo
que transmite el mandar es un impulso, una fuerza que provoca en la
otra voluntad una modificación y una transformación concomitante. Se
produce en la voluntad a la que va dirigida el mandato desde dentro de
ella misma y de manera autónoma: Ante la presión del mandato ejercido
por la fuerza que se propone como superior, la fuerza destinataria
puede obedecer o bien resistirse al mandato. En los dos casos hay una
modificación que se produce desde dentro y autónomamente. No hay aquí
el determinismo externo de la relación causa-efecto, sin ninguna
posibilidad de que el efecto no se produzca. En cambio, en la relación
mandar-obedecer existe esa transformación desde dentro que se produce,
en las dos fuerzas en lucha, de manera autónoma.\\

Para Nietzsche el planteamiento de la ciencia moderna es ilusorio,
porque consiste en la simulación de estar fuera del mundo y tratar de
ver desde fuera relaciones externas de causa.efecto entre las
cosas. La ciencia moderna lo llama objetividad, porque uno de sus
principios básicos es el que de que el conocimiento científico no
puede tener nada de subjetivo.\\
Para Nietzsche esto es absurdo, porque no es posible salir uno de uno
mismo y del mundo para ver las cosas desde esa exterioridad
objetiva.\\
Propone es reconocer que nuestro acceso al conocimiento del mundo
parte, lo queramos o no, de dentro de nosotros mismos, y sobre todo
parte de la experiencia de nuestro propio cuerpo como lucha de fuerzas
y enfrentamiento de voluntades de poder. Su propuesta metodológica es:
tomar el cuerpo como hilo conductor de toda investigación; suponiendo
que nuestro mundo de apetitos y pasiones sea lo único real que está
dado, que no podamos ascender o descender hacia ninguna otra realidad
que precisamente la realidad de nuestras pulsiones, pues pensar es
solo una interacción de estas pulsiones entre sí. De aquí, es lícito
el planteamiento de si este estar dado no bastaría para comprender
también, partiendo de lo idéntico a sí mismo, el llamado mundo
mecánico, material, el mundo visto desde dentro, el mundo definido y
caracterizado de acuerdo con su carácter inteligible, sería justamente
voluntad de poder y nada más.\\

Nietzsche piensa que la energía constante total del mundo, movida por
la aspiración de las voluntades de poder que la integran hacia el
logro de un máximum de poder, alcanzaría un determinado novel cenital
de organización como suma de fuerzas en juego, como un vértice, en la
jerarquización interna del mundo. Una vez alcanzado, se hundiría
disgregándose de nuevo en una multiplicidad anárquica. Esto sería un
círculo eterno. El sentido de Dios sería Dios como estado máximo, como
un época, un punto en el desarrollo de la voluntad de poder desde el
cual se explicaría tanto el desarrollo ulterior como lo previo, la
hasta-él.\\
Dionisio es ese dios que muere despedazado y vuelve a renacer de sí
mismo como consecuencias de lo que la naturaleza es en cuanto
pluralidad de voluntades de poder. El caos del mundo no contradice el
orden de un retorno cíclico y regular. Ambas cosas proceden de lo que
la voluntad es. El devenir, el ciclo, se origina así en la lucha
incesante de las voluntades de poder.\\

Otro punto esencial de esto es el modo en que tiene lugar el combate
entre las fuerzas por lograr el máximo poder. Esto es justamente el
ejercicio de la evaluación y de a interpretación, la imposición por
parte de una fuerza dominante de un sentido o de un valor a las otra
fuerzas en función del juego de dominación propio de los afectos en
lucha.\\
Interpretar una cosa, evaluarla, es imponerle un significado o
conferirle un valor. Y ese es el medio más originario de intentar
dominarla.\\
Esta actividad de interpretación y de evaluación de la voluntad como
un proceso de digestión de la realidad por el que una fuerza crece
alimentándose de otras fuerzas. Esta asimilación es siempre selectiva,
empieza con un acto de discriminación de las fuerzas para asimilar
aquellas que se estiman como susceptibles de ser eficazmente
incorporadas, por su capacidad para autofortalecer y aumentar el nivel
propio de poder, mientras que todo lo que no se estima útil para este
fin es desestimado y desechado.\\

Con todo, Nietzsche está ensayando un manera alternativa de explicar
el acontecer en la naturaleza tal como la que había propuesto el
darwinismo, que entendía este acontecer como una evolución cuyo motor
es la lucha externa regida por la necesidad de adaptación al medio y
por el principio de la selección natural.\\
Nietzsche acepta las tesis de lucha del darwinismo pero añade que en
esa lucha entre las fuerzas que se confrontan no se produce según el
esquema causa-efecto, de la determinación del medio como causa.\\
Para Darwin, el ambiente externo y sus condiciones son los estímulos
que producen como efectos determinísticamente las respuestas de
adaptación de los seres vivos.\\
Nietzsche en cambio, el movimiento no parte del medio externo, sino
que parte de dentro de los seres vivos, que tienen constitutivamente
un poder interior de creación de formas, de órganos, de
funciones. Defiende un principio de autorregulación interior como
poder propio de los seres vivos, frente al mero adaptacionismo de los
darwinistas.\\

En esta perspectiva de la voluntad de poder y a su afecto de mandar le
es concomitante un sentimiento de placer o de displacer. El placer
sobreviene cuando se alcanza aquello a lo que la voluntad de poder
realmente tiende, o sea, el poder. Y que el dolor sobreviene cuando el
poder no se consigue o se pierde.\\
Así, este placer no es el placer provocado por el poder no por la
posesión del poder, sino el placer que sobreviene como consecuencia de
la percepción del aumento de poder y de la diferencia que eso marca
frente a las otras fuerzas —el placer es un síntoma del sentimiento
del poder alcanzado, un llegar a una consciencia de la diferencia; el
viviente no aspira al placer, sino que el placer aparece cuando el
viviente alcanza aquello a lo que aspira.\\
El placer en la voluntad de poder como lucha de fuerzas es el de la
victoria sobre otras fuerzas, victoria que hacer aumentar su propio
poder, mientas que el dolor es el dolor de la derrota y la percepción
de una disminución de la cantidad de poder.\\
Pero la principal dificultad de esta caracterización radica en tener
que admitir una explicación para las ciencias —física, química etc.—
donde no hay manera de considerar una voluntad de poder con
sensaciones de placer o de dolor, no con otros sentimientos
concomitantes al aumento o a la disminución de la fuerza. La respuesta
de N. consiste en proponer su hipótesis como un giro hacia una
interpretación del mundo de los fenómenos desde dentro de los sujetos
de conocimiento, en lugar de desde fuera como hace le mecanicismo, que
serviría para hacer avanzar el saber en una dirección a la que la
ciencia moderna se ha cerrado.\\

** La nueva concepción de ciencia
El conjunto de observaciones críticas con las que N. cuestiona la
ciencia moderna está en su nueva concepción de lo que es ciencia y de
lo que es un hombre de ciencia.\\
El *hombre de ciencia* no es sino un intérprete, un filósofo cuya
tarea principal consiste en descifrar los fenómenos naturales,
históricos o culturales con las claves que proporciona el texto del
cuerpo. Y esto según dos condiciones: puesto que el cuerpo interpreta,
la salud y la enfermedad deben ser consideradas como los determinantes
de la calidad y del valor de toda interpretación. La segunda condición
es que en el ejercicio de la práctica interpretativa es preciso
explicar cómo funciona y se aplica el criterio para diferenciar una
buena de una mala interpretación. Si en lugar de la verdad-falsedad
son la salud-enfermedad los nuevos determinantes del valor de toda
interpretación, es obvio que será distinta la actividad interpretativa
que brota de una voluntad de poder sana, activa. Por el contrario, la
que es producto de la mera negación, reactiva, en la medida en que la
conciencia no es mas que una instancia subordinada que ejecuta las
órdenes emitidas por los impulsos y que toda nuestra actividad
espiritual o culturas está determinada y dirigida por el dinamismo
propio de nuestras configuraciones instintuales.\\

Así pues, no hay conocimiento objetivo y desinteresado de leyes en sí
del mundo, o de esencias existentes en un mundo inteligible. Ni
tampoco valores en sí, sino juicios concretos de valor interiorizados
en virtud de ese proceso de incorporación en la que consiste la
socialización.\\
Si las teorías científicas, los valores morales de una sociedad o de
un individuo, no son otra cosa que la traducción de las necesidades
propias de un organismo como cuerpo que interpreta, esto determinará
una diferencia entre la expresión del tipo de exigencias fisiológicas
que brotan de un cuerpo como voluntad de poder, está exigiendo una
fisiología que no es ya la de la ciencia newtoniana. Conocer y juzgar
de forma genealógica es ahora considerar que el suelo de la vida
fundamenta y constituye el sentido y el valor de las opciones teóricas
espirituales o culturales.\\
La vida es susceptible de vivirse básicamente como salud o plenitud de
fuerzas y como decadencia, declive o debilitamiento de las fuerzas.\\
Por otra parte la segunda condición del arte de leer bien el cuerpo es
lo que N. llama la *honestidad filológica*, que implica una
transformación radical en la concepción de la verdad.\\
Verdad ya no se entiende como la explicación correcta y adecuada de un
texto en sí, sino como aquella clase de interpretación que cumple
determinados requisitos de honestidad.\\
Muchas de sus críticas a la ciencia y a la filosofía de la moral, son
debidas a malas lecturas o incluso denuncias por la tradición entera
de la cultura occidental.

* Voluntad de poder activa y decadencia
En la voluntad de poder, la noción de vida sana, no decadente no
enfermedad, es voluntad de poder activa que aspira a confrontarse con
dificultades y a superarlas. No rehuye las dificultades ni el dolor,
sino que los afronta y los quiere como el mejor medio de crecer de
fortalecerse y de convertirse en algo más.\\

El sentimiento de bienestar y de placer como ausencia de dolor y de
conflictos el que subyace a la concepción nietzschana de la salud,
sino la autoafirmación como predomino de las fuerzas activas sobre las
reactivas y como ejercicio de una voluntad de poder que aumenta
venciendo sufrimientos y resistencias.\\
Se deducen dos condiciones distintivas de la salud: (/i/) el poder de
afirmar la vida en su fluir caótico, imprevisible e incontrolable sin
temor a los aspectos dolorosos que pueda producirse y (/ii/) el poder
de armonizar las fuerzas más opuestas sometiendo su diversidad
conflictiva a una ley, a una unidad simple, lógica, categórica, a la
clásica del gran estilo.\\

Salud es ser lo bastante fuerte como para no retroceder ante el dolor
de la vida, sino aprovecharlo para llegar a hacerse aún más
fuerte. Salud es no dejarse descomponer por el caos pulsional de los
propios instintos, sino hacerse dueño del propio caos que se es y
construir, a partir de él, la armonía de un proyecto vital.\\
Para N. los griegos consiguieron ambas cosas, y de ahí el valor
modélico clásico de su cultura. Con su arte y su religión proyectaron
sobre el fondo cruel y terrible de la vida la apariencia multicolor de
sus dioses olímpicos apolíneos, y practicaron el orgiasmo musical
dionisíaco. La voluntad de lo trágico es la fuerza básica de la
autoafirmación como impulso de vida ascendente y como fuerza para la
que el dolor actúa como un estimulante. El arte clásico, arte de la
salud en el que lo pulsional, fuente de toda creación, es dominado por
una ley y sometido a una forma.\\

Frente a la imagen de salud, lo propio de la decadencia, como voluntad
de poder, es una disminución de la fuerza y, por tanto, el predominio
de un miedo al dolor en el que no se percibe ya su conexión con el
placer. La fuerza para acrecentarse y para producir el sentimiento de
un placer superior, tiene que esforzarse, tiene que sufrir venciendo
resistencias y obstáculos sin los cuales no se ejercita no puede
aumentar. Lo característico del decadente es no aceptar el dolor,
excluir el dolor del estado creador original. La disminución de la
fuerza, propio de la decadencia, tiene como consecuencia la
desaparición de las condiciones de la salud.\\
Por un lado da lugar a la negación de los aspectos terribles y
trágicos de la vida. Por otro se mueve en medio de un cierto caos
pulsional que no es autónomamente controlado ni sometido a ley.\\

En la /genealogía de la moral/ describe los rasgos de la decadencia en
tres ámbitos: la filosofía, la religión y la moral. Todos tres
presididos por los ideales ascéticos inspirados en el resentimiento y
la mala consciencia.\\
Las objeciones de N. a la cultura dominada por estos ideales pueden
resumirse diciendo que se ha complacido en la decadencia y se ha
identificado con ella.\\

El cristianismo, como columna vertebral de la cultura europea a lo
largo de los siglos, es para N. el paradigma genealógico-hermenéutico
opuesto al que ofrece la cultura griega. Ejemplificarían los dos polos
enfrentados que marcan esa diferencia interna a la voluntad de poder
que es el de la enfermedad y la salud.\\

El cristianismo y su moral son degeneración psico-fisiológica,
voluntad de poder reactiva, enfermedad y neurosis.\\
Si la salud —cuyo paradigma es la cultura griega— es capacidad de
someter a control el caos pulsional de los propios instintos, lo
propio de la decadencia es buscar en la cultura remedio a su
agotamiento, estimulantes o tranquilizantes.\\

Nietzsche ve en la moral cristiana toda una retórica teatral, un
constante exageración histérica animada por na intención de tiranizar
oculta.\\
En esto es lo que encuentra una similitud entre e cristianismo y las
ópera de Wagner. Los dos modelos ejemplares de lo que entiende por
decadencia.\\
La decadencia que equivale a descontrol de los instintos, da origen a
una sensación de miedo y de inseguridad por la incapacidad para
controlarlos. Entonces se impone la necesidad de tiranizar, que sería
la que habría presidido y determinado todo el proceso de culturización
occidental que no habría consistido esencialmente en otra cosa que en
un proceso de domesticación y desnaturalización del hombre.\\

Lo criticable de la decadencia como subsuelo de la cultura occidental
no sería la decadencia en sí, ni la enfermedad de la voluntad, que son
una faceta de la /physis/ y del cuerpo, lo mismo que la salud. Lo
criticable es que se la haya querido, el haberse complacido en ella y
haberla utilizado como resorte de una tiranía que ha convertido en
equivalentes culturización y desnaturalización.\\

Para que el hombre nihilista y enfermo recupere la salud, ha de llevar
a cabo una determinada recuperación de su mundo institucional y
pulsional. Pero este trasfondo no es el fundamento natural del hombre,
como su verdadera y originaria naturaleza.\\
Los instintos o son ningún principio originario, no son la cosa-en-sí
como fundamento de lo que el ser humano auténticamente es, de manera
que podamos hablar de una instintividad humana que debe ser liberada
como su verdadera naturaleza. Los instintos son la fuerza que se va
configurando y moldeando en función de la orientación que les imprime
la cultura, y en especial la moral.\\
Es aqeullo más importante del comportamiento, no porque sean innatos,
sino porque so lo que cubre el vacío de automatismo genético que
tienen los animales.\\
Los instintos, una vez configurados y consolidados, se convierten en
una segunda naturaleza, dirigen el comportamiento de una manera
espontánea anticipándose a cualquier intervención de la reflexión y de
la consciencia. Por eso es importante se moldeado o configuración, su
educación.\\

Si esto fuese así, se podría intentar un giro e iniciar un proceso de
reconfiguración de so instintos para que su energía resulta creativa y
produzca en los individuos la salud en vez de la enfermedad.


* El proceso civilizatorio europeo

