#+LATEX_CLASS: article

# -*- mode: org; -*-
#+LATEX_CLASS_OPTIONS: [a4paper, 11pt, twocolumn, spanish]
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[margin=.75in]{geometry}
#+LATEX_HEADER: \setlength\parindent{0pt}

#+Title: Apuntes de Teoría del Conocimiento ii
#+SUBTITLE: III La nueva filosofía de la ciencia
#+AUTHOR: Jordi Serra

* Introducción
** El final del modelo clásico de cientificidad
En las últimas décadas del s. XX hubo un profundo cambio en el ideal
clásico de cientificidad. Se ha perdido el sentido lineal y
acumulativo del devenir científico y se ha introducido la acción
humana en la historia de la ciencia. La ciencia deja de ser un
lenguaje perfecto. El mito de la presunta superioridad objetiva de la
ciencia se viene abajo , al quedar de manifiesto la inserción de la
elección en la práctica científica cotidiana.\\

El ideal clásico de cientificidad estaba representado por el
neopositivismo lógico. En contraposición a éste, podemos simplificar
en tres las nociones importantes en la nueva teoría de la ciencia.
  1. Los hechos científicos son relativos al sistema conceptual
     utilizado para poner en evidencia su articulación, susceptibles de revisión a medida que se vaya modificando el sistema.
  2. La evaluación de las hipótesis científicas, particularmente en
     las teorías que revisten un alto grado de complejidad, implica un
     tipo de apreciación que supone un largo entrenamiento, no siendo
     reductible a reglas formales explícitas de inferencia. Una
     reconstrucción puramente lógica de la confirmación científica
     debe necesariamente resultar incompleta.
  3. Teoría rivales pueden ser inconmensurables entre sí. Puede que
     sus sistemas conceptuales respectivos no se corresponden
     suficientemente como para hacer posible una comparación
     directa. O también los valores metodológicos que se incorporan a
     las teorías no son los mismos. En consecuencia, no se dispone de
     una metodología que haga posible una comparación entre ellas.

** Teoría de la ciencia y práctica científica
Hasta la fecha, se sostenía que las proposiciones verdaderamente
científicas debían fundarse bien en la intuición (Descartes), bien en
relaciones de observación (Locke), bien en principios sintéticos a
priori (Kant).\\

Durante el s. XIX, el auge de las ciencias atrae la atención hacia el
estudio de sus métodos de trabajo y a su historia misma, desviándose
de este punto de vista. La aparición del círculo de Viena, enfatizando
el conocimiento positivo, basado únicamente en la observación sensible
de los hechos y en la lógica formal como instrumento de análisis
(según el modelo de Russell), vuelve a restablecer la vigencia de las
tesis clásicas en teoría de la ciencia.\\

Para los positivistas lógicos las proposiciones básicas, en las que se
expresan las observaciones de la ciencia experimental, pueden servir
de base a generalizaciones cada vez más amplias.  Intentan formular la
relación de confirmación entre una hipótesis y una proposición que
exprese una evidencia. Esta corriente surge como una reacción frente a
la retórica y las abstracciones de cierta filosofía basada en el rigor
matemático de los lógicos.\\
Se tiene una clara imagen del estado de la ciencia en cada etapa. Se
empieza a partir de los hechos establecidos y se hace uso de los modos
de inferencia para llegar al nivel de las leyes y de las teorías. Se
puede tener una conciencia exacta tanto de significación como de
verdad, sobre el estado en que se está y sobre las relaciones de
proposiciones de cada estado y los hechos a partir de los cuales se ha
razonado.\\

Este método no se puede generalizar a cualquier proposición que se
quiera saber si es verdadera o no. El principal fallo de esta
concepción de la ciencia fue no haber prestado atención a la historia
real de las ciencias y a los cambios conceptuales. A partir de Popper,
se trata de construir la teoría de la ciencia sobre una base más o
menos vinculada a la práctica misma de la ciencia, mejor que a partir
de una teoría general del conocimiento como había sido el caso en la
tradición epistemológica clásica.

* Principio de verificación y unificación del lenguaje científico. El círculo de Viena
** La división del discurso
*** El isomorfismo lenguaje-realidad según el /Tractatus/
El */tractatus/* está escrito en forma de aforismos numerales según el
sistema decimal y contiene siete proposiciones fundamentales.\\
Las dos primeras /El mundo es todo lo que acaece/ y /lo que acaece, el
hecho, es la existencia de los hechos atómicos/ se refieren al mundo y
a la realidad.\\
Mientras que las cuatro siguientes son un desarrollo de la lógica y de
teoría del lenguaje.\\
La última proposición, la enigmática frase De lo que no se puede
hablar mejor es callarse, cierra el libro marcando el límite de lo que
se puede pensar y decir (la proposición).\\
Aunque la mayor parte del /tractatus/ habla de la lógica y lenguaje (de
la proposición), los párrafos iniciales tratan del mundo y de la
visión metafísica del mundo en términos del atomismo lógico
(Russell).\\
El mundo es la totalidad de los hechos y el lenguaje es la totalidad
de las proposiciones. Ambos comparten una estructura lógica común y
Wittgenstein relaciona realidad, lógica y lenguaje mediante *tres
conceptos fundamentales*: hecho atómico, figura lógica y
proposición.\\

  1. Hechos atómicos. El constituyente último del mundo son los
     objetos o cosas, las entidades que percibimos con los
     sentidos. Los objetos son simples y forman parte de los hechos
     atómicos. El hecho atómico es la combinación o relación de
     objetos o cosas. Éstos son la substancia de que está hecho el
     mundo, su constituyente básico. Pero de las cosas del mundo sólo
     podemos conocer lo que acaece (hacerse realidad). Esto es, los
     hechos atómicos o simples, los hechos compuestos de simples, o
     simplemente hechos, cuyo conjunto constituye la realidad.
  2. La figura lógica. Paralelamente, el lenguaje opone a las cosas
     del mundo nombres. A los hechos atómicos, proposiciones simples;
     y a los hechos complejos proposiciones compuestas. El lenguaje
     puede representar la realidad del mundo. Cuando por medio de
     proposiciones describe hechos, la estructura de las proposiciones
     en relación a la de los hechos, y viceversa, se preserva. Este
     isomorfismo entre el lenguaje y la realidad, es posible gracias a
     la participación de ambas instancias en una misma estructura
     común.
  3. La proposición o el signo con que expresamos el pensamiento
     representa un estado de cosas (un hecho atómico). Si este es
     real, la proposición es verdadera. El conjunto de todas ellas
     describe el mundo. Sólo las proposiciones, y no los nombres, son
     significativas y muestran la lógica de la realidad. Las
     proposiciones siempre tienen sentido, aunque sean falsas, porque
     siempre describen lo que acaece en el mundo. Y sólo pueden tener
     sentido cuando describen lo que acaece en el mundo.

Las proposiciones que no describen hechos carecen de sentido. Éstas
son de dos clases:
  1. Comprende las tautologías o enunciados necesariamente verdaderos,
     que nada dicen respecto del mundo. (o sus negaciones, las
     contradicciones.)
  2. Aquellas proposiciones que no comparten figura lógica con la
     realidad que pretenden representar.
     
Esto último sucede de dos maneras. Porque se la da a un signo un
sentido falso, una mala orientación, construyendo enunciados que
contienen signos carentes de significado, como sucede con las
proposiciones mal construidas o con las de carácter metafísico. O
porque apuntan a objetos que quedan fuera del mundo, trascienden el
mundo, queriendo expresar lo inexpresable, como pasa con las
proposiciones sobre ética y aquellas que quieren esclarecer el sentido
del mundo, las proposiciones metafísicas.

Así pues, sólo las proposiciones delas ciencias empíricas tienen
sentido. La lógica consta únicamente de tautologías, y toda
proposición sobre ética o metafísica es una proposición carente de
sentido. El análisis filosófico ayuda a esclarecer el sentido de las
proposiciones del lenguaje ordinario; las del lenguaje filosófico las
declara carentes de sentido.

*** La ciencia habla de la realidad, la filosofía habla del lenguaje
El principal criterio de diferenciación consiste en afirmar que sólo
la ciencia habla con legitimidad y sentido acerca dela realidad
extra-lingüística, mientras que la filosofía sólo tiene la tarea de
esclarecer, unificar, sistematizar y analizar el lenguaje
científico. El trabajo científico produce la representación
lingüística o simbólica adecuada a la realidad. La filosofía es una
actividad de segundo orden, metalingüística, que tiene por objeto el
lenguaje y el discurso de las ciencias. Sólo excluyendo la ambición
ontológica o metafísica de la filosofía tradicional, puede asignares
la labor a la filosofía de analizar con ayuda de la lógica formal el
lenguaje científico de la ciencia.\\

Los *enunciados referenciales* son aquellos que se refieren a objetos
que se pueden identificar. Poseen contenido y sentido. Si los objetos
referidos no son lingüísticos los enunciados son *realistas u
objetivos*. Si sí lo son, entonces se llaman *metalingüísticos*.\\
Uno de los objetivos principales del análisis lógico del lenguaje es
descubrir a los enunciados metalingüísticos con apariencia realista y
reformularlos correctamente a fin de que pongan claramente de
manifiesto que se refieren a palabras y no a cosas.

En el neopotivismo, la wittgensteiniana concepción pictórica del
lenguaje se expresa mediante las siguientes distinciones.
  1. Proposiciones con sentido y pseudoproposiciones. Sólo tiene
     sentido un enunciado que pueda ser calificado de verdadero o
     falso. La verificabilidad constituye el criterio del
     sentido. Cuando una palabra posee un significado, se dice que
     designa un concepto, mientras que si esta significación es sólo
     aparente y en realidad no a posee, entonces es un
     pseudoconcepto.\\
     Las condiciones para que una proposición tenga significado son:
     + Que las notas empíricas de los términos incluidos en la
       proposición sean conocidas.
     + Que haya sido estipulado de qué proposiciones protocolarias es
       derivable la proposición a examinar.
     + Que las condiciones de verdad para esa proposición hayan sido
       establecidas.
     + Que dispongamos de un método de verificación.

  2. Enunciados analíticos y enunciados empíricos. Para los
     neopositivistas, el principio de verificación se aplica a un
     enunciado sustancialmente de dos formas.
     + Determinando su coherencia lógica interna mediante el análisis
       de la posibilidad de reducirlo a enunciados más elementales.\\
       Se actúa así con los lenguajes formales con los que la verdad
       se decide sin recurrir a la experiencia porque es determinable
       a priori.\\

     + Recurriendo a la experiencia, que afecta a enunciados
       directamente referidos a la realidad y a los que integran las
       ciencias de la naturaleza.\\
       Son enunciados cuya verificación requiere su confrontación con
       los hechos extralingüísticos a los que remiten.\\
       Es una verificación empírica y a posteriori.

     Los del primer tipo no aportan ninguna información verdaderamente
     que no estuviera ya comprendida en la sintaxis y la semántica del
     lenguaje utilizado. Están desprovista de sentido, como las
     tautologías en la lógica.\\
     En cambio, los enunciados empíricos aportan informaciones sobre la
     realidad fáctica y extralingüística.\\
     En cualquier caso, todo enunciado pertenece a una categoría o a la
     otra.\\

     Una distinción de esta misma distinción es la que se establece
     entre leyes empíricas y leyes teóricas:
       1. Leyes empíricas son las que pueden ser confirmadas
          directamente mediante observaciones empíricas. Son leyes
          acerca de hechos observables. Contienen términos que designan
          hechos observables por los sentidos.\\
	  Se las obtiene mediante la generalización de los resultados
          de observaciones.\\
	  No sólo incluyen leyes cualitativamente simples —todos los
          cuervos son negros—, sino también leyes cuantitativas que
          surgen de observaciones simples.\\
	  Se las usa para explicar hechos observados y predecir sucesos
          futuros observables.
       2. Leyes teóricas o hipotéticas son las que contienen términos
          que no se refieren a hechos observables. Son leyes acerca de
          entidades como moléculas. átomos, electrones, etc. que no
          pueden ser medidos de manera simple y directa.
	 
  3. Enunciados que expresan juicios éticos o estéticos. Al considerar
     el lenguaje básicamente informativo se determinan como ilegítimos
     y sinsentido los enunciados que expresan sentimientos o
     valores.\\
     Los preceptos morales sólo expresan emociones positivas o
     negativas respecto de acciones y de situaciones
     descriptibles. Estos usos lingüísticos no presentan interés para
     la ciencia no para la filosofía.\\

     En esta posición radical en favor del discurso científico como
     idealmente objetivo y universal y este desprecio por las
     expresiones de la subjetividad explican la ausencia de compromiso
     filosófico y ético-político de esta filosofía con la
     sociedad. Sólo el desarrollo de la ciencia y del espíritu
     científico y analítico, lógico y objetivo, cabe esperar un
     progreso real para la humanidad. Mientras ese progreso se
     realiza, nadie está obligado a tomar posición en el terreno moral
     o político. Cualquier discurso filosófico o científico, que
     presenta valores o normas propiamente dichas como si se tratara
     de hechos objetivos o de realidades susceptibles de ser descritas
     de manera verdadera o falsa y de ser conocidas, cae en la falacia
     naturalista. Este sofisma consiste en la confusión entre hechos y
     valores, entre lo que es y lo que debe ser.


** El lenguaje unificado de la ciencia
El ideal de una ciencia unificada es característico del pensamiento
moderno desde Descartes, que se plantean construir una matemática
universal. El neopositivismo retoma este objetivo y lo reformula en el
plano del lenguaje. todas las ciencias han de tener en común la
utilización de un lenguaje. Se espera la superación de la diversidad
de las ciencias si se descubre o se construye ese lenguaje al que se
puedan reconducir los diferentes lenguajes científicos. La unificación
de las ciencias requiere la construcción de un lenguaje universal y
unitario de la ciencia.\\

Carnap en /La estructura lógica del mundo/ (1928) defiende como
condición básica de ese lenguaje que sus enunciados básicos se
refieran a sensaciones y experiencias sensoriales y no a objetos
físicos, que sólo son construcciones hipotéticas a partir de las
sensaciones. Las cosas son elaboraciones lógicas que realizamos sobre
la base de nuestro contenidos sensoriales. Lo propio de las
proposiciones científicas debe ser la posibilidad de que puedan quedar
reducidas a un lenguaje compuesto de símbolos de los contenidos
sensoriales.\\

El problema es que garantiza la objetividad de la ciencia ni su
exigencia universal. Se basaría en experiencias subjetivas de cada
individuo, pudiendo diferir. Los enunciados básicos de este lenguaje
no serían comunes más que en apariencia.\\
Neurah dio un giro distinto con su planteamiento fisicalista. El mundo
está constituido por objetos que existen con independencia de mi
experiencia. A esos objetos se refieren directamente los términos y
enunciados del lenguaje científico. Construir un lenguaje básico para
la ciencia representa descubrir los enunciados elementales y los
objetos o hechos elementales constitutivos de la realidad. Luego se
podrá traducir cualquier enunciado a ese lenguaje básico relativo a
estados  procesos del mundo físico.\\

En el seno del fisicalismo, durante el s. XX se cuestiona la
naturaleza referencial o realista de su propio lenguaje. Por otra
parte, fracasa también en su empeño por reducir fisicalistamente el
lenguaje de las ciencias humanas, como la psicología. El programa
neopositivista de unificación de las ciencias por la unificación de
sus lenguajes se queda en mera aspiración.

** La crítica de la metafísica
El análisis lógico-positivo del lenguaje responsabiliza del sentido o
bien a errores sintácticos en los enunciados, o bien a abusos
semánticos. Es decir, son enunciados sin sentido aquellos en los que
se combinan palabras que pertenecen a categorías diversas, pero que
considerados por separado o utilizados correctamente, tienen
significado. También son sin sentido los enunciados que incluyen
palabras sin una referencia determinable, como los enunciados
metafísicos.\\

El neopositivismo reduce la metafísica a un conjunto e errores
sintácticos y de abusos semánticos del lenguaje. Desde la perspectiva
lógica, los enunciados metafísicos o bien parecen despojados de
sentido, o bien sin el sentido o el alcance que se les quiere
atribuir.
  1. La primera diferencia estaría en la ambivalencia misma de la
     palabra ser. A veces se utiliza como cópula que antecede a y se
     relaciona con un predicado —yo soy el autor de este libro—,
     mientras que en otras designa existencia —yo soy. Este error
     resulta agravado por el hecho de que los metafísicos carecen de
     una idea clara de esta ambivalencia.
  2. El segundo error está en la forma que adquiere el verbo en su
     segunda significación, la de existencia. Esta forma verbal
     muestra ficticiamente un predicado no existente. La existencia no
     es una propiedad. A este respecto sólo la lógica moderna sería
     totalmente consecuente al introducir el signo de existencia en
     una fórmula sintáctica tal que no puede ser referido como un
     predicado a signos de objeto, sino sólo a un predicado.

Es decir, desde la antigüedad, la mayor parte de los metafísicos se
habrían dejado seducir por la forma verbal de la palabra ser, formando
pseudopreposiciones como /yo soy/, /Dios es/, etc. Pero lo
característico de la actitud física sería un determinado modo de
confusión de las palabras y las cosas. La labor del neopositivista
frente a este lenguaje será reconducir sus proposiciones a
descripciones o recomendaciones concernientes al lenguaje y su uso.
La filosofía deja de ser metafísica para reducirse a metalingüística y
transformarse en crítica y análisis lógicos del lenguaje. Este giro
lingüístico debería permitir también a los filósofos entenderse,
puesto que compartirían un punto de vista común (el metalingüístico) y
una referencia común (el lenguaje).

* Investigación científica y desarrollo del conocimiento: Popper
** La crítica a la epistemología inductiva
La tradición empirista tiene como método fundamental de la ciencia
moderna la inducción para establecer conceptos y teorías. Popper
rechaza los tres principios básicos del empirismo relativos al
conocimiento:
  1. Discute el *método inductivo* como método fundamental de desarrollo
     de la ciencia y e la ciencia, la suposición de la capacidad mente
     humana para alcanzar verdades universales válidas que se
     generalizan a partir de la observación repetida de casos
     particulares.\\
     Para Popper no se pueden verificar proposiciones o teorías de
     carácter universal a partir de proposiciones particulares que no
     las contradigan —la observación de muchos cuervos negros no
     implica que todos los cuervos sean negros.
  2. No cree que la mente, en el proceso del conocimiento, adopte
     solamente una *actitud pasiva y receptiva*. La mente no es una hoja
     de papel en blanco en la que la percepción de entrada a las
     sensaciones que se abstraerían para formar conceptos.
  3. Rechaza el *principio de verificación* como criterio de sentido
     desde el cual, los pensadores empiristas y positivistas han
     realizado la crítica a la metafísica que la reduce al
     sinsentido.\\
     Las teorías no son verificable empíricamente.\\
     Es necesario un nuevo criterio que separe la ciencia y la
     metafísica, *demarcación*, establezca las distintas características de uno y
     otro saber.
     
** El problema de la demarcación
Este surge al intentar distinguir las diferencias entre la teoría de
Einstein y las teorías del marxismo, el psicoanálisis y la psicología
del individuo. Popper se pregunta porqué estas últimas son tan
diferentes de las de Einstein, Newton etc. Aún presentándose como
ciencias de hechos, encuentra elementos en común con los mitos
primitivos que con la ciencia, se asemejaban más a la astrología que a
la astronomía.\\

Popper sostiene que la diferencia es que las teorías de Einstein &
cia. podían ser refutadas por un acontecimiento que se predijera
partiendo de ellas, mientras que las otras resultaban siempre
confirmadas por cualquier experiencia posible.\\
Sólo las primeras eran auténticas teorías científicas en la medida en
que sólo de ellas es posible decir que son comprobables por la
experiencia.\\
Pero no desprecia el valor de las segundas, muy importantes en el
devenir de la historia del hombre.\\


La diferencia fundamental entre unas i otras es que las primera no
asumen que el carácter científico de sus teorías viene dado por la
acumulación de hechos que refuerzan el sentido de la teoría
descartando los que no lo hicieran, sino mediante la determinación de
una experiencia decisiva, una prueba en forma de predicción deducida
de la teoría —pero no deducido de la teoría rival, y que pudiera ser o
no precisamente confirmada por la observación.\\

Este punto de partida es el que permite manifestar y ahondar en la
diferencia entre su criterio y el criterio positivista de
significado.\\
Con el criterio de refutabilidad, como criterio de demarcación, traza
una línea divisoria entre los enunciados o sistemas de enunciados
empíricos y todos los otros enunciados. Así, no se trata de un
problema de sentido o de significación, ni de verdad o aceptabilidad,
sino de demarcación.\\

Por al mismo tiempo, el criterio de demarcación envuelve un problema
ontológico de envergadura. Popper se centra en la cuestión del
desarrollo de la ciencia, siendo su referencia polémica las nuevas
ciencias sociales y humanas.

** El aspecto metodológico
Popper entiende la filosofía como teoría del conocimiento científico o
epistemológico. El problema fundamental de la epistemología no es el
de la estructura de la ciencia, sino el del desarrollo de la ciencia
—siempre será un asunto a resolver el de a qué cosa hemos de llamar
una ciencia. La epistemología no debe ser propiamente una lógica de la
ciencia, sino un lógica de la investigación científica, una lógica del
procedimiento según el cual se desarrolla el conocimiento
científico. La epistemología se reduce a metodología de la ciencia.\\
Popper lo compara con el ajedrez, de la misma manera que que es
posible definir el ajedrez mediante sus reglas, la ciencia empírica
puede definirse por medio de sus reglas metodológicas.\\


Esta metodología e la ciencia deberá clarificar el concepto mismo de
ciencia, aunque su problema fundamental será el del desarrollo del
conocimiento. No se trata de precisar un único método, sino que es
apropiado usar tantos métodos necesarios para avanzar en la resolución
del problema dado.\\
De este modo, ni el análisis del lenguaje común que parte de
Wittgenstein, ni el análisis del lenguaje científico del circulo de
Viena son métodos exclusivos de la teoría del conocimiento:
  1. El análisis del lenguaje ordinario no pueden servir como método
     porque no se refieren al problema fundamental del desarrollo del
     conocimiento, que se da precisamente en el paso del lenguaje
     ordinario al lenguaje científico.
  2. Pero tamoco sirve el análisis lógico del lenguaje científico y su
     procedimiento de construcción de modelos ideales (Carnap), por la
     precariedad de estos mismos y porque tampoco tiene como objetivo
     abordar la cuestión del desarrollo de la ciencia.

El único modelo que se puede postular es el de la discusión racional
común a toda pretensión de racionalidad, la ciencia y la filosofía,
que consiste en exponer claramente los problemas y discutir
argumentativa y críticamente las soluciones propuestas.

** El aspecto filosófico
Popper, mediante su criterio de demarcación, trata de distinguir entre
dos tipos de enunciados, de manera que podamos saber a cual nos
referimos cuando hablamos de filosofía de la ciencia. Define así su
problema de la demarcación:
  1. Es el problema de delimitar lo que es la ciencia empírica respecto
     de lo que es sólo pseudociencia. Cuando debe ser considerada
     científicamente una teoría o cuál sería su criterio para
     definirla como ciencia. No se trata de responder a la cuestión de
     la verdad o falsedad de una teoría.
  2. Es el problema de definir qué se entiende por experiencia. en
     último término, delimitar la ciencia es definir lo que entendemos
     por experiencia.\\
     Hay muchos sistemas teóricos posibles. Entre ellos tiene que
     haber alguno que represente el mundo de nuestra experiencia. Este
     es la ciencia empírica.
  3. Es el problema de definir qué se entiende por realidad y por
     conocimiento de la realidad. Se trata del problema filosófico de
     nuestra experiencia e interpretación del mundo.

Este intento de identificar este problema como el problema
metodológico de fijar una convención sobre lo que deba entenderse por
ciencia empírica, *desplaza al ámbito de discusión de la epistemología
a la discusión de la coherencia* de unas reglas metodológicas.\\
Pero los criterios de coherencia están definidos por las propias
reglas del método científico. Supone pues, la renuncia al análisis del
concepto de ciencia, de definir lo que habrá que entender por
experiencia y por realidad.

Esto ha dado pie a algunos *críticos* a denunciar que es inevitable
que lo que quede demarcado como ciencia dentro de la epistemología de
Popper será conocimiento de realidad y lo que queda fuera de la
ciencia será ilusión, engaño o mitología, por más que Popper se empeña
a hacer ver que su problema de demarcación es diferente al problema
positivista de separar enunciados con sentido de los enunciados sin
sentido.\\

En cualquier caso, con la idea de demarcación se eleva una determinada
concepción del método de la ciencia natural a método del conocimiento
científico y racional. Se produce una cierta confusión entre
epistemología y metodología coo consecuencia previa de la
desvalorización de un tipo de racionalidad, e.g. ciencias humanas,
frente a otro, ciencias naturales.\\
Más que la reducción de la racionalidad a la racionalidad científica,
lo característico de Popper es una concepción *empirista y
positivista* de la ciencia y de la filosofía, y de la razón. El
problema del desarrollo del conocimiento desemboca en el problema
general de la racionalidad.

** La falsabilidad como criterio de demarcación

*** Actitud científica y actitud dogmática
Popper el método científico engloba el empleo de la hipótesis de
alcance general la deducción de enunciados particulares que afirman
posibilidad de observación de un hecho determinado, la comprobación en
la medida de lo posible y la decisión de abrirse a comprobaciones
ulteriores en función de la evolución del conocimiento, la experiencia
y la ciencia.\\

Así, el criterio de cientificidad como criterio de demarcación se
basará fundamentalmente en la prueba de falsabilidad para una
teoría. Es decir, la comprobación en circunstancias precisas en las
que podría verse uno obligado a abandonar la teoría.\\
Una actitud científica debe afrontar este tipo de pruebas. Lo que pasa
con las teorías psicoanalíticas y marxistas es que tratan de evitar
este tipo de pruebas decisivas utilizando diversos procedimientos:
  1. Empleando una terminología abstracta y generalista que no se
     corresponda con hechos observables, pero que cumpla una función
     esencial en la teoría.
  2. Utilizando conceptos que permiten neutralizar observaciones
     capaces de contradecir e incluso refutar la teoría.
  3. Realizar una observación selectiva de datos o de hechos que sólo
     descubran y se describan en función de la teoría.

Las nociones de ambivalencia en psicoanálisis, de astucia de la razón
o de superación de la dialéctica en el marxismo, postulan
contradicciones, antítesis. Pero no crean problemas, ya que el
freudismo o marxismo se refuerzan con ellas. Estas teoría no pueden
ser refutadas por la evidencia de una incoherencia o de un
conflicto. Lo que no va en sentido de la teoría queda excluido.\\
Se trata de la ausencia de distanciamiento crítico, típico de la
creencia, de la ideología, de la fe, etc. y que inmuniza a la teoría
en la que se cree haciéndola infalible. De ahí el dogmatismo que se
refuerza por la habilidad para interpretarlo todo siempre en la
dirección ortodoxa.

*** Falsibilidad y contrastabilidad
El criterio de la demarcación de Popper es la falsabilidad,
refutabilidad o contrastabilidad de las teorías. Se trata de la
alternativa al principio positivista de verificabilidad y a la
metodología induccionista. La falsabilidada supone:
  1. Un modo concreto de entender la ciencia empírica al que debe
     responder a tal criterio.
  2. Un modo de entender el valor de la epistemología desde la que
     habrá que comprender la función de tal criterio.

En cuanto al *criterio de delimitación* de los enunciados científicos
de los no científicos, hay dos aspectos a tener en cuenta: su carácter
propiamente empírico y su carácter evolutivo.\\
El *carácter empírico* dela ciencia implica que los enunciados
científicos nos proporcionan información sobre la experiencia y que
son capaces de explicar la experiencia.\\
El *carácter evolutivo* de la ciencia implica también deos notas de los
enunciados científicos: Que tienen un carácter hipotético, i.e., no
tienen una validez definitiva, y que tienen un carácter progresivo,
i.e., que suponen un aumento real de nuestro conocimiento.\\

La fasabilidad, como norma metodológica, hará referencia a la
estructura lógica de los enunciados científicos y, por otra, a los
procedimientos de la investigación científica —a las reglas
metodológicas que se utilizan para manejar enunciados científicos. \\
Afirmar que una teoría pertenece a la ciencia empírica es afirmar algo
acerca de algo que no es ni tautológica —que no afirma nada—, ni
contradictoria —lo afirma todo—, ni metafísica —afirma algo que no
puede ser comprobado en la experiencia.\\
Enunciado científico es, pues, enunciado que afirma algo sobre la
experiencia. La forma de saberlo es contrastando el enunciado con la
experiencia.\\
El problema que surge es saber cómo se puede llevar a cabo esta
contrastación.\\

Una teoría científica no es directamente contrastable con la
experiencia, ya que esta es particular y concreta, mientras que la
teoría es universal y abstracta. Sin embargo, los enunciado básicos
—enunciados deducidos de una teoría que describen hechos de la
experiencia— sí pueden ser directamente comparados con la
experiencia.\\
*Contrastar una teoría* con la experiencia es deducir enunciados
singulares a partir de ella y verificar en la práctica estos
enunciados. \\
Pueden pasar dos cosas:
  1. Que los enunciados singulares sean refutados por la
     experiencia. La teoría queda también refutada.
  2. Que los enunciados singulares sean verificados por la
     experiencia. La teoría no queda verificada, sino solo probada
     provisionalmente.

Los enunciados teóricos sin enunciados universales, que comprenden
infinitos casos de enunciados particulares. La verdad de un enunciado
universal no se puede dar por la verdad de un enunciado particular.\\
De esta manera parece que la falsabilidad, como criterio de
demarcación, es útil para dar cuenta del carácter empírico de las
teorías empíricas.\\

Pero para llegar a identificar este primer aspecto del carácter
empírico de la ciencia con la falsibilidad de los enunciados
científicos se han llevado a cabo varias reducciones.\\
Solo podemos saber si un enunciado habla acerca de la experiencia si
habla acerca de hechos singulares, y si es posible que lo que afirma
acerca de hechos singulares sea falso.\\

Esto tiene como consecuencia una limitación empirista del concepto de
ciencia que deja fuera de la racionalidad científica a todo conjunto
de enunciados que no se refieran a experiencias o hechos. Se dejan
fuera los enunciados filosóficos y muchos enunciados metafísicos.\\
Sin embargo, los enunciados metafísicos, aunque no falsables, juegan
un papel importante en la ciencia, pero en la medida que, mediante la
evolución de la ciencia, lleguen a ser falsables.\\

La distinción entre falsabilidad y falsación se corresponde con la
distinción con la distinción entre el problema de la demarcación y el
problema del método de la ciencia.\\
Todo sistema empírica tiene que ser, además, falsable. Los enunciados
que satisfacen la condición de coherencia son incapaces de efectuar
discriminación alguna entre dos enunciados cualesquiera. Los que no
satisfacen la condición de falsabilidad no son capaces de efectuar
discriminación entre dos enunciados cualesquiera que pertenezcan a la
totalidad de todos los enunciados empíricos básicos posibles.

** La concepción de la ciencia
*** Enunciados básicos y teorías
El primer aspecto a determinar es la relación entre ciencia y
experiencia. La ciencia se concibe como un conjunto organizado de
enunciados. El problema de la relación entre la experiencia y la
ciencia se formulará como problema de las relaciones entre enunciados
teóricos y enunciados de hechos, i.e., entre teorías y enunciados
básicos.\\
Las teorías se caracterizan respecto de los enunciados básico por ser
falsables, y éstos respecto de a la teoría por ser sus posibles
falsadores. Lo relevante es el método de llevar a cabo la
contrastación entre unos y otros, el método de la falsación de la
teoría o de su sometimiento a falsación.\\

Contrastar la teoría será contrastar los enunciados teóricos con los
enunciados básicos. Pero esto no resuelve el problema del empirismo
lógico, el de la justificación del carácter empírico de los enunciados
básicos mismos, el problema de la relación entre lenguaje y
experiencia, a través de la relación entre enunciados y hechos y
experiencia de hechos. Este problema se desdobla en la epistemología
de Popper *en dos problemas*: El problema de la aceptación de
enunciados básicos para la falsación de una teoría y el problema de la
justificación de esa aceptación.

*** Aceptación de enunciados básicos
