#+LATEX_CLASS: article

# -*- mode: org; -*-
#+LATEX_CLASS_OPTIONS: [a4paper, 11pt, twocolumn, spanish]
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[margin=.75in]{geometry}
#+LATEX_HEADER: \setlength\parindent{0pt}

#+Title: Apuntes de Teoría del Conocimiento ii
#+SUBTITLE: IV La problemática del conocimiento histórico
#+AUTHOR: Jordi Serra

* Constitución del método hermenéutico como método del conocimiento histórico
** Hermenéutica teológica y hermenéutica filológica

A partir del renecimiento se hace necesario un *método hermenéutico*
en dos ámbitos culturales, el filológico y el teológico.\\

En el *ámbito filológico*, como instrumento para redescubrir la
filología clásica antigua. El sentido genuino de ésta se había vuelto
ambígua e inasequible al amodarse al mundo cristiano.

En el *ámbito teológico*, es necesaria para la autodefensa de la
comprensión reforista de la Biblia contra el ataque de los teólogos
tridentinos, sosteniendo que la comprensión de la Biblia debería
determinarse por la tradición dogmática de la Iglesia. Los
reformadores creían que su sentido genuino queda oculto por ella.\\

La hermenéutica intenta poner al descubierto el sentido original de
los textos mediante una serie de principio y reglas. La reflexión
sobre el procedimiento de la hermenéutica, deja de ser preceptiva y
plantea el problema de fondo de la comprensión. Este proceso se puede
caracterizar con cinco pasos:\\

La *idea luterana* de una comprensión de la Sagrada Escriutra, relación
circular entre totalidad e individualidad. Según Lutero, no hace falta
la tradición, ni tampoco una técnica especial para alcanzar la
adecuada comprensión de la Biblia. Es el conjunto el que debe guiar la
comprensión de cada pasaje individual. El conjunto sólo puede
aprehenderse cuando se ha llevado a cabo la comprensión literal de lo
individual. La comprensión de un texto debe realizarse a partir del
contexto, con sentido unitario del conjunto al que pertenece.\\

*Postulado de Ernesti*: Desvinculación de la hermenéutica y todo
dogmatismo y convertirse en un método puramente ceintífico. Para los
teólogos de la Reforma, la Sagrada Escritura es la palabra divinia
revelada. Esto introduce en su comprensión un dogmatismo
determinante. Para Ernesti, la cmprensión adecuada de la Biblia exige
el reconocimiento de una diversidad de autores y su carácter de libro
histórico.No debe haber diferencia entre la interpretación de lobros
sagrados y profanos y no debe haber más que una hermenéutica.\\

Los *filólogos humanistas* cultivan la idea de reconocer en los textos
clásicos verdaderos y genuinos modelos. El humanista quire comprender
a sus modelos para imitarlos y asemejarse a ellos. Esta relación
dogmático tuvo que relajarse para dejar sitio a una hermenéutica más
independiente.\\

La historia universal se convierte en el contexto en el que se muestra
el  verdadero  y  relativo  significado de  los  objetos  individuales
contextualemente. Comprender es preguntarse de como el autor ha llegdo
a decir lo que dice. Sólo a partir del todo ed la historia se entiende
plenamente cada  detalle. Ese todo  sólo puede entenderse  edsde estos
detalles.\\


Se entrelazan la evolución del método hermenéutico y el del
científico-natural. El método hermenéutico se apropia la objetividad y
la independencia de la actitud científico-natural respecto de la
tradición, a la Biblia y a los clásicos.\\
El método científico-natural se plantea con una tarea de labor de
interpretación, de desciframiento del libro de la naturaleza por la
influencia del principio hermenéutico de comprender por el contexto.

** El proyecto de Scheleiermacher de una hermenéutcia universal
*** El arte de evitar malentendidos
Scheleiermacher fue el primero en intentar fundamentar explícitamente
la teoría del método hermenéutico y un planteamiento reflexivo del
problema de la comprensión y sus condiciones. De tradición filológica
tomó conciencia a partir de traducir las obras de Platón y de estudios
del Nuevo Testamento, de la necesidad de corregir las diferencias de
los métodos interpretativos, con una hermenéutica universal, capaz de
preceptuar los principios generales y la metodología adecuada de la
justa comprensión.
#+begin_quote
La hermenéutico como arte de comprender no existe como una materia
general. Sólo tenemos una pluralidad de hermenéuticas especializadas.
#+end_quote

Se propone elaborar una hermenéutica centrada en el acto de
comprender, caracterizándola como un arte o técnica ed la
comprensión. Todo objeto de interpretación pertenece a la
hermenéutica. Comprender e un fenómeno autónomo particular en el que
intervienen elementos subjetivos y objetivos dentro de un proceso
regido por leyes propias y distinto de la explicación.\\
Tres aspectos relevantes de la hermenéutica:

El esfuerzo para comprender se produce cuando no existe una
comprensión inmediata, cada vez que puede darse un malentendido. Según
Spinoza, el recurso hermenéutico al contexto histórico sólo sería
preciso cuando el contenido de un texto resulta inconcebible —e.g. no
tendría sentido interpretar la geometria de Euclides segun constumbres
del momento histórico.\\
El punto de partida de la hermenéutica universal de Scheliermacher es
la idea de que la posibilidad del malentendido es universal. Por eso
también la define como el arte de evitar el malentendido.\\

Esto es así porque lo que se trata de comprender no es
fundamentalemnte la libertad de las palabras y su sentido objetivo,
sino la individualiad de una producción original, el pensamiento en el
individuo. Bajo esta sensibilidad de lo individual y concreto está la
actitud romántica que proclama una esencia común de la humanidad y una
mutua comprensión a través de ideas racionales.\\

En consecuencia, la hermenéutica es un comportamiento adivinatorio, un
entrar dentro de la constitución espiritual del autor. No bastan regla
objetivas de interpretación gramatical, sintácticas o lógicas. Sólo se
comprende adecuadamente retrocediendo hasta la génesis misma de las
ideas.

*** La comprensión como acto adivinatorio de congenialialidad

Esta definición de la hermenéutica como acto adivinatorio implica una
concepción particular edl objeto y del acot de comprender. El conjunto
de ideas que intentamos comprender como discurso o coo texto no
representan un contenido objetivo, sino una representación, una
consturccion estética. De aquí que la poseía pueda servir de
paradigma. Lo que se trata de comprender no es un pensamiento objetivo
común, sino un pensamiento individual, exteriorización de una esencia
individual. Por eso no se pueden proponerse reglas para este acto de
comprensión. La producción original es el acto creador del ingenio
productor del sentido, de los usos lingüísticos, los estilos
literarios, etc.\\

En Schleiermacher el modo de crear propio del artista genial
constituye el modelo de toda producción espiritual y de toda
comprensión recreadora e esa producción. No concible la interpretación
como la simple aplicación de determinadas reglas a textos para su
adecuada comprensión. Se trata de hacer una auténtica reconstrucción,
reproducción o experimentación por uno mismo del proceso mental
creativo que, en el autor, ha tenido como consecuencia la producción
del texto.\\
Cada acto de comprensión ha de suponer una inversión del acto creador
o una reconstrucción de la construcción por la que el que comprende
penetra, a través de las estructuras expresivas lingüísticas
(reconstrucción gramatical), en la vida del autor (reconstrucción
técnico-psicológica).

*** La fundamentación del método mediante una metafísica de la vida
En schleiermacher, lo que fundamenta una congeniadora es una
*metafísica de la vida* como vinculación previa a todas las
individualidades. Su presupueto metafísco es que cada individuo es una
manifestación del vivir total /cada cual lleva en sí algo de los
demás, lo que hace posible la adivinación por compparación con uno
mismo/. Cada individualidad es una manifestación concreta de la vida
universal, de modo que el intérprete participa de las mismas fuerzas
vivas que animan al autor. Es como si cada individuo llevara en sí
mismo algo de cada uno de los demás. Esto permite por vía de
comparación y de transposición el desarrollo de la comprensión
adivinatoria.\\

Desde esta metafísica de la vida, la individualidad del intérprete y
la del autor ya no se contrastan como dos hechos incomparables y
extraños, sino que ambos se han formado sobre la base de la naturaleza
humana común que hace posible la comunidad misma de los hombres en el
discurso y la comprensión.\\
En esta base común es la que nos permite comprender, desde nuestra
propia autoconciencia, no sólo las palabras y gestos del otro, sino
también su manera de ser.

*** El círculo hermenéutico
La comprensión se hace sobre la base de la totalidad de la vida, pues
cada creación no es sino un momento vital en el nexo total de la
vida. Esta totalidad no está dada de antemano a modo de canon
dogmático. Comprender es siempre *moverse en círculo*: un contante
retorno de las partes al todo y viceversa.\\

La reconstrucción y el carácter provisional de la tarea hermenéutica
se mueven en círculo entre un todo y sus partes. Sobre este movimiento
circular se apoya la pretensión metodológica del comprender y las
pautas o criterios que han de regularlo. Schleiermacher concreta
reglas de su hermenéutica metódica y distingue *dos métodos*, el
comparativo y el adiviniatorio, así como *dos formas de
interpretación*, la gramatical y la técnica.\\

Estos métodos y formas de interpretacioón se condicionan mutuamente,
de tal manera que ningún método existe sin el otro y ninguna de las
formas de interpretación tiene una preeminencia absoluta sobre las
otras.\\
El *método adivinatorio* es definido como intuición inmediata o
captación de la inmediatez del sentido del texto, únicamente posible
para un espíritu afín que comparte con el autor un sentimiento vivo.\\
El *método comparativo* indica un camino para la cmprensión de una
totalidad a través de una serie de conocimientos singulares y
contrastados entre sí.\\

Estos dos métodos tiene su aplicación concreta:\\
La *interpretación gramatical*, que es la objetiva. Está referida al
sentido objetivo de las palabrase e investiga la regularidades del
lenguaje y las posibilidades de sus formas de expresión, por lo que
presupone la participación de los intérpretes y el autor en un juego
de lenguaje común. Shcleiermacher caracteriza este primer modo como un
proceso negativo y general, en cuanto que señala los límites de la
reconstrucción.\\
La *interpretación técnica*, que es la subjetiva, también denominada
psicológica. Intenta captar positivamente lo individual y subjetio del
autor en el uso que hace de las palabras. Trata de comprender el valor
significativo de lo dicho. Ésta se situa en la esfera del pensamiento
o ámbito del proceso creador interno del autor.\\

Estas dos formas de interpretación con los dos métodos, tienen como
tarea común la reconstrucción de la unidad de la obra como unidad de
lo general (lenguaje común del escritor y el intérprete) y de lo
particular (lo individual). Sólo la reconstrucción de esta unidad
original es lo que determina el rango de objetividad. El objetivo no
es asignar motivos o causas a las intenciones edl autor, sino
reconstruir el pensamiento mismo ed otra persona a través de la
interpretación de su discurso.

*** Comprender el autor mejor de lo que él mismo se comprendió
La comprensión implica la reconstrucción de una
proeducción. Necesariamente aparecerán en éste proceso aspectos que
pudieron haber pasado desapercibidos para el autor
original. Comprendiendo las formas particulares en su nexo de
relaciones, las palabras en sus cambios semánticos, según el uso
lingüístico del autor, poemos decir que comprendemos mejor al autor de
lo que él mismo se había comprendido.\\

El círculo hermenéutico se está siempre ampliando, pues el conjunto de
todo es relativo y la integración de cada cosa en relaciones cada vez
mayores afecta también a su comprensión. La comprensión del intérprete
puede considerarse mejor, puesto que expresa una opinión frente una
realización de su contenido, enciarra un poca más de conocimiento.\\
El lenguaje es un campo expresivo y su importancia en la hermenéutica
que es que el interprete puede considerar sus textos como puros
fenómenos de expresión, al margen de sus pretensiones de verdad
(Gadamer).

*** Una contradicción insalvable
El gran problema de la hermenéutica de Schleiermacher es la
conciliación, en una hermenéutica general, las dos formas de
interpretación, gramatical y técnica. Sin conocerse sus obras tardías,
se pensaba que consideraba estas formas en pie de igualdad. Eso
planteaba el problema de cómo se podrían practicar ambas en el mismo
tiempo. Pero Schleiermacher decía que centrarse en la lengua común es
olvidar al escritor en su individualidad, mientras que comprender el
autor singular implica olvidar su lenguaje.\\

Esto es, o bien se percibe lo común, o bien se percibe lo singular. La
primera inerpretación sería objetiva: Se dirige al lenguaje común,
pero también negativa: fijaría los límites de la comprensión.\\
La segunda interpretación, sería técnica —por la cual se alcanza la
subjetividad del autor que usa la lengua como un instrumento de su
individualidad—, pero por otro lasdo sería positiva —alcanza el acto
de pensamiento que produce el discurso. Así que son excluyentes y
piden aptitudes distintas. En sus últimos escritos, caracteriza la
segunda interpretación como psicológica, pasando entonces los
elementos críticos al método comparativo.

** La aplicación del método hermenéutico al estudio de la historia
De la teoría de la hermenéutica de Schleiermacher, dos conclusiones:
  1. Que la perfección última de todo conocimiento, de toda
     intepretación está en la comprensión de la totalidad en la que se
     insertan las creaciones individuales.
  2. Que cada texto individual no posee un valor autónomo. Más bien un
     material mediador para el conocimiento de la totalidad.

     
*** El planteamiento de Hegel
Hegel hace una aplicación concreta de estas dos conclusiones en su
concepción idealista de la historia universal. Los principios básicos
de esta transposición son tes:\\
La *individualiad* sólo deermina en su significado propio desde el
conjunto. No puede, pues, haber otra historia que la historia
universal. A través del esfuerzo de los individuos, la historia camina
hacia una meta de plena autoconciencia y absoluta comprensión.\\
La *libertad* tiene su expresión completa y adecuada en la totalidad
histórica. Los individuos actúan insertos en ésta mecanicamente hacia
la meta final.\\
La *historia* es percibida como un contexto unitario si se la piensa
teleológicamente, aunque no se haya acabado. Esto es, desde la meta
final a la que se dirige. Hegel mantiene así la visión cristiana de la
historia como historia de la salvación, que se había secularizado en
las concepciones ilustradas para las que el final condiciona el
sentido de la historia.\\

Así, Hegel llena de contenido metafísico el principio hermenéutico de
que la comprensión de lo individual debe producirse por referencia a
la totalidad. Aboca una metafísica de la historia universal curo
sentido unitario depende de una hipotética meta final dogmáticamente
establecida.

*** La reacción de la Escuela historicista
La escuela histórica da respuesta a la concepción hegeliana con una
fundación hermenéutica de la historiografía. Sus principios son
tres:\\
La *investigación histórica concreta* es lo que puede conducir a una
comprensión histórica universal. La determinación de la historia
universal como contexto unitario de sentido no puede hacerse más que a
partir del etudio de sus momentos individuales.\\
No hay ningún *final* ni ningún *fuera de la historia* que le otorgue
dogmáticamente su sentido. No se puede desarrollar el pensamiento
histórico mientras pervivan los prejuicios clasiscistas, mientras se
piense la historia a la luz de un pasado o de un porvenir con el valor
de patrón modélico más allá de la historia.\\
La *Idea* o la libertad no encuentran su expresión absoluta en la
totalidad de la historia, sino que cada época tiene su propia
existencia y su propia perfección. La Idea sólo alcanza
representaciones parciales en cada momento histórico. A través del
cambio incesante de los destinos humanos, la plenitud y la
multiplicidad de lo humano se conuce a sí misma hacia una realidad
cada vez mayor.\\

Es decir, entre Hegel y la escuela histórica hay una diferencia
esencial en la aplicación historiográfica de la teoría
hermenéutica. Los autores de esta escuela no llenan el principio
hermnéutico con ningún contenido. Piensan en la totalidad de la
historia universal simplemente como la idea formal de la máxima
variedad y multiplicidad de lo humano. El sentido de la historia no
viene de fuera, está en sí misma.

*** La concepción de la historia de Rake
Para Hegel, el conocimiento de la historia universal equivale a la
plena autoconciencia del presente histórico del presente histórico
como momento del camino del espíritu hacia sí mismo. Este camino del
espíritu le confiere sentido a la historia universal. Conocer este
camino desde dentro es concer la totaliad de la historia.\\

Para Ranke esto es una pura especulación escatológica. La estructura
formal de la historia de Ranke tiene esots seis principios:\\
Cada momento de la historia tiene su valor y su perfección
propia. Esots momentos forman un nexo histórico. Lo que sigue
representa el efectto de lo que le ha precedido. Lo único que se
mantiene a través del cambio de los destinos humanos es la
productividad de la vida.\\
Llama a los momentos del nexo histórico ecenas de la libertad. Los
concibe como decisiones que dan forma a la historia.\\
Estas decisiones que van haciendo la historia no son, ni libertad
absoluta, ni puro movimiento mecánico predirigido. Son libertad frente
a la resistencia de la necesidad.\\
La necesidad es el poder de lo acaecido ya, y de los otros que actúan
en contra de la propia decisión. La necesidad es algo que precede al
comienzo de cualquier actividad, restingiendo la posibilidad y
excluyendo muchos objetivos como imposibles.\\
La necesitat no es una fuerza distinta de la decisión libre, sino que
procede de ella. Lo que ha devenido ya no se puede suprimir sin más,
sino que delimita el ámvito de toda nueva actividad emergente, y es
consecuencia de una actividad anerior.\\
Esta dialéctica de libertad y necesidad es lo que consituye el nexo
histórico. Al mantenerse acaecido ya como fundamento, condiciona la
nueva actividad y la vincula en la continuidad de un nexo. Lo que ha
sido ya consitutye un nexo de lo que será.\\

Lo que impulsa el deveneir histórico y le da una unidad no es la
sibjetividad de los individuos, sino decisiones históricas
recognocibles en sus efectos. La individualidad de los sujetos está
conformada por esas fuerzas históricas.\\
Lo que da sentido al acontecer no son las ideas o proyectos de los que
actúan, sino los juegos ed fuerzas resultantes ed las decisiones, que
porducen continuidad.\\

Presupuestos aprióricos:\\
La historia es un curso acumulativo imposible de reconstruir
apriorísticamente. Luego, el supuesto de que la historia es un todo,
aunque no esté completo. Acumular implica un baremo en base al que se
reúnen acontecimientos heterogéneos. Un baremo a priori que guía su
reunión desde el principio. Por tanto la idea de la unidad de la
historia no es independiente de una comprensión de contenido.\\
Ranke rechaza el postulado pariórico de un telos que se pudiera
descubrir fuera de la historia, o de un plan subyacente al devenir
histórico. Ninguna necesidad a priori domina la historia. Pero la
estuctura del nexo histórico es pensada teleológicamente. Se mantiene
como objetivo orientador de la continuidad histórica y artífice de su
unidad. El éxito es lo que permito acumular. Que algo triunfe o
fracase decide sobre el sentido de esta acción. Además, el éxito o
fracaso hace que nexos completos de hechos y acontecimientos queden
llenos de sentido o carentes de él. Los elementos del nexo histórico
se determinan pues, desde una teleología encubierta que los reúne y
excluye lo que no tiene significado.\\
El conocimiento histórico no es un mero conocimiento empírico de datos
históricos. Es una condición de la conciencia histórica misma. La
condición de existencia misma de una historia es la continuidad de la
cultura (memoria). La ciencia histórica misma no es otra cosa que el
intento de comprenderse a sí misma como unidad histórica
universal. Sus ser está determinado por el saberse. El hundimiento de
nuestra tradición cultural occidental, que acabaría con su
continuidad, no significaría una catástrofe dentro de la historia
universal, sino el fin mismo de esta historia (por pérdida de
memoria).\\
La continuidad es la esencia misma de la historia. Al rechazar un
telos escatológico, fuera de la historia, como soporte del proceso y
del sentido histórico, se ve obligado a referir el sentido limitado de
los momentos históricos a un espíritu divino al que las cosas le
serían conocidas en su pleno cumplimiento. Los fenómenos de la vida
histórica se entenderán en la comprensión como manifestaciones ed la
vida total, de la divinidad.\\
Y la última, el conocimiento es más que un conocimiento humano. A
través de él se participa en la vida misma de la divinidad. Se realiza
por participación inmediata: /Lo que interesa al histriador no es
referir a la realidad a concepto, sino llegar al punto en que la vida
piensa y el pensamiento vive/.

* El intento de dilthey de una fundamentación hermenéutica de las ciencias del espíritu

