#+LATEX_CLASS: article

# -*- mode: org; -*-
#+LATEX_CLASS_OPTIONS: [a4paper, 11pt, twocolumn, spanish]
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[margin=.75in]{geometry}
#+LATEX_HEADER: \setlength\parindent{0pt}

#+Title: Apuntes de Teoría del Conocimiento ii
#+SUBTITLE: IV La problemática del conocimiento histórico
#+AUTHOR: Jordi Serra

* Constitución del método hermenéutico como método del conocimiento histórico
** Hermenéutica teológica y hermenéutica filológica

A partir del renacimiento se hace necesario un *método hermenéutico*
en dos ámbitos culturales, el filológico y el teológico.\\

En el *ámbito filológico*, como instrumento para redescubrir la
filología clásica antigua. El sentido genuino de ésta se había vuelto
ambigua e inasequible al amoldarse al mundo cristiano.

En el *ámbito teológico*, es necesaria para la autodefensa de la
comprensión reformista de la Biblia contra el ataque de los teólogos
tridentinos, sosteniendo que la comprensión de la Biblia debería
determinarse por la tradición dogmática de la Iglesia. Los
reformadores creían que su sentido genuino queda oculto por ella.\\

La hermenéutica intenta poner al descubierto el sentido original de
los textos mediante una serie de principio y reglas. La reflexión
sobre el procedimiento de la hermenéutica, deja de ser preceptiva y
plantea el problema de fondo de la comprensión. Este proceso se puede
caracterizar con cinco pasos:\\

La *idea luterana* de una comprensión de la Sagrada Escritura, relación
circular entre totalidad e individualidad. Según Lutero, no hace falta
la tradición, ni tampoco una técnica especial para alcanzar la
adecuada comprensión de la Biblia. Es el conjunto el que debe guiar la
comprensión de cada pasaje individual. El conjunto sólo puede
aprehenderse cuando se ha llevado a cabo la comprensión literal de lo
individual. La comprensión de un texto debe realizarse a partir del
contexto, con sentido unitario del conjunto al que pertenece.\\

*Postulado de Ernesti*: Desvinculación de la hermenéutica y todo
dogmatismo y convertirse en un método puramente científico. Para los
teólogos de la Reforma, la Sagrada Escritura es la palabra divina
revelada. Esto introduce en su comprensión un dogmatismo
determinante. Para Ernesti, la cmprensión adecuada de la Biblia exige
el reconocimiento de una diversidad de autores y su carácter de libro
histórico.No debe haber diferencia entre la interpretación de libros
sagrados y profanos y no debe haber más que una hermenéutica.\\

Los *filólogos humanistas* cultivan la idea de reconocer en los textos
clásicos verdaderos y genuinos modelos. El humanista quiere comprender
a sus modelos para imitarlos y asemejarse a ellos. Esta relación
dogmático tuvo que relajarse para dejar sitio a una hermenéutica más
independiente.\\

La historia universal se convierte en el contexto en el que se muestra
el  verdadero  y  relativo  significado de  los  objetos  individuales
contextualmente. Comprender es preguntarse de como el autor ha llegado
a decir lo que dice. Sólo a partir del todo ed la historia se entiende
plenamente cada  detalle. Ese todo  sólo puede entenderse  desde estos
detalles.\\


Se entrelazan la evolución del método hermenéutico y el del
científico-natural. El método hermenéutico se apropia la objetividad y
la independencia de la actitud científico-natural respecto de la
tradición, a la Biblia y a los clásicos.\\
El método científico-natural se plantea con una tarea de labor de
interpretación, de desciframiento del libro de la naturaleza por la
influencia del principio hermenéutico de comprender por el contexto.

** El proyecto de Scheleiermacher de una hermenéutcia universal
*** El arte de evitar malentendidos
Scheleiermacher fue el primero en intentar fundamentar explícitamente
la teoría del método hermenéutico y un planteamiento reflexivo del
problema de la comprensión y sus condiciones. De tradición filológica
tomó conciencia a partir de traducir las obras de Platón y de estudios
del Nuevo Testamento, de la necesidad de corregir las diferencias de
los métodos interpretativos, con una hermenéutica universal, capaz de
preceptuar los principios generales y la metodología adecuada de la
justa comprensión.
#+begin_quote
La hermenéutico como arte de comprender no existe como una materia
general. Sólo tenemos una pluralidad de hermenéuticas especializadas.
#+end_quote

Se propone elaborar una hermenéutica centrada en el acto de
comprender, caracterizándola como un arte o técnica ed la
comprensión. Todo objeto de interpretación pertenece a la
hermenéutica. Comprender e un fenómeno autónomo particular en el que
intervienen elementos subjetivos y objetivos dentro de un proceso
regido por leyes propias y distinto de la explicación.\\
Tres aspectos relevantes de la hermenéutica:

El esfuerzo para comprender se produce cuando no existe una
comprensión inmediata, cada vez que puede darse un malentendido. Según
Spinoza, el recurso hermenéutico al contexto histórico sólo sería
preciso cuando el contenido de un texto resulta inconcebible —e.g. no
tendría sentido interpretar la geometría de Euclides según costumbres
del momento histórico.\\
El punto de partida de la hermenéutica universal de Scheliermacher es
la idea de que la posibilidad del malentendido es universal. Por eso
también la define como el arte de evitar el malentendido.\\

Esto es así porque lo que se trata de comprender no es
fundamentalemnte la libertad de las palabras y su sentido objetivo,
sino la individualidad de una producción original, el pensamiento en el
individuo. Bajo esta sensibilidad de lo individual y concreto está la
actitud romántica que proclama una esencia común de la humanidad y una
mutua comprensión a través de ideas racionales.\\

En consecuencia, la hermenéutica es un comportamiento adivinatorio, un
entrar dentro de la constitución espiritual del autor. No bastan regla
objetivas de interpretación gramatical, sintácticas o lógicas. Sólo se
comprende adecuadamente retrocediendo hasta la génesis misma de las
ideas.

*** La comprensión como acto adivinatorio de congenialialidad

Esta definición de la hermenéutica como acto adivinatorio implica una
concepción particular edl objeto y del acto de comprender. El conjunto
de ideas que intentamos comprender como discurso o como texto no
representan un contenido objetivo, sino una representación, una
construcción estética. De aquí que la poseía pueda servir de
paradigma. Lo que se trata de comprender no es un pensamiento objetivo
común, sino un pensamiento individual, exteriorización de una esencia
individual. Por eso no se pueden proponerse reglas para este acto de
comprensión. La producción original es el acto creador del ingenio
productor del sentido, de los usos lingüísticos, los estilos
literarios, etc.\\

En Schleiermacher el modo de crear propio del artista genial
constituye el modelo de toda producción espiritual y de toda
comprensión recreadora e esa producción. No concibe la interpretación
como la simple aplicación de determinadas reglas a textos para su
adecuada comprensión. Se trata de hacer una auténtica reconstrucción,
reproducción o experimentación por uno mismo del proceso mental
creativo que, en el autor, ha tenido como consecuencia la producción
del texto.\\
Cada acto de comprensión ha de suponer una inversión del acto creador
o una reconstrucción de la construcción por la que el que comprende
penetra, a través de las estructuras expresivas lingüísticas
(reconstrucción gramatical), en la vida del autor (reconstrucción
técnico-psicológica).

*** La fundamentación del método mediante una metafísica de la vida
En schleiermacher, lo que fundamenta una congeniadora es una
*metafísica de la vida* como vinculación previa a todas las
individualidades. Su presupuesto metafísico es que cada individuo es una
manifestación del vivir total /cada cual lleva en sí algo de los
demás, lo que hace posible la adivinación por comparación con uno
mismo/. Cada individualidad es una manifestación concreta de la vida
universal, de modo que el intérprete participa de las mismas fuerzas
vivas que animan al autor. Es como si cada individuo llevara en sí
mismo algo de cada uno de los demás. Esto permite por vía de
comparación y de transposición el desarrollo de la comprensión
adivinatoria.\\

Desde esta metafísica de la vida, la individualidad del intérprete y
la del autor ya no se contrastan como dos hechos incomparables y
extraños, sino que ambos se han formado sobre la base de la naturaleza
humana común que hace posible la comunidad misma de los hombres en el
discurso y la comprensión.\\
En esta base común es la que nos permite comprender, desde nuestra
propia autoconciencia, no sólo las palabras y gestos del otro, sino
también su manera de ser.

*** El círculo hermenéutico
La comprensión se hace sobre la base de la totalidad de la vida, pues
cada creación no es sino un momento vital en el nexo total de la
vida. Esta totalidad no está dada de antemano a modo de canon
dogmático. Comprender es siempre *moverse en círculo*: un contante
retorno de las partes al todo y viceversa.\\

La reconstrucción y el carácter provisional de la tarea hermenéutica
se mueven en círculo entre un todo y sus partes. Sobre este movimiento
circular se apoya la pretensión metodológica del comprender y las
pautas o criterios que han de regularlo. Schleiermacher concreta
reglas de su hermenéutica metódica y distingue *dos métodos*, el
comparativo y el adivinatorio, así como *dos formas de
interpretación*, la gramatical y la técnica.\\

Estos métodos y formas de interpretación se condicionan mutuamente,
de tal manera que ningún método existe sin el otro y ninguna de las
formas de interpretación tiene una preeminencia absoluta sobre las
otras.\\
El *método adivinatorio* es definido como intuición inmediata o
captación de la inmediatez del sentido del texto, únicamente posible
para un espíritu afín que comparte con el autor un sentimiento vivo.\\
El *método comparativo* indica un camino para la comprensión de una
totalidad a través de una serie de conocimientos singulares y
contrastados entre sí.\\

Estos dos métodos tiene su aplicación concreta:\\
La *interpretación gramatical*, que es la objetiva. Está referida al
sentido objetivo de las palabras e investiga la regularidades del
lenguaje y las posibilidades de sus formas de expresión, por lo que
presupone la participación de los intérpretes y el autor en un juego
de lenguaje común. Shcleiermacher caracteriza este primer modo como un
proceso negativo y general, en cuanto que señala los límites de la
reconstrucción.\\
La *interpretación técnica*, que es la subjetiva, también denominada
psicológica. Intenta captar positivamente lo individual y sujeto del
autor en el uso que hace de las palabras. Trata de comprender el valor
significativo de lo dicho. Ésta se sitúa en la esfera del pensamiento
o ámbito del proceso creador interno del autor.\\

Estas dos formas de interpretación con los dos métodos, tienen como
tarea común la reconstrucción de la unidad de la obra como unidad de
lo general (lenguaje común del escritor y el intérprete) y de lo
particular (lo individual). Sólo la reconstrucción de esta unidad
original es lo que determina el rango de objetividad. El objetivo no
es asignar motivos o causas a las intenciones edl autor, sino
reconstruir el pensamiento mismo ed otra persona a través de la
interpretación de su discurso.

*** Comprender el autor mejor de lo que él mismo se comprendió
La comprensión implica la reconstrucción de una
producción. Necesariamente aparecerán en éste proceso aspectos que
pudieron haber pasado desapercibidos para el autor
original. Comprendiendo las formas particulares en su nexo de
relaciones, las palabras en sus cambios semánticos, según el uso
lingüístico del autor, podemos decir que comprendemos mejor al autor
de lo que él mismo se había comprendido.\\

El círculo hermenéutico se está siempre ampliando, pues el conjunto de
todo es relativo y la integración de cada cosa en relaciones cada vez
mayores afecta también a su comprensión. La comprensión del intérprete
puede considerarse mejor, puesto que expresa una opinión frente una
realización de su contenido, encierra un poca más de conocimiento.\\
El lenguaje es un campo expresivo y su importancia en la hermenéutica
que es que el interprete puede considerar sus textos como puros
fenómenos de expresión, al margen de sus pretensiones de verdad
(Gadamer).

*** Una contradicción insalvable
El gran problema de la hermenéutica de Schleiermacher es la
conciliación, en una hermenéutica general, las dos formas de
interpretación, gramatical y técnica. Sin conocerse sus obras tardías,
se pensaba que consideraba estas formas en pie de igualdad. Eso
planteaba el problema de cómo se podrían practicar ambas en el mismo
tiempo. Pero Schleiermacher decía que centrarse en la lengua común es
olvidar al escritor en su individualidad, mientras que comprender el
autor singular implica olvidar su lenguaje.\\

Esto es, o bien se percibe lo común, o bien se percibe lo singular. La
primera interpretación sería objetiva: Se dirige al lenguaje común,
pero también negativa: fijaría los límites de la comprensión.\\
La segunda interpretación, sería técnica —por la cual se alcanza la
subjetividad del autor que usa la lengua como un instrumento de su
individualidad—, pero por otro lado sería positiva —alcanza el acto
de pensamiento que produce el discurso. Así que son excluyentes y
piden aptitudes distintas. En sus últimos escritos, caracteriza la
segunda interpretación como psicológica, pasando entonces los
elementos críticos al método comparativo.

** La aplicación del método hermenéutico al estudio de la historia
De la teoría de la hermenéutica de Schleiermacher, dos conclusiones:
  1. Que la perfección última de todo conocimiento, de toda
     interpretación está en la comprensión de la totalidad en la que
     se insertan las creaciones individuales.
  2. Que cada texto individual no posee un valor autónomo. Más bien un
     material mediador para el conocimiento de la totalidad.

     
*** El planteamiento de Hegel
Hegel hace una aplicación concreta de estas dos conclusiones en su
concepción idealista de la historia universal. Los principios básicos
de esta transposición son tes:\\
La *individualiad* sólo determina en su significado propio desde el
conjunto. No puede, pues, haber otra historia que la historia
universal. A través del esfuerzo de los individuos, la historia camina
hacia una meta de plena autoconciencia y absoluta comprensión.\\
La *libertad* tiene su expresión completa y adecuada en la totalidad
histórica. Los individuos actúan insertos en ésta mecánicamente hacia
la meta final.\\
La *historia* es percibida como un contexto unitario si se la piensa
teleológicamente, aunque no se haya acabado. Esto es, desde la meta
final a la que se dirige. Hegel mantiene así la visión cristiana de la
historia como historia de la salvación, que se había secularizado en
las concepciones ilustradas para las que el final condiciona el
sentido de la historia.\\

Así, Hegel llena de contenido metafísico el principio hermenéutico de
que la comprensión de lo individual debe producirse por referencia a
la totalidad. Aboca una metafísica de la historia universal curo
sentido unitario depende de una hipotética meta final dogmáticamente
establecida.

*** La reacción de la Escuela historicista
La escuela histórica da respuesta a la concepción hegeliana con una
fundación hermenéutica de la historiografía. Sus principios son
tres:\\
La *investigación histórica concreta* es lo que puede conducir a una
comprensión histórica universal. La determinación de la historia
universal como contexto unitario de sentido no puede hacerse más que a
partir del etudio de sus momentos individuales.\\
No hay ningún *final* ni ningún *fuera de la historia* que le otorgue
dogmáticamente su sentido. No se puede desarrollar el pensamiento
histórico mientras pervivan los prejuicios clasicistas, mientras se
piense la historia a la luz de un pasado o de un porvenir con el valor
de patrón modélico más allá de la historia.\\
La *Idea* o la libertad no encuentran su expresión absoluta en la
totalidad de la historia, sino que cada época tiene su propia
existencia y su propia perfección. La Idea sólo alcanza
representaciones parciales en cada momento histórico. A través del
cambio incesante de los destinos humanos, la plenitud y la
multiplicidad de lo humano se conduce a sí misma hacia una realidad
cada vez mayor.\\

Es decir, entre Hegel y la escuela histórica hay una diferencia
esencial en la aplicación historiográfica de la teoría
hermenéutica. Los autores de esta escuela no llenan el principio
hermenéutico con ningún contenido. Piensan en la totalidad de la
historia universal simplemente como la idea formal de la máxima
variedad y multiplicidad de lo humano. El sentido de la historia no
viene de fuera, está en sí misma.

*** La concepción de la historia de Rake
Para Hegel, el conocimiento de la historia universal equivale a la
plena autoconciencia del presente histórico del presente histórico
como momento del camino del espíritu hacia sí mismo. Este camino del
espíritu le confiere sentido a la historia universal. Conocer este
camino desde dentro es conocer la totalidad de la historia.\\

Para Ranke esto es una pura especulación escatológica. La estructura
formal de la historia de Ranke tiene estos seis principios:\\
Cada momento de la historia tiene su valor y su perfección
propia. Esots momentos forman un nexo histórico. Lo que sigue
representa el efecto de lo que le ha precedido. Lo único que se
mantiene a través del cambio de los destinos humanos es la
productividad de la vida.\\
Llama a los momentos del nexo histórico escenas de la libertad. Los
concibe como decisiones que dan forma a la historia.\\
Estas decisiones que van haciendo la historia no son, ni libertad
absoluta, ni puro movimiento mecánico predirigido. Son libertad frente
a la resistencia de la necesidad.\\
La necesidad es el poder de lo acaecido ya, y de los otros que actúan
en contra de la propia decisión. La necesidad es algo que precede al
comienzo de cualquier actividad, restringiendo la posibilidad y
excluyendo muchos objetivos como imposibles.\\
La necesidad no es una fuerza distinta de la decisión libre, sino que
procede de ella. Lo que ha devenido ya no se puede suprimir sin más,
sino que delimita el ámbito de toda nueva actividad emergente, y es
consecuencia de una actividad anterior.\\
Esta dialéctica de libertad y necesidad es lo que constituye el nexo
histórico. Al mantenerse acaecido ya como fundamento, condiciona la
nueva actividad y la vincula en la continuidad de un nexo. Lo que ha
sido ya constituye un nexo de lo que será.\\

Lo que impulsa el devenir histórico y le da una unidad no es la
subjetividad de los individuos, sino decisiones históricas
recognocibles en sus efectos. La individualidad de los sujetos está
conformada por esas fuerzas históricas.\\
Lo que da sentido al acontecer no son las ideas o proyectos de los que
actúan, sino los juegos ed fuerzas resultantes ed las decisiones, que
producen continuidad.\\

Presupuestos aprióricos:\\
La historia es un curso acumulativo imposible de reconstruir
apriorísticamente. Luego, el supuesto de que la historia es un todo,
aunque no esté completo. Acumular implica un baremo en base al que se
reúnen acontecimientos heterogéneos. Un baremo a priori que guía su
reunión desde el principio. Por tanto la idea de la unidad de la
historia no es independiente de una comprensión de contenido.\\
Ranke rechaza el postulado apriórico de un /telos/ que se pudiera
descubrir fuera de la historia, o de un plan subyacente al devenir
histórico. Ninguna necesidad a priori domina la historia. Pero la
estructura del nexo histórico es pensada teleológicamente. Se mantiene
como objetivo orientador de la continuidad histórica y artífice de su
unidad. El éxito es lo que permito acumular. Que algo triunfe o
fracase decide sobre el sentido de esta acción. Además, el éxito o
fracaso hace que nexos completos de hechos y acontecimientos queden
llenos de sentido o carentes de él. Los elementos del nexo histórico
se determinan pues, desde una teleología encubierta que los reúne y
excluye lo que no tiene significado.\\
El conocimiento histórico no es un mero conocimiento empírico de datos
históricos. Es una condición de la conciencia histórica misma. La
condición de existencia misma de una historia es la continuidad de la
cultura (memoria). La ciencia histórica misma no es otra cosa que el
intento de comprenderse a sí misma como unidad histórica
universal. Sus ser está determinado por el saberse. El hundimiento de
nuestra tradición cultural occidental, que acabaría con su
continuidad, no significaría una catástrofe dentro de la historia
universal, sino el fin mismo de esta historia (por pérdida de
memoria).\\
La continuidad es la esencia misma de la historia. Al rechazar un
telos escatológico, fuera de la historia, como soporte del proceso y
del sentido histórico, se ve obligado a referir el sentido limitado de
los momentos históricos a un espíritu divino al que las cosas le
serían conocidas en su pleno cumplimiento. Los fenómenos de la vida
histórica se entenderán en la comprensión como manifestaciones ed la
vida total, de la divinidad.\\
Y la última, el conocimiento es más que un conocimiento humano. A
través de él se participa en la vida misma de la divinidad. Se realiza
por participación inmediata: /Lo que interesa al historiador no es
referir a la realidad a concepto, sino llegar al punto en que la vida
piensa y el pensamiento vive/.


* El intento de Dilthey de una fundamentación hermenéutica de las ciencias del espíritu
** Introducción
Wilhelm Dilthey es el fundador del historicismo. Su obre influye en
autores posteriores —Heidegger, Weber, etc.\\

El contexto en el que se desarrolla la obra de Dilthey es el de la
decadencia de los grandes sistemas metafísicos del pasado y el
consiguiente auge del espíritu positivista. Dilthey intenta
fundamentar las ciencias del espíritu o ciencias históricas —en
situación precaria respecto de las ciencias de la naturalza— mediante
un trabajo de complementación de la crítica kantiana de acuerdo con la
analogía /razón pura/-/razón histórica/. Dilthey, al mismo tiempo que
sostener una tarea de fundamentación gnoseológica de las ciencias del
espíritu, advierte de la dificultad de sistematizar las expresiones
históricas en la unidad de una historia que pueda ser entendida como
ciencia unversalmente válida sin recurrir a teorías filosóficas de
base, apoyándose sólo en actitudes apropiadas frente al material
histórico mismo.\\
Su solución pasa por distinguir entre las operaciones cognoscitivas
básicas de *explicación y comprensión*.\\
La explicación opera en las ciencias naturales. La comprensión en las
ciencias del espíritu, o ciencias hermenéuticas.\\


Su concepción de la comprensión deriva hacia un intento de
fundamentación psicológica que será fuertemente contestado por
Husserl.\\
Para D., el yo en el que se fundamente el conocimiento histórico, se
constituye como experiencia o conexión dinámica de ámbitos
psíquicos. Así, queda abierto el problema de coniciliar la dimensión
subjetiva del mundo histórico con la exigencia de objetividad
científica que conlleva el empleo de un método de investigación
científica.\\
Para resolverlo, identifica mundo humano e historia. Esto es, el plano
subjetivo del conocimiento histórico con las formas objetivas del
espíritu. Así, la validez de los criterios de interpretación no puede
basarse en principios absolutos, externos a la finitud e historicidad
del hombre. La pretensión de la fundación epistemológica que trate de
constituir las ciencias del espíritu como explicación sistemática y
universal es ilusoria.
 
** El problema epistemológico de las ciencias históricas como crítica de la razón histórica

*** Una aplicación de la crítica kantiana
Ranke representa la continuación del espíritu romántico y el esfuerzo
por hacerlo compatible con la investigación empírica. Es inevitable
una ambivalencia entre idealismo y pensamiento empírico que se
agudizará en Dithley, que se propone encontrar un fundamento
epistemológico sólido para las concepciones teóricas que Ranke había
mantenido frente al idealismo de Hegel. Cree que se puede hacer
positivamente completando la crítica kantiana de la razón pura con una
crítica de la razón histórica.\\
Los argumentos de base de Dithley son:\\
Primero que la crítica kantiana mostraba al mismo tiempo la
imposibilidad de la metafísica como ciencia y las condiciones a priori
del conocimiento científico, y respondía a la pregunta de cómo es
posible una ciencia natural pura. Después de la crítica kantiana, el
idealismo de Hegel había involucrado el mundo de la historia en una
nueva metafísica de la razón. Esta metafísica, para la escuela
histórica, se interpreta como un dogmatismo tan inaceptable como la
metafísica clásica para Kant. Luego, era lógico buscar fundamentación
científica del conocimiento físico, según la analogía razón pura/razón
histórica.\\
Segundo, la caída de la metafísica hegeliana queda destruida la
correspondencia natural e inmediata entre logos y ser. El conocimiento
es interpretación. Hegel fue el máximo y último representante de la
filosofía racionalista iniciada en Grecia. Con él acaba el dogmatismo
metafísico de la verdad como copia de la realidad. La crítica kantiana
justificaba el conocimiento de la Física, no como representación de la
cosa en sí, sino como construcción interpretativa y categorial. Es
lógico adoptar el nominalismo kantiano para rechazar definitivamente
la hegeliana construcción a priori de la historia universal.

*** Conocimiento científico-natural y experiencia histórica
El problema epistemológico de Dithley es como se puede convertir en
ciencia la experiencia histórica; cuales son las categorías históricas
que pueden fundamentar el conocimiento de las ciencias del espíritu.\\
Pero el conocimiento impone limitaciones a la analogía:\\
Primero, no es posible la simple aplicación de la filosofía
trascendental kantiana en el ámbito del conocimiento histórico, como
pretendían las escuelas neokantianas. Para estos, la filosofía
trascendental proporciona el análisis categorial de todo objeto de
conocimiento. Pero esto es otro dogmatismo inaceptable, porque la
experiencia es, en el ámbito histórico, algo fundamentalmente distinto
al conocimiento físico.\\
El conocimiento científico-natural se produce en base a comprobaciones
empíricas verificables de hechos de experiencia común. El conocimiento
histórico no se produce sobre hechos de experiencia que pueden ser
incluidos en categorías lógicas universales, sino que su base es la
experiencia histórica que es un proceso vital. Es una constatación de
hechos. El modelo del conocimiento histórico es la peculiar fusión de
recuerdo y expectativa en un todo llamado experiencia, que se adquiere
con la experiencia.\\

Segundo y último, el planteamiento epistemológico de las ciencias
históricas debe tener un comienzo distinto al comienzo kantiano. No
empieza con la relación de nuestros conceptos con un mundo externo o
cosa en sí. El mundo histórico es un mundo completamente conformado
por el espíritu humano. Dithley subraya la importancia epistemológica
del mundo de la historia por encima del conocimiento
científico-natural. El /cogito/ no es el punto de partida radical,
previo a la posibilidad de hacer ciencia está el yo como ser
histórico. En el caso de la ciencia histórica significa que el que
investiga la historia es el que la hace.\\

El problema epistemológico debe plantearse de una forma
fundamentalmente diferente. Dithley no pudo desprenderse de la teoría
del conocimiento tradicional. Su punto de partida, la interiorización
de las vivencias, no podía tender el puente hacia las realidades
históricas, porque las grandes realidades históricas —sociedad y
estado— son siempre en realidad determinantes previos de toda
vivencia.\\
La autorreflexión no son hechos primarios, y no bastan como base para
le problema hermenéutico. No es la historia que nos pertenece, somos
nosotros los que pertenecemos a la historia. Mucho antes de que
nosotros nos comprendamos a nosotros mismos en la reflexión, nos
estamos comprendiendo ya de una manera autoevidente en la familia, la
sociedad y el estado en que vivimos. La lente de la subjetividad es un
espejo deformante. La autorreflexión del individuo no es más que una
chispa en la corriente cerrada de la vida histórica. Por eso, los
prejuicios de un individuo son la realidad histórica de su ser.


*** Vivencias y estructura como fundamentos psicológicos
Dithley intenta desarrollar su proyecto partiendo de esta
característica del conocimiento histórico. Investiga cómo el individuo
adquiere un contexto vital, e intenta elaborar los conceptos
constitutivos capaces de sustentar el contexto histórico y su
conocimiento.\\
Es consciente que sólo obtendrá un fundamento psicológico de alcance
limitado: La historia no es el conjunto de nexos vividos por el
individuo accesibles vivencialmente a los otros. Su problema es saber
como se eleva la experiencia del individuo y su conocimiento a
experiencia histórica.\\
Los conceptos pueden que fundamentar, al mismo tiempo, el contexto
histórico y su conocimiento son:\\
Primero, el *concepto de vivencia*, que define el conocimiento
histórico. La identidad de sujeto y objeto tiene realidad palpable en
la identidad. El sujeto se conoce a sí mismo en el objeto, que es obra
suya. No hay distinción entre acto y contenido. Dithley busca cómo se
configura un nexo a partir de este elemento, inmediatamente cierto, y
cómo es posible un conocimiento de tal nexo.\\

Segundo y último, el *concepto de estructura*. Los nexos psicológicos
de vivencias deben ser distintos de los nexos causales del acontecer
natural. La noción de estructura sirve para expresar lo vivido de
estos nexos psicológicos. La estructura no expresa relaciones basadas
en la sucesión temporal, sino configuradas internamente. Es un decurso
vital que forma una unidad sobre la base del significado de un
conjunto de vivencias. Como tal significado unitario se ofrece al
individuo o puede ser revivido en el conocimiento biográfico de los
demás. La estructura se forma del mismo modo que se constituye la
forma sensible de una melodía: no desde la mera sucesión temporal de
tonos pasajeros, sino desde los motivos musicales que determinan la
unidad de su forma.\\

*** De lo psicológico a lo hermenéutico

En este planteamiento está presente la ambivalencia entre el todo y
las partes. Dithley ha desarrollado teóricamente la afirmación de
Ranke de que no existe un sujeto universal, sino sólo individuos
históricos. La idealidad del significado no puede asignarse a un
sujeto trascendental, sino que surge de la realidad histórica de la
vida. Es la vida la que al desarrollarse conforma unidades
comprensibles, y el individuo comprende estas unidades como tales. El
nexo estructural de la vida, como el de un texto, está determinado por
una cierta relación entre todas sus partes. Cada parte expresa algo
del todo de la vida. Tiene una significación en el todo, al igual que
su propio significado está determinado desde este todo.\\

Hasta ahora, Dithley sólo ha encontrado el nexo propio de la
existencia vital del individuo. Para fundamentar científicamente el
conocimiento histórico, necesita un nexo o significado general que no
es vivido ni experimentado por ningún individuo. Esto supone, a pesar
del rechazo del idealismo de Hegel, poner sujetos lógicos en lugar de
los sujetos reales. El problema es equivalente a pasar de la
fundamentación psicológica a la fundamentación hermenéutica de las
ciencias del espíritu: El problema de la historia no es cómo puede ser
vivido y conocido el nexo general biográfico, sino cómo pueden ser
cognoscibles aquellos nexos que ningún individuo a podido experimentar.\\

La transformación de lo psicológico en hermenéutica es llevada a cabo
mediante los siguientes tres pasos.

Primero, el conocimiento histórico como comprensión. Mediante el
concepto de comprensión Dithley consigue diferenciar las relaciones
del mundo espiritual, ciencias del espíritu, respecto de las
relaciones causales de las ciencias naturales. Pero en la expresión,
lo expresado aparece de manera distinto que la causa en el efecto. La
causa se sitúa más allá, en un ámbito de ser distinto, dualismo
metafísico. En la expresión, lo expresado está presente totalmente en
ella. No hay referencia a algo más allá donde se sitúa el sentido.\\

Segundo, La estructura vivencial como significado. La estructura de la
vida psíquica no es la mera consecuencia de factores causales. Es una
unidad vital comprensible en sí misma, que se expresa en cada una de
sus manifestaciones y puede ser comprendida desde ellas. Dithley
aprende de Husserl esta distinción entre estructura, o significado
general, y nexo causal. Para Husserl, la intencionalidad de la
conciencia no es sólo un hecho psicológico, sino una determinación
esencial de toda conciencia: La conciencia es siempre conciencia de
algo. El objeto intencional no es tampoco un componente psíquico, sino
unidad ideal, un significado general que sirve de referente. La
estructura o significado no está dado en la inmediatez de una
vivencia, pero tampoco es una derivación que se explica como un
conjunto de ellas. Las investigaciones de Husserl legitiman conceptos
como el de estructura y el de significado sin que tengan que ser
deducibles a partir de elementos. Pudiendo quedar como más originarios
que estos supuestos elementos a partir de los cuales deberían
construirse.

Tercero y última, la vida como origen de todo significado. Husserl
permite a Dithley una nueva fundamentación del concepto de lo dado. La
tarea no puede plantearse ya como derivación de nexos a partir de
vivencias atómicas para tratar de explicarlos desde ellas. La
consciencia está ya en los nexos, y tiene su ser propio en la
referencia a ellos. Pero la demostración husserliana de la idealidad
del significado era el resultado de investigaciones puramente
lógicas. Dithley no entiende el significado en sentido lógico, sino
como expresión de la vida. La vida misma, esta temporalidad en
constate fluir, está referida a la configuración de unidades de
significado duraderas. La vida misma se autointerpreta. Tiene sentido
hermenéutico. Es la vida misma la que constituye la base de las
ciencias del espíritu.

** Las aporías de una consciencia histórica como sustituto del saber absoluto
La hermenéutica de la vida de D. intenta permanecer así sobre el suelo
de la concepción histórica del mundo. Propone:
  - Al universalismo lógico-abstracto de Hegel
  - A la metafísica de la individualidad romántico-panteísta de origen
    leibniziano.

 
*** El individuo y su contexto histórico
El individuo está en constante formando parte de una circunstancia. No
hay una fuerza originaria de la individualidad como libertad, sino que
ésta es lo que es en la medida en que se impone a la
circunstancias. El hombre está determinado por la relación
individualidad/espíritu objetivo. Pero lo dado, la facticidad con la
que tropieza la libertad, no sólo son barreras, limitaciones y
condicionamientos para la libertad. Son también realidades históricas
que sustentan al individuo, que le dan sus cauces de expresión y la
posibilidad de reencontrarse a sí mismo. Así, no son ya barrera u
obstáculos, sino objetivaciones de la vida.

*** La relación entre individuo y significado
La relación entre individuo y significado es esencial para las
ciencias del espíritu, en dos sentidos:
  - El concepto de lo dado tiene una estructura completamente distinta
    al dato científico-natural. No se trata de nada fijo, sino de algo
    que acontece, adviene, se produce.
  - El conocimiento de las ciencias del espíritu quedará determinado a
    partir de la cuestión d como se vincula la fuerza del individuo
    con aquello que está más allá de él y que le es previo, el
    espíritu objetivo; de como debe pensarse la relación de fuerza y
    significado, poder e idea, facticidad e idealidad de la vida.

Dithley no consigue responder a estas cuestiones y no puede
fundamentar hermenéuticamente las ciencias del espíritu. La causa es
que se enreda en problemas que le llevan a la proximidades del
idealismo especulativo y que no puede librarse de las consecuencias
implícitas de la metafísica idealista.\\

*Dithley y el idealismo hegeliano*. Dithley coincide con Hegel en
  - su crítica a la posibilidad de lo dado
  - su determinación del espíritu como conocimiento de sí mismo en el
    ser otro
  - El pensamiento de la vida como espíritu

Dithley se aparta de Hegel en
  - su fe en la razón como poder cognoscitivo
  - su construcción especulativa de la historia del mundo
  - su deducción a priori de todos los conceptos desde el
    autodesarrollo dialéctico de lo absoluto, que contradice la
    posición central del espíritu objetivo.

Lo que Dithley propugna es
  - partir de la realidad de la vida para comprenderla con conceptos
    adecuados
  - fundamentar así el espíritu objetivo de modo que pueda quedar
    justificada la variedad de formas de vida
  - superar la unilateral fundamentación hegeliana del espíritu
    objetivo en la razón universal, y mostrar como formas de vida la
    religión, el arte y la filosofía, que en Hegel son formas del
    espíritu absoluto y no del espíritu objetivo.

Todo lo cual se puede resumir en una única diferencia: según Hegel, en
el concepto filosófico se lleva a cabo el retorno del espíritu a sí
mismo, mientras que para Dithley, el concepto filosófico no tiene
significado cognitivo sino expresivo.\\


*La interna contradictoriedad de la conciencia histórica*. Dithely no
 rechaza la posibilidad de una forma del espíritu de total
 autotransparencia y plena identidad de existencia y significado (el
 espíritu absoluto de Hegel), aunque la entienda como conciencia
 histórica y no como especulación filosófica. Sería aquella conciencia
 que viera todos los fenómenos del mundo humano e histórico sólo como
 objetos en los que el espíritu se conoce más profundamente a si
 mismo. Esto es, la conciencia histórica como retraducción del
 espíritu a la vitalidad espiritual de donde procede y como
 objetivación de ella. No es en el saber especulativo del concepto,
 sino en la conciencia histórica, donde se lleva a término el saber de
 sí mismo del espíritu. La filosofía mismo no es la consumación del
 espíritu absoluto, sino otra expresión de la vida.Las diversa
 concepciones filosóficas del mundo no son sino expresión del
 polifacetismo, interna riqueza y variedad de la vida que se
 desarrolla en ellas.\\

 Dilthey cree haber superado la metafísica. En realidad lo único que
 hace es colocar la conciencia histórica en un lugar del hegeliano
 saber absoluto, cuando la conciencia histórica no puede ocupar este
 lugar. Si la vida es la realidad creadora e inagotable, entonces la
 constante transformación del nexo de significados que es la historia
 implica la exclusión de un saber que puede alcanzar objetividad. La
 conciencia histórica no es más que un ideal utópico que contiene un
 esí mismo una contradicción.


* La objeiviad del conocimiento hiistórico: condiciones y límites

** La infinitud potencial de la razón histórica

Dilthey intenta legitimar el conocimiento de lo históricamente
condicionado como conocimiento científico y objetivo, a pesar del
propio condicionamiento. Recurre al concepto de estructura o
significado que constituye su unidad y sentido desde su propio centro,
tomado de la hermenéutica —el viejo postulado de la hermenéutica es el
de comprender un texto desde su propio centro. Dilthey, según este
sentido, cree posible pensar en un concimiento de nexos históricos
cada vez más amplios, hasta un conocimiento histórico universal. Pero
este esquema presupone que es posible superar la vinculación a un
punto de partida por parte del intérprete, que es la pretensión de la
conciencia histórica.\\

El problema es cómo es posible tal comprensión inagotable para la
naturaleza histórica limitada. Dilthey se diferencia de Hegel en que
afirma la necesidad de mantener la conciencia de la propia
finitud. Aceptó el concepto hegeliano de espíritu infinito, pero bajo
la forma del ideal de una razón ilustrada que maduraría históricamente
hacia la genialidad de la comprensión total.\\

La infinitud potencial del espíritu no es en la especulación, sino en
la razón histórica donde se actualiza. La conciencia de la finitud no
significa un limitación de la conciencia, sino la posibilidad de la
vida para elevarse sobre toda limitación. Piensa en una comprensión
histórica extendida sobre todo lo que está dado históricamente,
universal, en cuanto está fundada en la totalidad e interna infinitud
del espíritu.\\
Significa suponer una semejanza natural entre todos los hombres y
ampliar las propias vivencias, como punto de partida, transponiendo su
estrechez con la infinitud del mundo histórico revivido. Las
limitaciones impuestas a la universalidad de la comprensión por la
finitud histórica de nuestro ser son sólo de naturaleza subjetiva.

** El método comparativo
La verdadera comprensión es posible por la simpatía. En virtud de
ella, se superan los límites que impone la comprensión de la
causalidad subjetiva de las preferencias y afinidades. Por simpatía
entiende una vinculación congenial e intuitiva que hace
espontáneamente posible para el historiador una comprensión muy
laboriosa y difícil de alcanzar de otro modo. Siguiendo a
Schleiermacher y Ranke, mediante el método comparativo se superarían
las barreras contingentes que representa el círculo de las propias
experiencias y se ascendería así a verdades de mayor generalidad. Pero
la comparación hace las cosas explícitamente simultáneas, que no es
compatible con la idea de un conocimiento histórico. El método
comparativo no puede ser legitimado como método del conocimiento
histórico.

* El conocimiento histórico como autoconodido
Dilthey no considera la vinculación del hombre finito e histórico a su
punto de partida como una restricción de las posibilidades del
conocimiento histórico-científico. La conciencia histórica tendría que
realizar en sí misma la superación de la propia relatividad hasta
alcanzar la objetividad de un concimiento universal.\\
El problema es cómo justificar la esta pretención sin implicar un
concepto de saber absoluto, filosófico, por encima de toda conciencia
histórica.\\

La escuela histórica se perfila como crítica a esta prentesión de la
conciencia folosófica de contener en sí la verdad entera de la
historia del espíritu. Su reivindicación de la conciencia histórica,
frente al apriorismo de la conceptción hegeliana, se basa en al
evidencia de que la conciencia hhumana no es un entendimiento infinito
para el que todo puede ser simuláneo y presente por igual. La
indentidad absoluta ed conciencia histórica y finita. No le es dado
desembarazarse del nexo de efectos que es la historia.\\

Dilthey dá respuesta a las cuestiones sobre la diferncia entre la
conciencia histórica de Dilthye y el saber absoluto de heger, así como
la elevación de la conciencia histórica sobre sí misma y hacerse capaz
de un concimiento hostórico objetivo.\\
La conciencia no es tanto un debilitarse de sí mismo
para fusionarse con el todo ed la vida que nos subyace (Ranke), cunto
una progresiva posesión de la propia posibilidad de comportarse
históricamente. El conocimiento histórico no consiste en una pura
aplicación a la tradición de los patrones de la propa comprensión de
la vida. Sería la relación reflexiva de comprensión de lo particular
desde lo general, y viceversa. Esto es, una forma de autoconocimiento.

** La estructura hemrenéutica de la vida

El intento de Dilthey de fundmentar científicamente el conocimiento
hitórico se resolvería en la tarea de hace comprensible, desde la vida
misama, cómo surge la conciencia científica sobre la base del
autoconocimiento. Es decir, Dilthey parte de la vida, que ya contiene
el saber y estár referida a la reflexión.\\
El distanciamiento respecto al nexo de nuestro propio hacer es lo que
hace posible la reflexión.\\
Primero se forma una concepción natural de la vida sobre sí misma,
antes de toda objetivación científica.\\
Ésta se objetiviza en la sabiduría de refranes y leyendas, pero sobre
todo en las grandes obras de arte, en las que algo espiritual se
desprende de su creador.\\
El arte es pues, un órgano especial de la cmprensión de la vida. En
él, la vida se abre con una profundidad inaccesible a la observación,
a la meditación y a la teoría.\\

Cualquier expresión de la vida opera ya un cierto saber y es
reconocible en ella una cierta verdad.\\
Todas las formas de expresión son en su conjunto conformacione de
espíritu objetivo.\\
En el leguaje, las constumbres, las normas jurídicas, el individuo
está siempre elevado por encima de su particularidad. La entrega de
objetivos comunes, la dedicación a una actividad para la comunidad
libera al hombre de la particularidad y de lo efímero.

* La ciencia como hecho de la vida

Tanto la formas prerreflexivas de expresión como en la reflexión, el
saver de la vida aspira a la estabilidad. Dilthye concibe la
objetividad del conocimiento histórica, y del conocimiento científico
en general, como meta suprema de la tendentica natural de la
vida. Mediante el método experimental se produce la elevación, por
encima de la contingencia subjetiva de la observación, hasta el
conocimiento de la regularidad de la naturaleza. Las ciencias del
espíritu intentan también elevarse metódicamente por encima de la
contingencia sibjetiva del propio punto de partida y de la tradición
propia, hasta alcanzar la objetividad del conocimiento básico.\\

El nexo de vida y saber es un dato originario. La filosofía no puede
consistir en un intento de fundamentación teórica desde la unidad de
un principio especulativo. La filosofía es una objetivación más de la
vida que contínua el camino de la auto-reflexión histórica. Por eso no
le afecta la objeción de relativismo. Esta objeción sólo puede
proceder de un intelectualismo al que, la fundamentación de la
filosofía en la vida, quita toda base.\\
Las constumbres, religión etc, son expresión de un saber de la vida
sobre sí misma. El ascenso del individuo al espíritu objetivo se
realiza a través de su entrega a la tradición.\\

El impulso científico surge de la necesidad interna a la vida de
estabilizar, en un medio incesante de la percepciones sensoriales, de
los deseos y sentidos, algo fijo y estable que haga posible un modo de
vida continuado y unitario. Este rendimiento del pensar es inmanente a
la vida y se realiza en las objectivaciones del espíritu que sustentan
al individuo en la medida en que éste se entrega a la objetividad de
la cultura.

* La influencia en Dilthey del ideal científico del positivismo
Las refelxiones espirituales sobre la fundamentación de las ciencias
del espíritu no son del todo congruentes con su enraizamiento en la
filosofía de la vida. Estas reflexiones se orientan más bien desde un
ideal científico propio de la Ilustración y de reminiscencias
cartesianas que no entiende el saber y la reflexio´n desde la
imanencia general del saber en la vida, sino como un movimiento
orientado frente y contra la vida.\\
Dilthey entiende la certeza propia de las ciencis del espíritu como la
perfección de la certeza vital de la vivencia. Hay que poner en duda
prejuicios, dogmatismos, etc. hasta llegar a resultados seuros.\\
La necesidad de un conociiento estable sigue teniendo el carácter de
necesidad de protección frente a las tremendas realidades de la
vida.\\
El espíritu humano que busca protección y seguridad, debe oponer a la
insondabilidad misteriosa de la vida, a su rostro temible, la
capacidad ceintíficamente formada de la comprensión. Ésta debe abrir
la vida en su ralidad socio-histórica tan por copmleto que el saber
proporcione protección y seguridad en este uso persona, a pesar del
misterio de la vida.\\
La objetividad del conocimiento histórico no puede ser la de las
ciencias inductivas, sino que se adquiere de una forma distinta. La
fundamentación de las ciencias del espíritu en la filosfía de la vida
quiere hacer valer esto. Pero el positivismo epistemológico, al que
D. no logra escapar, avaba por anular la peculiaridad condicionante
del conocimiento histórico.\\

Dilthey, en un sentido schleiermacheriano, intenta poner en
consonancia la forma de conocimiento de las ciencias del espíritu con
los modelos metodológicos de la ciencias de la naturaleza. Pretende
ponerlas a la altura de la objetividad válida en las ciencias de la
naturaleza.\\
Para ello, la hermenéutica romántica le sirve porque no tiene en
cuenta la esencia histórica de la experiencia. Presuponía que el
objeto de la comprensión es el texto que hay que descifrar y
comprender en su propio sentido. El encuentro con el texto es un
autoencuentro del espíritu. Pensando el mundo histórico como un texto
que hay que descifrar, cree haber justificado epistemológicamente las
ciencias del espíritu.\\
Sin embargo, en la medida que la hermenéutica romántica le servía de
modelo, se vio obligado a reducir la historia a historia del espíritu,
y a medio afirmar y medio negar la filosofía hegeliana.\\

La significación de la epxeriencia vital, individual y general para el
conocimiento de las ciencias del espíritu es importante, pero incapaz
de verificación. Necesita de ser perfeccionada por la inducción
metadológica de la ciencia. La escisión interna que acarcteriza el
esfuerzo de D. se debe a la coacción que ejerce en él el ideal
metódico de la ciencia moderna. Sin embargo, la tarea no puede ser
otra que la de describir más adecuadamente la experiencia operante en
las ciencias del espíritu y la objetividad que en ellas puede
alacanzarse.

